### ISSUE TITLE
Не проходит OAuth авторизация

### ISSUE THREAD

**Issue by pravets** [Zverik/every_door#1]
После нажатия кнопки "Авторизовать" на стороне OSM в приложении появляется ошибка:

OAuth Error 
FormatException: Unexpected character (at character 1) <!DOCTYPE HTML PUBLIC "-// IETF//DTD HTML 2.0//EN"> 

Возможно, конечно, временные глюки на стороне OSM и мне просто не повезло.

**Comment by yegorm** [comment]
У меня тоже
![Screenshot_2022-03-26-14-40-48-80_5bbe6680bf1a18f54c554c43678e9cdb.jpg](https://user-images.githubusercontent.com/3057812/160237995-def5d8ca-aa87-44ad-aa94-501a383b5588.jpg)

**Comment by deevroman** [comment]
Об этом известно https://t.me/ruosm/638011

**Comment by Zverik** [comment]
Fixed in c3bcf05decb2d86bdc239ec09ef8baad11f62a8a
