### ISSUE TITLE
It doesn't display Mo-Su when you confirm changes in opening_hours

### ISSUE THREAD

**Issue by danilax86** [Zverik/every_door#10]
Initial state is:
 <img src="https://user-images.githubusercontent.com/46713109/160894234-654f3846-4937-4d6e-aedc-4b73af1d9e53.png" width="300" />

Then, if you go to opening_hours section and tap blue round "confirm" button...
 <img src="https://user-images.githubusercontent.com/46713109/160894946-900aeea8-c5b2-488f-bf16-8a35b792be4a.png" width="300" />
 
 It says only hours, but not days:
 <img src="https://user-images.githubusercontent.com/46713109/160895151-ab207b0e-4cbb-4ccc-92ba-1d6249097e16.png"
 width="300" />

It is fine when a shop, for example, works not the whole week, e.g. Mo-Fr, days and time stay still after confirmation

**Comment by Zverik** [comment]
Yes, that is the intended behaviour. "Mo-Su" part is optional, so I decided to keep it short. Both "10:00-21:00" and "Mo-Su 10:00-21:00" mean the same.
