### ISSUE TITLE
Find a website for public translations

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#101]
Transifex does not support `.arb` files. Who does? Or maybe write a converter?

**Comment by Eleferen** [comment]
По роботе изучал все существующие доступные сервисы перевода (ну или почти все). Weblate - оказался лучшим из них, как по доступности использования, так и по функционалу. Так что однозначно рекомендую его.

**Comment by Zverik** [comment]
Ну да, меня только смущает требование «трёх месяцев активной разработки» в панели запроса. Но я спрошу у них всё равно.

**Comment by Zverik** [comment]
https://hosted.weblate.org/projects/every-door/app/
