### ISSUE TITLE
Support `power=transformer/substation` in micromapping mode

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#102]

**Comment by Zverik** [comment]
All `power=*` tags should be available for micromapping.

**Comment by Zverik** [comment]
Yeah, they are not at the moment. I've added the todo label :)

**Comment by Zverik** [comment]
BTW what is the app below plz? I'd like to check if there's something in it that might improve my app :)

**Comment by deevroman** [comment]
https://github.com/ubipo/osmfocus

**Comment by Zverik** [comment]
Done in 0.1.6.
