### ISSUE TITLE
[Proposal] Expand limits for breaks, pls

### ISSUE THREAD

**Issue by danilax86** [Zverik/every_door#11]
There are only 2 break periods available to add. It is impossible to add more.

Sometimes it is like that:
Here I manually added breaks via raw tags editor. It shows correctly in the app though
<image src ="https://user-images.githubusercontent.com/46713109/160929187-58f7cb85-2ed9-409e-bf17-658fde04d3fe.png" width=200 />

**Comment by Zverik** [comment]
Thanks, I didn't think a venue would have so many breaks. I've increased the limit to four for the next version.
