### ISSUE TITLE
Ref hints should not change if already selected

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#112]
It seems like I accidentally changed the ref

https://user-images.githubusercontent.com/25708359/164791492-28c514ff-cd08-4d0e-8acb-e71130b67a57.mp4

**Comment by Zverik** [comment]
I do not understand the issue. You've selected `ref=3`, and while the options were changing, the chosen value stayed the same.

**Comment by deevroman** [comment]
After I have selected `ref`, I don't expect any changes in this field. But when I type the text in Flats I see some changes. This is very annoying and makes you double-check the `ref` value.

**Comment by Zverik** [comment]
The idea is, you _first_ type in the flats, and then choose the ref value. That way the ref chooser is prepared, with most likely refs. It would also solve your issue with missing `ref=2` by default.
