### ISSUE TITLE
Why is ref=2 skipped by default?

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#114]
![Screenshot_20220423-003417.jpg](https://user-images.githubusercontent.com/25708359/164798980-ad9b6a17-5146-4052-8d07-e8d3eaa26038.jpg)

**Comment by Zverik** [comment]
Because I decided that people usually start entering entrances from a building side. And `ref`s are usually used on big buildings, with 3+ entrances.

**Comment by deevroman** [comment]
> And refs are usually used on big buildings, with 3+ entrances.

A controversial statement. Yesterday, for example, I met a lot of people at home with two entrances. On the one hand, the second entrance is usually a service entrance, but often it has ref=2 with the same apartment numbers.

<details>
<summary>Details</summary>

<img width="569" alt="Снимок экрана 2022-04-23 в 10 47 03" src="https://user-images.githubusercontent.com/25708359/164885492-84582415-fa45-48c2-b03f-3961ea186ead.png">

</details>

There is an even more special case -- two-storey houses in villages. They often have 2-3 entrances, and often are not signed `addr:flats`, so hiding ref=2 is strange.

**Comment by Zverik** [comment]
I don't agree, but this is not a hill I'm ready to die on. Fixed in 0.1.8.
