### ISSUE TITLE
Support for the 19th zoom level for osm tiles

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#132]

**Comment by natrius** [comment]
Why is zooming restricted at all? Because of that https://github.com/Zverik/every_door/issues/168 problem i wanted to manually change to my position and as i don't even know where i am currently i don't know if 10 minutes of scrolling in one direction leads somewhere :D

**Comment by natrius** [comment]
I can assure you, my GPS is working perfectly fine and fast :) Thanks for the recommendation, still!

Why does it matter for zooming at all? Deactivate satelite imagery when zoomed out to far or switch automatically to osm-map when zooming out too far for example. But zooming should be possible in my opinion :)

**Comment by Zverik** [comment]
Done in 0.5.
