### ISSUE TITLE
Support barrier=* in micromapping mode

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#134]

**Comment by Zverik** [comment]
Done in 0.1.12.

**Comment by deevroman** [comment]
Should this work for barrier=* owned highways?

**Comment by Zverik** [comment]
Yes, all _nodes_ with a `barrier=*` must be editable.

**Comment by deevroman** [comment]
Dont't work :(

https://osm.org/node/7878424994

![Screenshot_20220430-214948.jpg](https://user-images.githubusercontent.com/25708359/166118841-f3ec5b84-64e9-4c06-940c-045520a49aa5.jpg)

![Screenshot_20220430-215044_OSMfocus Reborn.jpg](https://user-images.githubusercontent.com/25708359/166118845-45630e69-2527-425b-854b-94abfd6da7c8.jpg)

**Comment by Zverik** [comment]
Ah, found the error, thanks. Barriers will appear in 0.1.13.
