### ISSUE TITLE
Override some presets

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#140]
E.g. street_lamp. That won't make translations appear, but at least we would have some missing fields.

**Comment by pyrog** [comment]
… or add new preset i.e. specific to countries.

For example, `ref:FR:SIRET` that is very useful to get official data about shops…

[SIRET](https://en.wikipedia.org/wiki/SIRET_code) is a 14-figure numerical identifier that should be checked and a click on the tag should open an URL on the SIREN database.

**Comment by Zverik** [comment]
Superceded by #174, also the repo is maintained now.
