### ISSUE TITLE
Add level for entrances

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#143]

**Comment by Zverik** [comment]
Could you please elaborate?

**Comment by mfbehrens99** [comment]
![grafik](https://user-images.githubusercontent.com/58851724/166482464-fe667a65-f2e6-4ede-ad5e-912584559f43.png)
Entrances enter the building on a specific level

**Comment by Miroff** [comment]
+1 for this issue. Different entrances may lead to different floors. E.g. cellar door, or external stairs to second floor entrance. 

Taginfo says, there are 70k entrances with level tag in OSM.

Example of such building: https://overpass-turbo.eu/s/1iL4

**Comment by deevroman** [comment]
How many out of 70k have level!=0? :)

**Comment by Zverik** [comment]
```
  48593 0
  10818 1
   4417 -1
   2393 2
    636 3
    440 -2
    243 -0.5
    239 0.5
    230 0;1
    191 4
```

**Comment by mfbehrens99** [comment]
In my opinion level is more relevant that a ref tag. Additionally, level is very important for routing.
