### ISSUE TITLE
Option to add an address point, without building

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#159]
Maybe a kind of "building" in the entrances mode?..

Useful for buildings with multiple addresses.

**Comment by pyrog** [comment]
At least in France, an address point could be on the fence, a pillar…

Note: the french community want a unique `addr:house_number` (with an `addr:street` or an associated_street relation)
**and only if necessary** a `contact:house_number` (and an `contact:street` ) .

**Comment by Zverik** [comment]
Done in 0.4.
