### ISSUE TITLE
(A bit) misleading message 'no amenities around..' in certain scenario

### ISSUE THREAD

**Issue by yegorm** [Zverik/every_door#16]
версия 1.1 андроид

**подготовка:**
1. поставить апп с нуля
2. прийти в место, где есть POI
3. запустить приложение, скачать POI
4. закрыть приложение

**основной сценарий**
1. открыть приложение
результат - в области POI выдается текст "no amenities around..", которое позже сменяется информацией по POI
комментарий - такой текст в этом сценарии немного озадачивает - мы же знаем, что POI  же есть вокруг, и что приложение о них уже знает.
Ожидаемый результат - как-то уточнить отражение состояния. Варианты:
- сообщение  типа "у меня что-то есть в базе, вот щас поищу и покажу.. или нет"
- просто спиннер

**Comment by Zverik** [comment]
Вероятно, починил в 0.1.2. Проверь и закрой тикет, когда придёт ссылка :)

**Comment by pravets** [comment]
Не починилось. При старте говорит нет POI, дёргаешь карту и данные подгружаются.

**Comment by yegorm** [comment]
> Вероятно, починил в 0.1.2. Проверь и закрой тикет, когда придёт ссылка :)
Илья, что-то пока не поменялось - наблюдаю сц в 0.1.2

**Comment by Zverik** [comment]
Понятно, спасибо. Мне сложно это отладить самому, потому что до ближайшего заведения 200 метров :)  Попробую другие способы.

**Comment by Zverik** [comment]
В версии 0.1.4, которую я разослал вчера вечером, эта проблема должна была уйти. Посмотрите, плз.

**Comment by yegorm** [comment]
> В версии 0.1.4, которую я разослал вчера вечером, эта проблема должна была уйти. Посмотрите, плз.

Да, стало хорошо, спасибо!
