### ISSUE TITLE
Editing trees

### ISSUE THREAD

**Issue by Binnette** [Zverik/every_door#163]
Hi @Zverik, thank a lot for your new editor "Every Door" 👍 

I like to use my phone to edit trees. And currently the default tags shown for trees do not "suit me".

Here are the current default fields when editing a tree:
![image](https://user-images.githubusercontent.com/6597721/167831244-92ec097f-36c1-4102-9271-be41af40ee55.png)

I would love to see the additional fields:

1. genus
2. species
3. And why not: age

![image](https://user-images.githubusercontent.com/6597721/167831745-098e48d9-e31c-4f40-9ef5-6c5d33539e60.png)

In fact genus and species are the most important tags to determine the kind of a tree.

Thanks a lot and have a nice day 👍

**Comment by Zverik** [comment]
Hi Binnette, thanks for using the editor! With this we have two means of proceeding. First is make a pull request to the [presets repository](https://github.com/openstreetmap/id-tagging-schema/). I've recently gained the owner rights on that, so it won't be too long to merge.

Or you could wait for #119 and make your own preset for trees, with searching and stuff. But it would take a few months.

**Comment by Zverik** [comment]
Yes.

**Comment by Binnette** [comment]
I just created a PR openstreetmap/id-tagging-schema#455
Thank for reviewing it 👍
