### ISSUE TITLE
UI layout switching not ideal

### ISSUE THREAD

**Issue by natrius** [Zverik/every_door#169]
The map part is tiny and the other part quite big. I managed to half the screen again with some wiping. I managed to switch for 2 or 3 times and now i have the 50:50 split-screen again. 

The 'wrong' view was as followed:
![signal-2022-05-12-092106_001](https://user-images.githubusercontent.com/7243447/168015277-05c373ae-c89f-431a-a9e0-a2d54bc76597.jpeg)

After a bit more testing it seems like when scrolling upwards on the map part it increases the size of the bottom part and when scrolling downwards its decreasing. But... its not consistent and just sometimes. Strange behavior.

**Comment by Zverik** [comment]
Please see the first answer in [the FAQ](https://every-door.app/en/faq.html).

**Comment by natrius** [comment]
Can you please reopen this? I'm aware of that but i haven't downloaded anything at all and i was able to change the layout with swiping up and down in the map reandomly. If its needed, i can try to record a video.

**Comment by Zverik** [comment]
Why do you want to change layout? The whole idea is that the map is small: you look at shops and amenities in the list, not at the map.

**Comment by bryceco** [comment]
@Zverik For a new user who downloads the app at home, possibly far from amenities, the first-time launch experience is somewhat jarring: a small map and lots of empty white space looks like something went wrong. 

It looks like you enlarge the map when scrolled far from your current location. I'd change the logic to enlarge when either you're far away OR the list of amenities is empty or very small.

**Comment by bryceco** [comment]
@natrius The map is smaller whenever the pin is within about 100 meters of your current GPS location. Presumably to provide more space to list amenities in your immediate vicinity.
