### ISSUE TITLE
Map very small

### ISSUE THREAD

**Issue by Akiyamka** [Zverik/every_door#170]
When you first open the map is very small, despite the empty space at the bottom, and I see no way to expand it

<img src="https://user-images.githubusercontent.com/6587585/168050844-ed7e01a4-995a-46ff-b6c3-b42cf716a058.png" alt="Screenshot_20220512-122415" style="max-width: 100%; width=100px">

**Comment by Zverik** [comment]
Please see the first answer in [the FAQ](https://every-door.app/en/faq.html).
