### ISSUE TITLE
"Every Door" in title is cut off for smaller phones

### ISSUE THREAD

**Issue by habi** [Zverik/every_door#171]
I'm using the app on an iPhone 12 mini, hence with limited screen space.
The title bar shows "Every Do...", as can be seen in the screenshot.
I *think* that with some minimization of white space between the icons the whole text could fit.
![IMG_9212](https://user-images.githubusercontent.com/1651235/168088494-37f80631-3696-484d-b1f7-ee73e1466f6f.jpeg)

**Comment by Zverik** [comment]
Thanks for testing the app! The label is ideed useless. With #161 it will be removed.
