### ISSUE TITLE
Field icons displayed as texts on a POI

### ISSUE THREAD

**Issue by yegorm** [Zverik/every_door#175]
I noticed this behavior on this particular POI (node id = 1123362163). Probably the reason is in its unusual type ('theatre') . What usually appears as icons here turned to texts and it causes too much white space
![Screenshot_2022-05-12-18-42-45-37_5bbe6680bf1a18f54c554c43678e9cdb.jpg](https://user-images.githubusercontent.com/3057812/168118788-1ac2ad64-53d6-4365-8e10-b21b9e78fe08.jpg)

Version 0.2.1 Android

**Comment by Zverik** [comment]
Done in 0.4.
