### ISSUE TITLE
Make facebook tags clickable

### ISSUE THREAD

**Issue by pyrog** [Zverik/every_door#176]
A click on website open the URL, but not for `contact:facebook`, `contact:instagram`…

Note: accept also `facebook` (in fact all common tags with or without `contact:` prefix)

**Comment by pyrog** [comment]
See also #178

**Comment by Zverik** [comment]
They are already clickable. If you found one that isn't, please link the object.

**Comment by pyrog** [comment]
For example : https://www.openstreetmap.org/node/7495152594
`contact:facebook=PauseRelaxante` should open https://www.facebook.com/PauseRelaxante

**Comment by Zverik** [comment]
Yeah, indeed. Thanks.

**Comment by Zverik** [comment]
Done in 0.4.
