### ISSUE TITLE
Sort the imagery list by area size

### ISSUE THREAD

**Issue by pyrog** [Zverik/every_door#177]
i.e. in France, the official source of background imagery is "BD Ortho IGN".
Could you use the [iD imagery index](https://github.com/ideditor/imagery-index) or [JOSM imagery index](https://josm.openstreetmap.de/maps), or provide a way to configure it manually ?

**Comment by Zverik** [comment]
The iD imagery index is already used. See the "Background imagery" page in the Settings. I have been using Estonian ortho imagery since December.

**Comment by pyrog** [comment]
So nice, thank you 😃 

<img width="25%" src="https://user-images.githubusercontent.com/2158081/168252659-fe5ea702-a67e-4167-9732-bae04cc967d1.jpg"/> <img width="25%" src="https://user-images.githubusercontent.com/2158081/168252692-2f78f9b4-13c1-41d2-85ea-0c08b53dc630.jpg"/>

The list should be sorted by **local,** **national** and **international** sources.

In France:
* Cadastre ?? (this is not a "satellite imagery)
* BDOrtho IGN
* Ortho HR
* Ortho HR 2018

Then:
* ESRI World Imagery
* …

**Local** is for i.e. a big city like Paris, Lyon…

**Comment by Zverik** [comment]
Nice suggestion, thanks. I'll see if this is possible.

**Comment by Zverik** [comment]
The sorting was already good enough, but I improved it a bit in 0.4.
