### ISSUE TITLE
Filter a lot of the information=* stuff

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#18]
It seems like the information=* tag is somehow polluting the list of shops. When I go to my local mall I see some hiking guideposts (information=guidepost) and many information boards some of them should be moved to the micromapping or should be removed from the list.

The only important information values are:

- information=office
- information=visitor_centre

What do you think?

The same applies to leisure=picnic_table. I would also move this to the micromapping section.

Is the micromapping section implemented yet? I could not reach it for no :(

**Comment by pyrog** [comment]
Guideposts, boards and i.e. drinking water are important for hikers 😉
This editor could have several profiles for i.e. **hikers**, **shoppers**, **firemen**… (filters + imagery + favourites tags…).

**Comment by Zverik** [comment]
These comments are from 1.5 months ago, I've added a micromapping mode since then.

Custom profiles may be supported later: #119.
