### ISSUE TITLE
Entrance does not snap to building contour

### ISSUE THREAD

**Issue by danieldegroot2** [Zverik/every_door#186]
https://www.openstreetmap.org/node/9735201466/history
should snap to the building contour according to #62 but has not done so.

(I found this floating entrance while fixing tagging on a nearby node.)

**Comment by Zverik** [comment]
These cases should be easier to find, since the editor adds `fixme=*` tag to non-snapped entrances now. Also this exact issue could be solved later with #160. Thanks for reporting!
