### ISSUE TITLE
Indoor door does not have unspecified values removed

### ISSUE THREAD

**Issue by danieldegroot2** [Zverik/every_door#187]
https://www.openstreetmap.org/node/9735466256/history
should have unspecified values removed, but this is not the case (or its value was not properly saved, or defined by the user..)
`door=yes/manual/main_entrance`
Removed => the key `door` is not uploaded if not specified, or is alternatively defaulted as `door=` with no values and automaticly removed before uploading.

**Comment by Zverik** [comment]
This is, in the edit the value of `door` was specified, chosen manually from the list of [the most popular taginfo values](https://taginfo.openstreetmap.org/keys/door#values). Which contain `yes/manual/main_entrance` with 138 uses. So I don't see any error here.

**Comment by danieldegroot2** [comment]
Ok, I see it's not an issue on your side. Thanks for the information. :-)

(I've looked at these tags and shared my findings on the OSM World Discord.)
