### ISSUE TITLE
[Feature Request] Zoom using the +/- volume button

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#19]
Perhaps this function is not relevant now because of autoscaling, which locks the scale. But if this changes in the future, it was convenient to zoom the card with the volume buttons.

In Every Door, this will be especially relevant because:

1. Due to the small size of the card, it is difficult to zoom
2. It is impossible to change the zoom with your fingers without changing the current position. And this entails changing the order of the POI list, which is annoying.

One of the disadvantages of this function is that you will have to add a new setting

An example of the implementation can be found in https://github.com/Helium314/StreetComplete

**Comment by deevroman** [comment]
Oh, in 0.1.2, zooming with a finger does not change the current position, and automatic scaling does not interfere now. In principle, now this feature is no longer needed

**Comment by Zverik** [comment]
Yeah, the idea is good, but I could not find a way to intercept volume buttons in Flutter :(

**Comment by deevroman** [comment]
https://stackoverflow.com/questions/55678814/access-hardware-buttons-like-the-volume-buttons-from-flutter

**Comment by Zverik** [comment]
I saw this — alas the method is still unreliable: as a comment there mentions, it requires a weird permission on Android, and the behaviour is unstable on iOS. And in #127 I've added on-screen buttons, so this method is redundant.
