### ISSUE TITLE
Cuisine demonyms

### ISSUE THREAD

**Issue by bgo-eiu** [Zverik/every_door#192]
This is a feature suggestion which seems feasible to implement. I was impressed by the number of possible languages to select in the translation menu - in continuing with the idea of allowing for a "complete" list of options, the cuisine menu could include every national demonym with the correct format on the list. Tags like Pakistani, Bosnian, Senegalese, and so on; this is not the only way cuisines can be tagged of course but it covers a lot of ground. This could help people be more specific when they might not consider that an option.

There are also some nationalities where the correct format may not be obvious to people that could use some standardization. Not everyone knows that Somali and not Somalian would be correct for Somali food, and there are some more hard to guess ones out there like Burkina Faso = Burkinabe, United Arab Emirates = Emirati, Kiribati = I-Kiribati, and so on.

**Comment by matkoniecz** [comment]
Are cuisine suggestion also coming from iD presets?

If yes, then adding some missing ones like in https://github.com/openstreetmap/id-tagging-schema/pull/252 would be a proper fix.

**Comment by Zverik** [comment]
Agreed, this is for the iD tagging schema. See [the faq](https://every-door.app/en/faq.html#how-to-change-or-translate-preset-fields) for links.

**Comment by bgo-eiu** [comment]
I'll bring it up there, it seems like they have some ideas about how to do this
