### ISSUE TITLE
Add zoom buttons to "Choose location" map page

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#194]
When adding a point, the next page to open is to fine-tune location. I'm not sure what the current rules are for zoom, but I frequently find the need to zoom in, especially in micromapping mode. I know you can pinch to zoom, but could we get zoom buttons on that page as well?

**Comment by Zverik** [comment]
Oh, indeed, thanks. I just forgot.

**Comment by Zverik** [comment]
Done in 0.4.
