### ISSUE TITLE
Walking papers mode

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#197]
A fourth mode that allows scribbling lines on top of a map / imagery layer. No uploading anywhere, but with a option to export to geojson. Below two rows of buttons: colors for roads / buildings / paths / fences. And "undo", "eraser" (later, too hard to make), "add a note". The latter can optionally be uploaded to OSM — which solves #47. And in time photos can be attached there as well.

Up-to-date todo list:

- [x] Display lines on the map chooser panel
- [x] Move add notes button on top of the drawing layer
- [x] Tappable notes on the map
- [x] Switch between OSM and scribble notes
- [x] Smart suggestions for scribble notes
- [x] Style chooser button
- [x] Proper design for style chooser and undo buttons
- [x] Tap-and-slide for choosing a mode
- [x] Translations for modes
- [x] Eraser mode for taps
- [x] Eraser mode for drawing a line
- [x] Black/white casing for scribbles
- [x] Fix the flicker between finishing drawing and adding a scribble to the map
- [x] Lock button (inside the mode menu / replaces the mode menu).
- [x] Fix undo states and deleting notes.
- [ ] Render labels on the WMS layer (server)

![walking-papers-everydoor](https://user-images.githubusercontent.com/766031/168466779-a0f344c6-c97d-4026-b419-90699dd13474.jpg)

**Comment by Zverik** [comment]
Pavel in the chat adds that it would be nice to have different legends (buttons) for different tasks. E.g. surfaces, "lit=*", paths and streams, etc. Probably it could be a single big list of things, but with a manual assignment of colors and buttons.

**Comment by Zverik** [comment]
Types I used in my walking papers:

* Road and track
* Footway and path
* Wall and fence
* Power line
* Stream (and ditch/drain?)
* Free-form writing.

Also maybe lit=yes/no, cycleway=shared/designated, steps?

**Comment by Zverik** [comment]
For map notes (not osm), which should be very short, show a list of previous / nearby notes. Useful for marking surfaces and other data.

**Comment by jidanni** [comment]
All I know is if these are personal notes and not OSM Map Notes, then I would pick a different name: mumbles, etc.

**Comment by danieldegroot2** [comment]
To-do list (optional items are without checkbox); you may edit this message.

- [ ] Basic scribbling mode (red)
- [ ] Define colours
-- Colour customization (Colour wheel)
- Size selection
- Opacity slider
- Define shapes/emojis
- Option to move / copy/cut-paste
- [ ] Undo button
- Redo button
- [ ] Clear button
- Eraser tool
- [ ] Add note button
- [ ] Simple legend
- [ ] Legend customization
- [ ] GeoJSON export logic
- [ ] GeoJSON export button
- Export as image to photo library or elsewhere (not a screenshot)

**Comment by Zverik** [comment]
https://telegra.ph/How-I-won-50000-Telegram-Sticker-App-Contest-using-Flutter-04-06

**Comment by Zverik** [comment]
Given we cannot add transparent WMS overlays to iD, I've added [an issue](https://github.com/openstreetmap/iD/issues/10204) for a data layer in there.
