### ISSUE TITLE
"Su off" breaks the opening hours parser

### ISSUE THREAD

**Issue by kmpoppe** [Zverik/every_door#198]
For [this](https://www.openstreetmap.org/node/412725782) node the OH editor doesn't load for me, other entries work fine.

Any ideas?

Kai

**Comment by Zverik** [comment]
Yeah, I've got another report about that. The cause is "Su off" string: I forgot it is valid, and parsing breaks. For now you can use the raw tags editor for that, I'll fix this in 0.4.

**Comment by Zverik** [comment]
Done in 0.4.
