### ISSUE TITLE
When not translation is available, fall back to English not German

### ISSUE THREAD

**Issue by Binnette** [Zverik/every_door#200]
Hi @Zverik, yesterday I introduced Every Door to the members of the OSM Grenoble (France). They installed the app directly from the Play Store Android. And when running the app, the interface was in German.

I know that somebody already translated the interface in France. But I find interesting that you set English (instead of German) at the default fallback when user language is not yet supported.

Thanks 👍

**Comment by Zverik** [comment]
Fixed in 0.4.
