### ISSUE TITLE
Allow to manually set a street name in the AddressForm widget

### ISSUE THREAD

**Issue by nbaksalyar** [Zverik/every_door#204]
Currently, [`AddressForm`](https://github.com/Zverik/every_door/blob/fd5e7d54c5745ebf4803cf52c09e4cd90bfdbbc2/lib/widgets/address_form.dart#L147-L156) uses `RadioField` to show nearest streets in the radius of 100m. However, sometimes this list of streets is not complete so I think it would be helpful to allow setting a street name manually.

**Comment by zekefarwell** [comment]
Yes this would be very good.  I found that the proper street name wasn't available[ in this case](https://www.openstreetmap.org/node/2833009509/history) so I had to enter it incorrectly and then come back later to fix with a different editor.  In the screenshot below I was trying to add a POI with `addr:street=Pearl Street`, but that wasn't an option.  If there was a custom field I would have just typed it in.

<img width=300 src="https://user-images.githubusercontent.com/281482/170166607-efbbad73-8893-4b3c-b4ed-6171126d6f85.jpg">

**Comment by Zverik** [comment]
The reason I'm hesitant to add a free-form editor for a street name, is that it might lead to broken `addr:street` values: some that resemble road names, some just plain wrong. It is actually a very rare case (I think) that an amenity is addressed with a road name that's not there.

So this option would require I guess real-time looking for a similar names around and suggesting these.

**Comment by Zverik** [comment]
Done in 0.7.
