### ISSUE TITLE
Language chooser in settings

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#211]

**Comment by damjang** [comment]
Yes, add it please, so everyone can chose the language independently of the android language: or automatic or manual selection. Thank you

**Comment by deevroman** [comment]
> not sure 

I think it would be interesting to read why StreetComplete added language selection after all. https://github.com/streetcomplete/StreetComplete/issues/2643#issuecomment-792952040

**Comment by Zverik** [comment]
All good points, thank you @deevroman.

**Comment by Zverik** [comment]
https://stackoverflow.com/questions/55889889/how-to-change-a-flutter-app-language-without-restarting-the-app

**Comment by Zverik** [comment]
Done in 0.10.
