### ISSUE TITLE
Artifacts during scaling

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#218]
https://user-images.githubusercontent.com/25708359/169692939-0239ba79-9fd4-4a22-b636-4352d3445f53.mp4

**Comment by Zverik** [comment]
Sorry, but I cannot fix this. These artifacts are also visible e.g. with Leaflet on the web in some browsers. If you want to push this upstream, here it is: https://github.com/fleaflet/flutter_map/issues

**Comment by deevroman** [comment]
Can you please suggest a specific issue?

**Comment by Zverik** [comment]
No idea, probably there isn't one. You can use [this leaflet issue](https://github.com/Leaflet/Leaflet/issues/3575) as a template.
