### ISSUE TITLE
Keep the map big when the screen is big enough for all tiles

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#222]
![big_screen](https://user-images.githubusercontent.com/766031/169704368-c24ddc26-1b18-4ccb-9603-8f45b3b986ed.jpg)

**Comment by willemarcel** [comment]
Maybe making the size of the POIs area adjustable could be a better solution. I felt the need to see the map bigger, even when I had a full list of POIs.

**Comment by Zverik** [comment]
Done in 0.5.
