### ISSUE TITLE
[Bug] Entrances are not placed where dropped when map is rotated (0.4.0)

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#229]
I enjoy the map rotation capability. However, in Entrance mode, I had the map rotated, and when I dragged an entrance onto the map, it left the point in an unexpected location. I did not test this thoroughly, but I expect it put it where it would have been if the map was north-up.

As far as I can tell, it works as expected in Micromapping mode (I didn't test POI mode).

**Comment by Zverik** [comment]
Yeah, the entrances mode is completely broken wrt map rotation. Thanks for the report, I'll fix it in 0.5.

**Comment by Zverik** [comment]
Fixed in 0.5. See also https://github.com/fleaflet/flutter_map/issues/1283
