### ISSUE TITLE
Schools do not have opening hours

### ISSUE THREAD

**Issue by matkoniecz** [Zverik/every_door#234]
When browsing `amenity=school` is highlighted as missing `opening_hours`

At least in my region this is not taggable as schools do not have opening hours.

**Comment by Zverik** [comment]
It's okay to have some fields missing: the editor is not a validator, it merely shows tags that you might — or might not — consider important for an amenity. Like, most shops around here don't have websites or phones, which are highlighted on POI tiles, and that doesn't mean I would go out of my way to collect them.

(And also _some_ schools do have opening hours, mostly private or limited).
