### ISSUE TITLE
Copying/pasting raw tags

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#241]
Use cases:
1) Transferring tags from one POI to another
2) Replication of specific tags on several poi (tags of trees, surveillance cameras, etc.)

<details>
<summary>Example of the interface in Vespucci: </summary>

![2022-06-05 19 28 03](https://user-images.githubusercontent.com/25708359/172060594-252c66a5-1ddc-4f2f-91d4-cac0ad967534.jpg)

</details>

**Comment by Zverik** [comment]
Sorry, but I have to refuse. This is an expert-level option that would just take screen estate without any usefulness for virtually all mappers. One of the frequent use cases would be solved with #213.
