### ISSUE TITLE
Exclude garages from addresses

### ISSUE THREAD

**Issue by cincodenada** [Zverik/every_door#242]
This is similar to #206 (which I also support) but is a distinct request: the wiki page for `noaddress=yes` also says that `building=garage` and similar can be implicitly assumed to not need an address, so I think the app should exclude garage and probably a few others from having question marks on them.

**Comment by habi** [comment]
In Switzerland, `building=garage` can and do have address tags.

**Comment by Zverik** [comment]
Yeah, same in Estonia.

**Comment by tordans** [comment]
As an inspiration: I really think it is time we start a shared repo (like ELI, id-tagging-schema, …) that collects information about address formats and stuff like "which tags have addresses per country". There are a few projects like https://github.com/yuiseki/osm-address-editor-vite/issues/2#issuecomment-1066125324 for example that could collaborate on this.

**Comment by cincodenada** [comment]
I think garages should still be able to have addresses added to them, but I go around looking for question marks to fill in, so I wish there was a distinction between "this building is missing an address" and "this building doesn't have an address".

Looking at the app again, currently I don't think there is a way to indicate "this building doesn't have an address" - all buildings I see either have an address or a question mark.

So there may actually be two parts to this issue: first, how to indicate buildings without addresses (which already exist unambiguously in the data with `noaddress` or `nohousenumber). A few options that come to mind for buildings without addresses:
 - Using the same small circle as for an entrance (might be confused with entrances)
 - Use a different symbol (a smaller circle?)
 - Using some other symbol in the bubble ("X" is pretty universal I think, "N/A" might be more English-centric?)
 - Using an empty rectangular bubble (might look like a bug or unintentional)
 - Use no bubble, but still allow tapping on an un-bubbled building to edit its info

Once that is resolved, or if it is already resolved and I am just not seeing it, then the second question is, should we default some types of buildings (e.g. garages) to not having an address rather than the "missing address" display, I think.

**Comment by cincodenada** [comment]
I did a (global) analysis of what building types were least likely to have addresses, to try to get a sense of what might make sense to default to not-expected:
![housenumbers](https://user-images.githubusercontent.com/479715/174233610-ed0089fd-2cf0-4871-baf9-9af032e7970f.png)

**Comment by tordans** [comment]
> I did a (global) analysis of what building types were least likely to have addresses

Just for completeness/awareness: that will not cover those places that map the address as a free floating node above a building. Or as part of the entrance-Node. Most of Berlin is mapped that way, for example. My hunch is, that having addresses on the building object is something for villages (and similar areas) but in cities it's more "nodes" since it's harder to split the geometries properly.

**Comment by cincodenada** [comment]
> > I did a (global) analysis of what building types were least likely to have addresses
> 
> Just for completeness/awareness: that will not cover those places that map the address as a free floating node above a building. Or as part of the entrance-Node. Most of Berlin is mapped that way, for example. My hunch is, that having addresses on the building object is something for villages (and similar areas) but in cities it's more "nodes" since it's harder to split the geometries properly.

That's a good point, and actually illustrates another question-mark problem - for buildings that are mapped with floating addresses, EveryDoor presents a question mark on the building, even though the address information exists (and, indeed, is rendered on the basemap!)

In my area, floating addresses seem to be common on building with multiple addresses (such as a row of apartments or offices), but buildings with one address tend to have the address on the building way, but I don't know how common that is globally.

It seems like there's not strong agreement about how to manage multiple addresses on a building - ([Addresses](https://wiki.openstreetmap.org/wiki/Addresses) on the wiki seems to lean towards not double-entering addresses on nodes and buildings, but acknowledges there is some disagreement and links to [a help topic](https://help.openstreetmap.org/questions/48735/address-information-in-poi-and-building) that presents a couple opposing views.

I seem to have opened a can of worms here 😅 Getting back to the basic question - to me, a question mark indicates "missing data", and right now it's often showing on places where there is no missing data (buildings with "floating" addresses as points within-but-not-on the way, buildings without addresses, buildings that probably don't need addresses). But I'm not sure if the question mark was intended to indicate "missing data" in the first place!

**Comment by cincodenada** [comment]
> As an inspiration: I really think it is time we start a shared repo (like ELI, id-tagging-schema, …) that collects information about address formats and stuff like "which tags have addresses per country". There are a few projects like [yuiseki/osm-address-editor-vite#2 (comment)](https://github.com/yuiseki/osm-address-editor-vite/issues/2#issuecomment-1066125324) for example that could collaborate on this.

Also, second this -  I really like the idea of gathering this kind of common data in a shared place - EveryDoor is certainly not the only app that needs to answer these kinds of questions! It reminds me of Mozilla's [browser compatibility data](https://github.com/mdn/browser-compat-data), which has come to serve as the base of all kinds of useful tools.

**Comment by Zverik** [comment]
Done in 0.5. I guess for a list of common tags, there needs to be another ticket, or a public discussion.
