### ISSUE TITLE
Адрес у точки подсвечен как незаполненный, но точка при этом находится внутри знания

### ISSUE THREAD

**Issue by vitalyzhakov** [Zverik/every_door#243]
Добрый день!

Точка внутри здания с адресом.
При этом у точки приложение также хочет адрес.

Корректное ли это поведение?

Версия приложения 0.4.0, Android 9.

**Comment by Zverik** [comment]
Да, это так и задумывалось. У редактора есть мнение, что независимо от геометрического положения точки, все данные, связанные с организацией, должны быть на самой точке. Заполнение этих данных будет чуть проще после #209.
