### ISSUE TITLE
Unable to add decimal point in Height tag

### ISSUE THREAD

**Issue by reueld** [Zverik/every_door#252]
![Screenshot_20220612-190218](https://user-images.githubusercontent.com/19855764/173236118-d8c6fc14-5133-450c-bf21-89acc4c2f27f.jpg)

While entering the height value, there is no option for a decimal point. This might be the case for all numeric inputs. If I find any other example, I will add to this thread.

**Comment by Zverik** [comment]
Please open Settings, and there "Fix numeric keyboard". I'll think of how to make these options more accessible.
