### ISSUE TITLE
[Bug] Zoom buttons in micromapping disappear when no points in view

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#254]
When you are in a new area with no points downloaded, or there are simply no points near enough, the box with the legend leaves the screen as expected, but the zoom buttons are also gone. If I'm going to add a new point, I like to zoom in close first to make sure I'm over the right area. I know pinch zoom works, but it's just a weird quirk.

**Comment by Zverik** [comment]
Done in 0.5.
