### ISSUE TITLE
`internet_access:fee=no` label is cut off, leading to misunderstanding

### ISSUE THREAD

**Issue by habi** [Zverik/every_door#256]
I was micromapping around [this node](https://www.openstreetmap.org/node/6628867002/) today.
The `internet_access:fee` field is cut off, showing "Internet Access: No" in the GUI. 

![image](https://user-images.githubusercontent.com/1651235/173687723-b405d889-8f7e-4a41-afaa-00fc95d8eb4e.jpeg)

Updating the tag shows "Free"/`no` under "Internet Access ..." making it even harder to understand what's going on.

![image](https://user-images.githubusercontent.com/1651235/173688036-b5bf2262-8a61-4b1d-a473-e1b0811f9333.jpeg)

This might only be an issue with the smaller screen on an iPhone 12 mini which I'm using.

**Comment by Zverik** [comment]
Alas it's not cut off: that is the exact label people see in e.g. iD editor. [Source is here](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/internet_access/fee.json#L4).

I recommend using the wifi field at the top part of fields: it allows setting both `internet_access` and `internet_access:fee` with a single tap.

**Comment by habi** [comment]
Go Map!! pulls in the values and shows 'Free' instead on 'no', as you can see in the screenshots below.
Would it be possible to also show the verbose options instead of the value in Every Door?

![image](https://user-images.githubusercontent.com/1651235/173909585-054122b6-cd54-4ae5-a048-cec156db06b7.jpeg)

![image](https://user-images.githubusercontent.com/1651235/173909601-6483d340-ad1d-493c-a4a4-94e2e18a0bb7.jpeg)
