### ISSUE TITLE
[Feature request] Switching satellite images by long tap the map button

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#258]
Options:
1. Long press opens the satellite sub settings
2. After a long press, a pop-up window with a list of images opens. 

![-210750_temp](https://user-images.githubusercontent.com/25708359/173898697-1e566f98-e0b3-4cc1-8131-36fd915e76a6.jpg)

**Comment by Zverik** [comment]
Hmmmm no, too complex, and saves just one tap.

**Comment by deevroman** [comment]
> one tap
more :)

Settings->Satellite images->Click->To main

**Comment by Zverik** [comment]
Thing is, changing satellite imagery is a rare action. Because it's just a reference for things you see with your own eyes. If you find yourself juggling imageries, you're doing something wrong, and maybe JOSM would suit you better.

Also, popup menus with icons and long lists are a bad UI pattern.

**Comment by deevroman** [comment]
> you find yourself juggling imageries, you're doing something wrong

~~Yes, I don't live in Estonia))~~

Not all cities have one good satellite layer(

**Comment by Zverik** [comment]
Yes but the point is, good fresh satellite layers are important when you're tracing from imagery. But for surveying, you just need a point of reference, and for that anything would do.
