### ISSUE TITLE
Add building:material to the building panel

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#277]
Not sure: this leads to building color, roof material etc. [Wiki](https://wiki.openstreetmap.org/wiki/Key:building:material), [Taginfo](https://taginfo.openstreetmap.org/keys/building%3Amaterial#values).

**Comment by ygra** [comment]
Materials are a lot easier to add than colours, though. Especially for colours that are just hexadecimal codes. As someone who actually adds those details, I'd be content with just having materials on the go. Colours require a colour picker from photos and some sort of judgement to hit something that's close to correct, anyway.

**Comment by Zverik** [comment]
Done in 0.8.
