### ISSUE TITLE
Hide payment and charge when fee=no

### ISSUE THREAD

**Issue by kmpoppe** [Zverik/every_door#279]
In micromapping mode, wouldn't it make sense to hide the `payment:*` and `charge` fields when `fee` is explicitly set to `no` (i.e. `amenity=bicycle_parking`)?

**Comment by Zverik** [comment]
I think it might — but also for some things it might make sense to keep these fields. For example when the basic service is provided for free, but there are some extras you need to pay for. In case of a bicycle parking, there might be free simple stands, but when you don't have your own lock, you might pay for one on the spot.

I'd prefer not to second-guess a user, so managing such exceptions is more trouble than not.
