### ISSUE TITLE
Support for `addr:housename`

### ISSUE THREAD

**Issue by GeorgeHoneywood** [Zverik/every_door#280]
[`addr:housename`](https://wiki.openstreetmap.org/wiki/Key:addr:housename) in the wiki.

In the UK a significant amount of (usually old) houses have just a name, no number. Some others have both names and numbers. It'd be great if I didn't have to swap to StreetComplete to enter these easily.

To avoid cluttering the address editor with a whole new field, maybe it could be clever and reuse the existing  "House" field — using some logic like: if amount of alphabetic characters is greater than numeric characters, use `addr:housename`, otherwise use `addr:housenumber`. This would work for cases like "3a", though I'm sure there are adresses where this would get it wrong.

Maybe doing this kind of magic is a bit confusing and opaque to the user.

Thanks again for the app!

**Comment by Zverik** [comment]
Done in 0.7.

**Comment by endim8** [comment]
How do you add a housename? 
I'm guessing it's this field, but its only possible to add numbers
![Screenshot_20220806-120501_Every Door](https://user-images.githubusercontent.com/26939824/183246298-e2ec77b1-dc2f-4525-8e3c-2da0760f1e68.png)

**Comment by GeorgeHoneywood** [comment]
Go to settings and enable "Extended Numeric Keyboard". That should allow you to input letters and numbers in the address form. Once you've entered a few characters a checkbox will appear asking if it is a name.

I think this might be changed in the next release, but this is how it works in 0.9.0.

**Comment by Zverik** [comment]
Also I recommend installing Microsoft SwiftKey keyboard: it is much easier to type with it, and switch modes if needed.
