### ISSUE TITLE
Redesign the opening hours editor

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#284]
The current editor is hard to use and it requires too many taps without clear targets. For example, odd hours are not displayed on the clock.

We need an alternative. For starters, let's display 8 hour options with two buttons: for opening the common clock, and for `24/7`.

Common hours for start I guess are `7:00`, `8:00`, `9:00`, `10:00`, `11:00`, `12:00`. Plus two part-hour options from around, by default `8:30` and `9:30`.

Common hours for end would be `17:00`, `18:00`, `19:00`, `20:00`, `21:00`, `22:00`. Plus again two part-hour options, by default `17:30` and `18:30`.

For a break, we can assume it spans an hour, so we present four full-length options: `12:00-13:00`, `13:00-14:00`, plus two most common options from around. By default `12:00-14:00` and 12:30-13:30`.

**Comment by TheAdventurer64** [comment]
Related to this, would it be possible to add the functionality to add AM and PM support for opening hours?

**Comment by Zverik** [comment]
Added #287 for that. Don't know yet what's the best way to implement.

**Comment by Zverik** [comment]
Some stats:

```
Starts:
  09:00 485030
  08:00 377854
  10:00 331414
  07:00 145708
  11:00 98572
  08:30 74437
  06:00 59782
  09:30 45078
  12:00 43613
  07:30 38011

Ends:
  18:00 299706
  20:00 217485
  22:00 181677
  21:00 176189
  19:00 170155
  17:00 164076
  23:00 88225
  16:00 76708
  14:00 46571
  13:00 45615

Breaks:
  13:00-14:00 17443
  12:00-14:00 16264
  12:00-13:00 8121
  12:30-14:00 5878
  12:00-13:30 3989
  12:00-15:00 3971
  12:30-13:30 3137
  13:00-15:00 2890
  12:30-14:30 2148
  12:30-15:30 2093
```

**Comment by Zverik** [comment]
Done in 0.7.
