### ISSUE TITLE
Add support for farmland

### ISSUE THREAD

**Issue by TheAdventurer64** [Zverik/every_door#286]
Currently, there is no way to edit farmland details. Certain farms have social media info, websites, and phone numbers. Could this be added?

**Comment by Zverik** [comment]
Do you mean landuse=farmland? Or what tag you have in mind?

**Comment by TheAdventurer64** [comment]
> Do you mean landuse=farmland? Or what tag you have in mind?

Yes

**Comment by gdabski** [comment]
Putting these details on landuse features seems questionable to me. Can you give an example of such a feature? I assume the farmyard with any buildings there are is a separate feature. So farmland isn't the same as farm, which spatially includes farmland, farmyard and potentially other features which may have distinct landuse.

**Comment by TheAdventurer64** [comment]
> Putting these details on landuse features seems questionable to me. Can you give an example of such a feature? I assume the farmyard with any buildings there are is a separate feature. So farmland isn't the same as farm, which spatially includes farmland, farmyard and potentially other features which may have distinct landuse.

My bad. The reason I asked for this POI to be supported is because iD allows additional info (email, phone, etc) for the Farmyard preset. I figured I could use the preset for a farm I was mapping without doing any research on the tag, thus creating an issue.

**Comment by Zverik** [comment]
This editor deals with points of interest. These are usually tagged under `shop`, `amenity`, `craft`, and some other keys. The key `landuse` is absolutely not for points of interest, regardless of what additional info some of these landuse features have. For keeping info on farmlands, I'd suggest using another tag. For example, [shop=farm](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dfarm).
