### ISSUE TITLE
Possible duplicate warning makes typing names impossible

### ISSUE THREAD

**Issue by gdabski** [Zverik/every_door#288]
The detection seems to be triggered after every key press when typing attributes such as POI name or operator. The focus is then taken away from the input field and the warning is shown. As a result I can write only a single letter before losing focus. Even worse, when I want to type in a space, it is trimmed-out from the name after focus is lost and I have to resort to tricks (e.g. first type another letter and then input the space in between letters).

**Comment by Zverik** [comment]
Thanks, this is indeed a bug, which I also encountered couple days ago. There's a delay between typing the last letter and the duplicates warning, but that's one second, which might be quite low. I'll fix this in a week or so.

**Comment by gdabski** [comment]
Thank you. I suck at using smartphones, so I'm not surprised I'm not typing fast enough ;)

**Comment by Zverik** [comment]
Done in 0.7.
