### ISSUE TITLE
Add support for amenity=parking

### ISSUE THREAD

**Issue by TheAdventurer64** [Zverik/every_door#289]
Currently, there is no support for `amenity=parking`. Could this be added?

**Comment by gdabski** [comment]
I would like to ask about reconsidering this. I agree parking is better added as areas, but I often find myself wanting to change attributes of an existing parking, especially `parking=*`, `access=*` and `fee=*`, and I can't without switching to another editor. Also, you still can an `amenity=parking_entrance` using EveryDoor, which is a bit of an inconsistency.

**Comment by gdabski** [comment]
@Zverik , would you mind giving your thought on this? I wanted to create a new issue on this only to discover I had already requested it once here...

**Comment by gdabski** [comment]
Oh brilliant, I rediscovered it again after another year 😁

**Comment by Zverik** [comment]
Now you can write a plugin and have it your way :)
