### ISSUE TITLE
Remove entrance-related presets

### ISSUE THREAD

**Issue by imagoiq** [Zverik/every_door#291]
Hi,

I've noted that every door interface give me `building=entrance` tag value combination which is supposed to be deprecated (according to the wiki https://wiki.openstreetmap.org/wiki/Tag:building%3Dentrance). 

There is `entrance=main` in the autocomplete field, but not `entrance` key with the value yes. I guess it's kind of paradoxal to not use the proper tag for entrance for an app called every door 😛😛 (joke, but I seriously think your app has a good potential)

Also it would be nice for those two tags to have some input to add `addr=*` in combination with the entrance.

**Comment by Zverik** [comment]
You are supposed to add entrances via the dedicated entrances mode, not via the [+] button. Removed these presets from 0.7.
