### ISSUE TITLE
Suggestion: possibility to delete changes ready for upload.

### ISSUE THREAD

**Issue by mpawelski** [Zverik/every_door#292]
Hi, thanks for making this app. It looks like a great (and better) alternative to my current use of OsmGo.

However, I was playing with the app and made some dumb changes (just to test what is possible in the app) and there seems to not be any way to "clear" the changes that you are going to upload.

In OSMGo at least you have big red button that allows that.

EveryDoor also seems to have a view with a list of changes. I suggest to add possibility to clear this changes list on this view like in OsmGo:

![Screenshot_20220703-212815](https://user-images.githubusercontent.com/2056282/177055288-b007f40a-c160-4b88-8ee1-7e0c51a2692f.jpg)

Because right now, when you made some stupid changes you don't have and easy option to start fresh with no changes.

**Comment by Zverik** [comment]
Hi Mariusz, thanks for using the app! Just swipe the change left in the changes list :)

**Comment by mpawelski** [comment]
Damn, thanks @Zverik 
I was actually going to suggest that deleting particular change would be useful too...😅

Anyway I think it's worth to consider improving UX discoverability of this feature. Just as "thrash" icon on the right to quickly tap do delete would made it clear that there is even option to do it. 

Plus, IMO, a button to delete all changes would be nice addition anyway.

**Comment by Zverik** [comment]
Following this issue, I did not add a deletion button (the space is already taken by a change type), but added a hint about swiping to the screen (in 0.7).
