### ISSUE TITLE
Write a simpler OSM history viewer

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#293]
See #263 for discussion and prior work.

**Comment by GeorgeHoneywood** [comment]
Hey! I've had a go at this. Code is a bit of a mess at the moment so I haven't opened a PR yet.

Any suggestions for the UI? I'm not sure about also rendering geometry changes -- it would be quite complex and I think it would need a network request for each version.

<img src="https://user-images.githubusercontent.com/25514836/180011437-d23487ad-0b6f-4e36-96cc-23e864280e63.jpg" width="300">

**Comment by Zverik** [comment]
I think you can cap the number of versions at ~30 :)
