### ISSUE TITLE
Карта перестает загружаться при приближении.

### ISSUE THREAD

**Issue by pravets** [Zverik/every_door#3]
После определенного зума вместо карты отображается серое поле, карта не загружается. Как osm тайлы, так и спутниковые снимки.

Если на этом зуме просто нет тайлов, то хотелось бы просто интерполировать картинку, чтобы хоть что-то отображалось.

**Comment by Zverik** [comment]
Починил в версии 0.1.1 для осмерских тайлов, а для спутника в общем виде никак: у них разное поведение на слишком близких масштабах.
