### ISSUE TITLE
Multiple words search does not work

### ISSUE THREAD

**Issue by TheAdventurer64** [Zverik/every_door#301]
Currently, to search for tags, you must type in the exact value of the tag. For example, you will not get any results if you search Gas Station. You must search for `fuel` in order for the Gas Station preset to show up.

**Comment by Zverik** [comment]
Alas I cannot reproduce this :( Which language do you have your app in?

![gas-station-every-door](https://user-images.githubusercontent.com/766031/177934841-4aab04b8-04ba-4c88-a02b-7781f1d207ec.jpg)

**Comment by Zverik** [comment]
Ah, I get it. Indeed, when you type "gas station", it returns no results. Instead it should returns all presets with both terms in the index.

**Comment by Zverik** [comment]
Done in 0.7.
