### ISSUE TITLE
Add the ability to view footpaths and corridors as overlay

### ISSUE THREAD

**Issue by TheAdventurer64** [Zverik/every_door#304]
Similar to StreetComplete, you should be able to view footpaths and corridors as an overlay. The issue is that when mapping malls, it can be difficult to properly align POIs without using the footpaths as a guide, which can result in POIs being misaligned.

**Comment by Zverik** [comment]
Alas ED doesn't have linear features in any form. But that's what the OSM background layer is for.

**Comment by TheAdventurer64** [comment]
> Alas ED doesn't have linear features in any form. But that's what the OSM background layer is for.

The problem is that the OSM background layer doesn't render  indoor corridors, which are used in indoor mapping.

**Comment by Zverik** [comment]
Well, https://github.com/gravitystorm/openstreetmap-carto/issues :)
