### ISSUE TITLE
Add brand presets for micro mapping

### ISSUE THREAD

**Issue by TheAdventurer64** [Zverik/every_door#306]
When it comes to bus stops in OSM, certain ones have brand presets. The problem with this is that when adding bus stops with Micromapping Mode, you cannot implement brand presets. Instead, you have to go into POI mode, search up the brand preset on there, and add the bus stop on the map.

**Comment by Zverik** [comment]
So I guess by brand presets you mean the name suggestions index. Are there bus stops in there?

**Comment by Zverik** [comment]
Actually, after #247 this would be useful indeed. Done in 0.7.
