### ISSUE TITLE
Add postcode field to the building pane

### ISSUE THREAD

**Issue by TheAdventurer64** [Zverik/every_door#310]
In the US, many addresses include the state and the postal code an address is located in. The issue is, you cannot add this from the regular address bar. You have to manually enter it from the tag editor. Having the ability to add additional address info would be great for not only the US, but other countries as well. Could this be added?

**Comment by Zverik** [comment]
Done in 0.7.

**Comment by Zverik** [comment]
Make it a radio field with two nearest postcodes.

**Comment by Zverik** [comment]
Now done.
