### ISSUE TITLE
Line direction hints when editing lines

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#312]
To mark the direction of a road sign, you need to know the direction of the line it belongs to. But now this is not possible
![Screenshot_20220711-133445](https://user-images.githubusercontent.com/25708359/178249026-57c850b0-6ab0-4005-9ecf-16f11c0bf427.jpg)

**Comment by Zverik** [comment]
Alas, Every Door does not and will not know anything about linear geometries.

**Comment by deevroman** [comment]
Wouldn't it be necessary then to remove the ability to edit this tag from the card?
