### ISSUE TITLE
Do not ask for address tags on houses in the Netherlands

### ISSUE THREAD

**Issue by 501Ghost** [Zverik/every_door#325]
The Netherlands works with a very actively maintained import of address nodes, and local mapping guidelines dictate that POIs are mapped on these nodes rather than buildings. Address tags on buildings are in most cases worthless duplications, so suggestions to add them are generally not helpful here. Could this functionality be removed only in the Netherlands? (StreetComplete is already doing this: the question "what is the address of this building" is never shown in the Netherlands)

P.s. I have very little experience with Github, so my apologies if I've overlooked something.

**Comment by Zverik** [comment]
Hi 501Ghost, thanks for using the editor :)

In Edvery Door, buildings and address nodes are treated virtually the same: it's just a switch on the building pane, "address" option removes any building tags. So, would removal of "?" symbol on un-addresses buildings do?

**Comment by 501Ghost** [comment]
That would be helpful to prevent addresses from being added to buildings, but we would miss out on the option to tag building levels and roof shapes. Is there a way to only remove the option to add addresses?

**Comment by Zverik** [comment]
Done in 0.8.
