### ISSUE TITLE
Remove addr:postcode from the building panel

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#326]
It breaks "on the ground" rule.

**Comment by 501Ghost** [comment]
But the postcode is part of the address. Postmen are very happy with postcode data.

**Comment by Zverik** [comment]
It is! But one of the founding principles of the editor is that it is only for visual surveying, and postcodes are rarely displayed on buildings.

**Comment by TheAdventurer64** [comment]
> It is! But one of the founding principles of the editor is that it is only for visual surveying, and postcodes are rarely displayed on buildings.

Restaurant permits in my area have postal codes.

**Comment by Zverik** [comment]
Done in 0.8.
