### ISSUE TITLE
Mixed separators in phone numbers

### ISSUE THREAD

**Issue by mxxcon** [Zverik/every_door#328]
EveryDoor, including v0.7 seem to be formatting phone numbers in an inconsistent way.
According to https://wiki.openstreetmap.org/wiki/Key:phone#Usage numbers should be separated either by `-` OR ` `(space), but not mixed.

> `phone=+<country code> <area code> <local number>`, following the [ITU-T E.123](https://en.wikipedia.org/wiki/E.123) and the [DIN 5008](https://en.wikipedia.org/wiki/de:DIN_5008) pattern
> `phone=+<country code>-<area code>-<local number>`, following the [RFC 3966](https://www.ietf.org/rfc/rfc3966.txt)/[NANP](https://en.wikipedia.org/wiki/NANP) pattern

It would be nice if EveryDoor followed this convention too.

**Comment by Zverik** [comment]
Could you give some examples of how ED formats vs how it should be formatted please?

**Comment by mxxcon** [comment]
> Could you give some examples of how ED formats vs how it should be formatted please?

For example node 9132786077 from changeset 123623255.
It was added as `phone=+1 718-397-0533`
Instead of either `phone=+1-718-397-0533` or `phone=+1 718 397 0533`

**Comment by Zverik** [comment]
I do not see the requirement you write of anywhere on that page. The formatter uses a commonly adopted library that follows Google rules — as does the native caller app for Android:

![called-us-number](https://user-images.githubusercontent.com/766031/179157452-ab1c56a6-e7fc-4b05-841d-65556cf0dd83.jpg)

Here, there are two parts: country code and local number. As per national US standards, the local part is separated with `-`.

As I see in taginfo, of 350k phone numbers with a dash inside, half also has a space.

Finally, I just like when there are different separators for different layers of meaning: it's easy to see which part should be used when calling from abroad, and which is sufficient for a local call.
