### ISSUE TITLE
App doesn't understand `only` for `diet:vegan` and `diet:vegetarian`

### ISSUE THREAD

**Issue by schuetzm** [Zverik/every_door#334]
If `diet:vegan` or `diet:vegetarian` are set to `only`, the corresponding buttons are not selected. This is bad, because if a user then clicks on them to activate them, the tag is replaced by `yes`, losing the existing information. Example: https://www.openstreetmap.org/node/7920795000

There may be a similar problem with `takeaway` (and maybe `delivery`), although I couldn't test this yet. `only` is already supported here, but they can also take a time specification in `opening_hours` format.

In general, any boolean tag could be affected. I'd suggest to either allow editing an additional free-form value for those tags, or as a quick solution to simply disable the buttons if it contains unsupported values.

**Comment by Zverik** [comment]
I have fixed the field to treat all non-`no` values as positive, just like the iD editor does. Not ideal, but there's a raw tags editor if needed.

**Comment by jolesh** [comment]
Maybe make a small table with the diet forms on the left and the values selectable, like this:
**Diets:**
| vegetarian | no | yes | only |
| vegan | no | yes | only |
| halal | no | yes | only |
...

Maybe accessible through a menu, just like opening hours open a dialog.
