### ISSUE TITLE
[Feature Suggestion] Pipeline markers in micromapping mode

### ISSUE THREAD

**Issue by schuetzm** [Zverik/every_door#336]
It would be nice to support pipeline markers in micromapping mode: https://wiki.openstreetmap.org/wiki/Key:marker
Currently they aren't even displayed.

IMO they would be useful because the energy infrastructure (in particular gas and oil) is currently very incomplete in OSM.

Edit: There's also the deprecated [pipeline=marker](https://wiki.openstreetmap.org/wiki/Tag%3Apipeline%3Dmarker), which is however still in widespread use.

**Comment by Zverik** [comment]
Done in 0.9.
