### ISSUE TITLE
Some ATM are not parsed/recognized

### ISSUE THREAD

**Issue by vlotorev** [Zverik/every_door#337]
If i open https://www.openstreetmap.org/#map=19/55.98269/37.17540 in Every Door v0.7, then application doesn't allow to edit Sberbank ATM that is present on the map.

**Comment by Zverik** [comment]
Yes, that relates to #247. I did not like the result, so I plan to revert it in 0.9.

**Comment by Zverik** [comment]
Done in 0.9.
