### ISSUE TITLE
Make a server for drawings and map notes

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#342]
A simple stuff:

* [x] PostgreSQL backend with two tables (points and lines)
* [x] PHP / Python API for uploading in batch and downloading by bbox
* [x] Tile rendering
* [x] Web interface for browing tiles
* [x] Add the tiles to editor-layer-index and JOSM imagery list

**Comment by tordans** [comment]
Interesting. What use cases do you have in mind for this?

**Comment by Zverik** [comment]
Server is up, https://github.com/Zverik/geoscribble. WMS works, tested with iD and JOSM. Only the last item, adding it to layer indices, remains.
