### ISSUE TITLE
Update the privacy statement

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#344]
Google has issues with the current one. I guess I should use the template from StreetComplete:

* https://play.google.com/store/apps/datasafety?id=de.westnordost.streetcomplete
* https://www.westnordost.de/streetcomplete/privacy.html

**Comment by mnalis** [comment]
Note that google might have issues with other things too (like mentioning donations etc.), see for example: 
- https://github.com/streetcomplete/StreetComplete/issues/3768
- https://github.com/streetcomplete/StreetComplete/issues/3748
- https://github.com/streetcomplete/StreetComplete/issues/2909

**Comment by Zverik** [comment]
Done. I hope it works.
