### ISSUE TITLE
Improve Notes display - allow opening links (pictures)

### ISSUE THREAD

**Issue by mnalis** [Zverik/every_door#349]
In new `OSM Notes` mode in ED 0.9, one can click on the note and see its text. 
That text sometimes contains URLs (e.g. see https://www.openstreetmap.org/note/2487699)

Currently the problems are:
- URLs are not clickable
- the form does not allow to select/copy the text from it, so user can't even manually copy/paste them in the external browser
- the form does not even show Note ID so user could manually construct URL (and/or reference that note number elsewhere). 

It would be great if it could be improved (i.e. make URLs clickable, show note ID, allow copy/paste), so users could use linked information (web pages / pictures). Note however that sometimes however URLs are shortened by missing `http:`, so it would take same heuristics to detect them also, e.g. https://www.openstreetmap.org/note/3295544)

**Alternatively** (and more easy and robust with less duplication of effort), just providing a button so user can open a note in external browser would solve all those problems (e.g. if a user clicks button `show in web browser`, ED would open https://www.openstreetmap.org/note/2487699 and **all** of the above issues are solved automatically, including URL-detecting-heuristics, nicer timeline display, user page linking, etc.). 
OsmAnd does that for example (_in addition_ do doing their own URL display!)

**Comment by Zverik** [comment]
Can you come up with a use case, when you have to open an url in the field? Given that ED's focus is on surveying, not map maintenance ([principle 2](https://github.com/Zverik/every_door/blob/main/README.md#principles)).

**Comment by mnalis** [comment]
I understand that the focus of ED is surveying. But I am somewhat confused about what is exactly meant by "maintenance"? If one looks at the OSM note, and then do some action based on what they've read, is that not some kind of "map maintenance" too? Even without notes, is not verifying and updating/deleting data on the ground "maintenance"?

But if you mean "not maintenance tool" in a sense that ED is **not** _"general purpose editor"_, but mobile editor specialized for on-the-ground survey, I agree. But so are for example StreetComplete or editing portion of OsmAnd too - yet both allow URLs in Notes to be accessed.

If Notes are useful for on-site surveyors, then surely disallowing users to access **_full content_** (i.e. including visiting mentioned URLs) of the Notes is counterproductive, no?

Here are few recent examples of Notes I've looked up that:
- have been explicitly marked as needing on-site survey (via `#surveyme` "hashtag")
- contain URL as a part of the note description

As, such they seem to me to represent a use case to ED. If that is what you asked for? :

https://www.openstreetmap.org/note/3204109
https://www.openstreetmap.org/note/3192123
https://www.openstreetmap.org/note/3179672
https://www.openstreetmap.org/note/3164229
https://www.openstreetmap.org/note/3126935
https://www.openstreetmap.org/note/3114210
https://www.openstreetmap.org/note/3113972
https://www.openstreetmap.org/note/3089723

Sure, maybe some of them could be solved even with partial information (i.e. without URL), maybe a little (or a lot) harder. Yet, it helps if mapper can see full content of the note, not just the plain ASCII part.

**Comment by mxxcon** [comment]
Some new users mistakenly create notes with poi info thinking they are adding that to the map.
Also data that comes from https://www.onosm.org/ is poi details as text in notes.

Ability to select text in notes in EveryDoor is extremely useful. 👍

**Comment by Zverik** [comment]
Done in 0.10.
