### ISSUE TITLE
Presets are missing some values [0.9]

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#350]
Today I noticed that some presets don't populate values for some options. For instance, `amenity=bench` and `amenity=waste_basket` both show an empty value button and the `...` menu (also empty) for Material. `natural=tree` has no values for Denotation. `manhole` has no Type values. And so on.

I tried purging and redownloading to no effect.

**Comment by Zverik** [comment]
This is weird and I cannot replicate this. Which version are you using — iOS, from GitHub, or from the Play Store?

**Comment by pkoby** [comment]
GitHub, but I tried fresh installing and it works again. Not sure what went wrong, but maybe something in the upgrade process did something weird.
