### ISSUE TITLE
Level selectors disappear when you select an address in POI mode

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#351]
When I am editing a POI, the editor shows three options for an address, and sometimes (presumably in areas with multiple levels), shows some values for what level the POI is on.
![2022-08-03 16 19 34](https://user-images.githubusercontent.com/7786285/182703896-552aa43e-c9e7-414d-9448-646e612d4e99.png)
However, when I select an address (e.g. 3201 Saint Paul), the buttons for levels (`/-1`, `/0`, `1/`) go away. It's not clear to me if this is intended. What I would like is the options to stay, because as I usually select the address first (as it's above the levels), I don't like having to type the value every time.

**Comment by Zverik** [comment]
It is intended: whyn you choose an address, it shows only floors for that address. And since floor navigation can vary from building to building (and from country to country), I cannot pre-populate floors.

**Comment by pkoby** [comment]
Okay, good to know it's intentional. However, I'm not sure I understand how it actually works.

Does it pull values from other POIs with the same address to populate the new POI? Adding a point inside a building with known levels doesn't populate values, so I assume you don't download building information.

That said, would it be possible perhaps to swap the address and the levels in the editor? Or perhaps having some common default values if there are no values known? I would think `/0` at least would be nice to have (most shops around here are on the ground floor).

**Comment by Zverik** [comment]
Yes, it pull values from other POIs around. And it filters based on addresses set directly on POI.

Alas, I cannot do default values, since they are different for every country, and even inside countries sometime. And the address is more important than a floor, hence it's above. Sorry.
