### ISSUE TITLE
Highlight POIs with a color that have a fixme tag

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#354]
It is also possible to highlight POIs that have not been checked for a long time (https://github.com/Zverik/every_door/issues/275)

**Comment by Zverik** [comment]
This is unlikely, because `fixme` as I see it are notes for desktop editors, e.g. to check the website, find a proper tag, and such. Like, all `amenity=fixme` have the tag set.

**Comment by deevroman** [comment]
> I see it are notes for desktop editors

A few examples. 

We will find all amenity=* with fixme in St. Petersburg.
<img width="1213" alt="Снимок экрана 2022-08-08 в 12 31 38" src="https://user-images.githubusercontent.com/25708359/183387204-d18f8d01-c371-4928-8348-81538756203b.png">

Top among fixme tags (But here you need to be careful with the conclusions, because there is not only amenity)
<img width="654" alt="Снимок экрана 2022-08-08 в 14 50 07" src="https://user-images.githubusercontent.com/25708359/183411799-853dfcc0-e381-4063-892b-d42ded346348.png">

You can also study similar queries

<img width="1220" alt="Снимок экрана 2022-08-08 в 16 06 50" src="https://user-images.githubusercontent.com/25708359/183425074-26bd578f-86f2-4d5f-b3ca-8233fae59be1.png">

**Comment by Zverik** [comment]
Okay, good point, thanks :)

**Comment by Zverik** [comment]
Aaaand also this might be used for generic tags like `shop=yes` (#65) and `amenity=yes`. And obviously fixme types should be highlighted to not make them feel normal.

**Comment by Zverik** [comment]
Also POI older than say 5 years should be highlighted as well, as suggested in #275. The idea currently is to add the ⚠️ symbol to a POI tile, and a yellow panel similar to a duplicate one to the editor.

**Comment by Zverik** [comment]
Done in 2.0.

**Comment by grahamjpark** [comment]
@Zverik Old thread, but what's the logic for if a business is old? Context: to help me find where I should survey in cities I'd like to try to find areas where many nodes fail this check. I tried to find where it's implemented in the code without luck.
