### ISSUE TITLE
Redesign five buttons on the entrance page

### ISSUE THREAD

**Issue by strump** [Zverik/every_door#356]
**Steps to reproduce:**
1. Select Ukrainian language
2. Switch to entrances mode
3. Pick entrance

**Actual result:** "OK" button is almost out of the screen
<img src="https://user-images.githubusercontent.com/720808/183441138-d7a49a96-dde8-4c0b-adf2-c71dd6fe5188.png" width="300px"/>

**Expected results:** All buttons should fit screen width.

**Comment by Zverik** [comment]
Thanks, it really is time to untangle that row of buttons.

**Comment by Zverik** [comment]
Okay, did this in 2.0 the easiest way: just two rows of buttons.
