### ISSUE TITLE
Rename Note action "close" to "resolve"

### ISSUE THREAD

**Issue by mnalis** [Zverik/every_door#362]
Recently implemented OSM Notes window offers buttons named `CLOSE`, `CANCEL`, `OK`. 

The issue is that `CLOSE` is confusing - In EveryDoor case it means "Close note", but user can easily mistake it to mean "Close window" (i.e. what `Cancel` button does), especially as it is shown first. Luckily, pressing it shows warning dialog (that saved me several times already), but it might be good idea to rename that `CLOSE` button to `RESOLVE` (like e.g. www.openstreetmap.org does) to remove ambiguity/confusion.

**Comment by Zverik** [comment]
Thanks, make sense. Did that on Weblate.
