### ISSUE TITLE
Copy paste of tags

### ISSUE THREAD

**Issue by sanketgarade** [Zverik/every_door#364]
Many times I am tagging adjacent buildings with the same tags such as number of levels, roof shape etc. 

At such a time it would be great if I could just tag one building properly and then simply copy paste its all tags onto other buildings. This would you save a lot of mechanical work and time. 

The "Go Map" app on iOS has this feature which I use very often.

**Comment by deevroman** [comment]
Pay attention to the issue https://github.com/Zverik/every_door/issues/241

**Comment by Zverik** [comment]
This editor is for surveying on the ground, not mass-editing already mapped objects. If I were to implement automatic copying of tags, this would lead to errors, since buildings have too many fields. I decided that 3-4 extra taps are worth it, and negligible compared to walking distances between buildings.

**Comment by sanketgarade** [comment]
> This editor is for surveying on the ground, not mass-editing already mapped objects. 

Even for on ground survey, this feature is useful. I will share a couple of experiences I had due to which I requested this feature. 

There are housing societies in my area which consist of multiple buildings having the same number of floors and same roof shape etc. I came across 12 such buildings where I thought it would be easier to tag one building properly and simply copy paste its tags to the other 11 buildings. Now I need to open every building and set each tag individually. 

Similarly there is a locality where there are about 40 individual bungalows each having a flat shape roof and two floors. I can't imagine having to individually open up each building and add these two tags every time.

And of course in some cases there can be more than two tags that needs to be copy pasted over multiple buildings. 

Using Go Map app such kind of operation can be done in just two clicks. You select the building and click on paste button on the GUI.

> If I were to implement automatic copying of tags, this would lead to errors, since buildings have too many fields.

Not sure what you mean by *automatic copying of tags* but I often copy paste tags when I use the Go Map! app on iOS. It's super easy and also gives you a pop up , asking to merge or replace the tags, if it finds and conflicts. In case you haven't tried it yet you can have a look at it to understand what I'm saying.

As a regular user of the app I am just providing my user experience feedback. Final decision is yours 😊
