### ISSUE TITLE
Filtering button when not focused on current position does nothing

### ISSUE THREAD

**Issue by starsep** [Zverik/every_door#366]
1. Click current position button
2. Flitering button works correctly
3. Pan the map
4. Filtering button does nothing

This bug was added in c5a74ab762b3ef39c97014b509c65b66165296c1

Low quality GIF:
![untitled](https://user-images.githubusercontent.com/2798728/184192687-f53eeeb8-a377-4840-8eca-8be2bf467385.gif)

**Comment by Zverik** [comment]
Fixed in 1.0, thanks for finding.
