### ISSUE TITLE
Change icon for raw tags view

### ISSUE THREAD

**Issue by waldyrious** [Zverik/every_door#369]
The icon to view the raw tags in the feature details screen was not immediately clear to me. As someone with some technical background, I can recognize that <kbd>&lt;&gt;</kbd> is sometimes used to represent "code" or XML, but I think a "table" icon would be more intuitive for the key-value structure that the tags represent.

Something like these, for example: [![](https://upload.wikimedia.org/wikipedia/commons/9/9f/OOjs_UI_icon_table-progressive.svg)](https://commons.wikimedia.org/wiki/File:OOjs_UI_icon_table-progressive.svg) [![](https://upload.wikimedia.org/wikipedia/commons/4/43/GeoGebra_icon_table.gif)](https://commons.wikimedia.org/wiki/File:GeoGebra_icon_table.gif)

**Comment by Zverik** [comment]
This new icon was requested by multiple people, and I feel there can be no good option. But I guess I'll revert it to the [one I used before](https://wiki.openstreetmap.org/wiki/File:Every_Door_0.3.0_Android_-_Main_Screen_Library.png), or maybe [this one](https://fonts.google.com/icons?selected=Material%20Icons%3Aview_list%3A).

**Comment by mnalis** [comment]
The latter (View List) looks good, the former (previous one: globe/ball) was even more confusing than the current one

**Comment by Zverik** [comment]
Done in 2.0.
