### ISSUE TITLE
Empty floor filter returns empty list

### ISSUE THREAD

**Issue by starsep** [Zverik/every_door#372]
I tried using "By floor" filter with `empty` value in the mall.
I am getting empty list of POIs even though there are POIs without `level` OSM tag.
Version tested: 1.0

**Comment by Zverik** [comment]
Could you please post a link to that mall? I'll check it out, but in case I don't find anything, I'd like an example place.

**Comment by starsep** [comment]
I already have added levels in one I tested previously.
Another mall where I confirmed the same behaviour: https://osm.org/way/30611687#map=19/52.23005/21.00258

**Comment by Zverik** [comment]
Done in 2.0.
