### ISSUE TITLE
App doesn't know auth is obsolete

### ISSUE THREAD

**Issue by rmikke** [Zverik/every_door#373]
I cannot upload data for two days when tapping the upload icon"Sending changes" appears for a moment, then the upload icon is still yellow and no data is uploaded. No POIs, no buildings data, no notes.

My wild guess is that I have been using Every Door and JOSM at the same time and it is possible that there was an object version conflict.

Force stopping and restarting Every Door does not help.
Haven't tried cleaning app memory, because I don't want to loose the data I want to upload.

Version 0.9.0 from Google Play.

**Comment by Zverik** [comment]
First, wait for the 1.0 version: it's reviewing right now, and it has some fixes regarding uploading.

Also open the changes list in Settings, and check the errors.

**Comment by rmikke** [comment]
I can only see the list of 31 changes waiting for upload and when I tap any of them, the change data opens. Can't see any error report.

**Comment by Zverik** [comment]
In case nothing helps (but do wait for 1.0, it might), you have an option of downloading your changes in an `osmChange` format, to upload using JOSM, for example. After that you can clear the changes list in the editor.

**Comment by rmikke** [comment]
I've already exported the file, but I'll wait for 1.0 just for sake of experiment :)

**Comment by rmikke** [comment]
Just to let you know, the upgrade did not help

**Comment by Zverik** [comment]
In the changes list, there is a "Pending" subtitle for every change not uploaded. For those that were, and failed, there will be an error message. Do check for these please.

Also open the system log (in the "about every door" item on the settings pane) and check for errors there.

**Comment by rmikke** [comment]
I'm not sure where I should see these errors. I have this list of pending uploads:
![Screenshot_20220816-113333](https://user-images.githubusercontent.com/4492676/184848413-3669f352-12ad-4464-a866-c6043bc0aa8f.png)
and wherever I tap on it, I get the change info like this:
![Screenshot_20220816-113357](https://user-images.githubusercontent.com/4492676/184849689-a63d39ac-48c8-4740-bbfa-f64e63bf7f81.png)
I can't see any error messages.

System log seems to be empty, but I tried sending it anyway.

**Comment by Zverik** [comment]
The system log is cleared when the app is restarted, so it makes sense to check it only after you've tried uploading the data.

**Comment by rmikke** [comment]
Rrrright, so the system log directly after trying to send the changes said I'm not logged in. The app was saying that I am logged in and logging off and on again helped.

So the issue comes down to app showing that I am logged in, while I was not.

**Comment by mnalis** [comment]
@rmikke Perhaps it is possible you logged in at some time, and then later revoked EveryDoor access at https://www.openstreetmap.org/oauth2/authorized_applications ? (just a wild guess)

**Comment by Zverik** [comment]
Thanks Ryszard, this replicates the same issue found by another user. I'll implement login checking in the next version, so such kind of error does not occur.

**Comment by rmikke** [comment]
@mnalis I'm sure that was not the case. Authorization may expire. I'm not even sure OSM's OAuth allows permanent authorization.

**Comment by Zverik** [comment]
Done in 2.0.
