### ISSUE TITLE
Make the delay from the last check_date higher

### ISSUE THREAD

**Issue by bfontaine** [Zverik/every_door#378]
Hello,
I use the "filter by check_date" feature (#12) in dense areas when I don’t have much time and just want to confirm things. However the delay between re-confirmation seems low: I checked a bunch of shops and restaurants in an area a couple weeks ago, and now they’re back as "un-checked".
I think it would make more sense to increase the delay to at least a couple months.

Related: #275, #354.

**Comment by mnalis** [comment]
Or perhaps make it configurable?

**Comment by Zverik** [comment]
Yes, I ran a poll in the Russian group, and the consensus is indeed around 2 months. I'm hesitant because you won't be able to confirm any shops less than two months old, except by changing some tags.

**Comment by Zverik** [comment]
Done in 2.0, set to 61 days.
