### ISSUE TITLE
barrier=kerb : more tags needed

### ISSUE THREAD

**Issue by JLZIMMERMANN** [Zverik/every_door#379]
HOW TO REPRODUCE : when selecting a kerb in the the first pictogram for detailled mapping we may complete some tags and some like :
- tactile_paving=yes/no
- wheelchair=yes / no / limited

WHAT I EXPECT : 
I'm a french OpenStreetMap big contributor about disabled people, and an improvement is welcome
- tactile_paving=yes / no / **contrasted**
-  wheelchair= yes / no / **bad** ["limited" is relevant for a restaurant because, we can maybe enter, and not go to the toilet]
Pictures : "contrasted" means if the surface is black the tactile_paving is white and vice-versa.
![image](https://user-images.githubusercontent.com/4929752/184721441-4e3fbeee-bbc8-44d4-87f2-204dff14bf5c.png)

IDEA : 
Add another tag really used in France
- crossing:bollard=yes/no/contrasted
![image](https://user-images.githubusercontent.com/4929752/184721601-fdfb012d-ea74-4564-99dd-781c25269796.png)

**Comment by Zverik** [comment]
Wheelchair=bad is a bad tag, because explaining how `bad` differs from `no` or `limited` would take a full page. And the value is used in like 0.05% of tags.

Other questions about tagging should go as pull requests to https://github.com/openstreetmap/id-tagging-schema

**Comment by JLZIMMERMANN** [comment]
In accessibility limited is for a building.
bad means concerning a kerb that the answer is almost reached.
