### ISSUE TITLE
Changes apparently discarded on "Pending uploads"

### ISSUE THREAD

**Issue by siiky** [Zverik/every_door#381]
When I open a feature from the "Pending uploads" list, make changes to it, open the history, and return from the history it looks like the changes were discarded. If I get back to the "Configuration" screen and then into the "Pending uploads" again, the changes are there.

Luckily the changes aren't really discarded, but it does look that way, which is very confusing.

Recording by @GeorgeHoneywood:

https://user-images.githubusercontent.com/25514836/185397078-98252ae9-d786-4142-99ad-7f4530f706a2.mp4

**Comment by GeorgeHoneywood** [comment]
I don't know if this is strictly related, but I think the pending uploads screen needs to be refreshed when you return to it.

For example if you edit an element in your pending changes, manually returning it to its original state, then save it. This takes you back to the pending uploads screen, where the now non-existent change still is.

https://user-images.githubusercontent.com/25514836/185394945-a056f936-a522-404e-8026-337ac8daf821.mp4

**Comment by GeorgeHoneywood** [comment]
More on topic; here is the original issue replicated. It seems the history page is unrelated.

https://user-images.githubusercontent.com/25514836/185397078-98252ae9-d786-4142-99ad-7f4530f706a2.mp4

**Comment by siiky** [comment]
Thanks for the recording! (I don't think I can record on my phone...) This second video is exactly it, but the first may still be related. I'll add it to the report if you don't mind.

**Comment by Zverik** [comment]
Done in 2.0.
