### ISSUE TITLE
Better offline support

### ISSUE THREAD

**Issue by siiky** [Zverik/every_door#382]
I mainly walk outside with no internet connection at all. I usually "plan" where I'm going, download everything I can before leaving, and then I don't (in general) need any more internet.

However, it happens often that I try to zoom in/out more than I had while connected to the internet, and in these cases the screen turns blank for lack of the needed map tiles (except for the downloaded features rendered by ED).

My first idea of an MVP for better offline usability would be to add an "offline mode" setting such that, when enabled, ED downloads all the map tiles for all zoom levels in the range of the downloaded data (when asked to download data with the small downward arrow on the bottom left of the screen or the red button).

**Comment by Zverik** [comment]
There is a separate button to download tiles: look in Settings, "Background imagery", there's a button.

I've hidden it because it strains the servers, and I prefer for the editor not to be banned.

**Comment by siiky** [comment]
Cool, thanks! Can you explain in some detail how it works? I tried it but it didn't seem to help. I downloaded an area I hadn't downloaded before, hit that button you mentioned (and waited for it to finish). I turned cut off the internet connection but still the tiles for some zoom levels were missing...

**Comment by Zverik** [comment]
It does not download tiles for ALL zooms because it would be too much. It gets ~1000 tiles for an area at the moment up to zoom 18. For 19, it would be ~3000 more. That is both increased load on a server, and increased storage requirements for a phone. With the OSM default layer, it might get the editor banned. So no, that's what we have to work with.

**Comment by siiky** [comment]
Understood, thanks!
