### ISSUE TITLE
Entrace move after snap

### ISSUE THREAD

**Issue by GeorgeHoneywood** [Zverik/every_door#384]
After an entrance has been snapped to a way, it can be moved, changing the shape of the way. This example is a bit contrived, but in all other cases Every Door stops you from moving nodes that make up a way, so I figure it makes sense to catch this too.

For example if you create some entrance, upload it, and it snaps to a nearby way. The entrance then shows in its new snapped position as part of the way. This node should now have the move button disabled, but it does not. Re-downloading the data will cause the button to be disabled.

See this replicated on the dev server [here](https://master.apis.dev.openstreetmap.org/way/4305938943/history). I was able to move the [entrance node](https://master.apis.dev.openstreetmap.org/node/4332337895/history), after it had snapped to the way.

**Comment by Zverik** [comment]
I did not fix the exact problem at its source (too hard and I don't want to dig into data models), but I made entrance nodes unmovable after uploading in 2.0.
