### ISSUE TITLE
Listen on "geo:" intents

### ISSUE THREAD

**Issue by mnalis** [Zverik/every_door#387]
on Android, in various mapping apps (like for example StreetComplete or OsmAnd), one can click on "share" button to share [geo:](https://en.wikipedia.org/wiki/Geo_URI_scheme) coordinates, which opens up Android menu allowing the user to choose application which will open at said coordinates.

Various mapping apps (like [StreetComplete](https://wiki.openstreetmap.org/wiki/StreetComplete), [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci), [OsmAnd](https://wiki.openstreetmap.org/wiki/OsmAnd), [Organic Maps](https://wiki.openstreetmap.org/wiki/Organic_Maps), [Trekarta](https://wiki.openstreetmap.org/wiki/Trekarta) etc.) respond to such `geo:` intent. Every Door (at least 1.0) does not (i.e. it is not present in android "share" menu). 

Would it be possible to add that functionality? It would be very useful invoke ED from other apps (I currently invoke Vespucci from other apps for editing, but would prefer to invoke ED instead for simpler cases as it's easier, faster, and less error-prone than Vespucci for quick POI tasks)

**Comment by Zverik** [comment]
Done in 5.3.
