### ISSUE TITLE
Allow addr:street updates without addr:housenumber or addr:housename

### ISSUE THREAD

**Issue by donalhunt** [Zverik/every_door#388]
In some countries, it's possible to determine the street address but not the house number/name from the street.

Observed:
Right now the everydoor app requires both to be filled out.

Desired:
Should be able to add an addr:street tag without also entering number/name of building. Since this could result in less data being collected, making it a user selectable option may make sense.

**Comment by donalhunt** [comment]
Current situation:

![Screenshot_20220824-184702.png](https://user-images.githubusercontent.com/5854402/186599474-f3b76d1f-5668-4be8-b02d-aab24912192c.png)

**Comment by Zverik** [comment]
Sorry, but while I could see some value in housenumbers/names without streets, I don't see any in having `addr:street` without a housenumber/name. These could just be set automatically, without having to go into the field. The point was to have an address, and a street name does not constitute one. For exceptions (which are very rare), you can use the raw tags panel.

**Comment by bfontaine** [comment]
To circumvent this I put a fake house number, then I go in the raw tags panel and remove it. It’s faster than adding `addr:street` via the raw tags panel because there you don’t have autocomplete on the street name.
