### ISSUE TITLE
Need a Z21 for micromapping

### ISSUE THREAD

**Issue by JLZIMMERMANN** [Zverik/every_door#389]
When trying to add tags to kerbs and street objects are really thin it's quite impossible to be sure that I'm adding anything to the good POI. 
![IMG_20220826_092328.jpg](https://user-images.githubusercontent.com/4929752/186847015-93df3763-7dee-4919-a02e-b6848d014d73.jpg)

**Comment by Zverik** [comment]
Zoom 21 is now available in 3.0.
