### ISSUE TITLE
Missing icon for bicycle shop

### ISSUE THREAD

**Issue by coooly** [Zverik/every_door#390]
![image](https://user-images.githubusercontent.com/8920118/187020918-66d65ba3-940f-4775-bf89-bc12b19d0c42.jpeg)

**Comment by Zverik** [comment]
There are too many missing emoji, and the idea was to not add every single tag myself. You can either make a pull request [to this file](https://github.com/Zverik/every_door/blob/main/lib/helpers/tag_emoji.dart), or wait for #38.

**Comment by coooly** [comment]
Sure. Happy to help.

**Comment by Zverik** [comment]
Hi Ivan, just click on the "pen" icon for that file, and you can edit it from github. And then it will create a pull request for you.
