### ISSUE TITLE
Feature: duplicate POI

### ISSUE THREAD

**Issue by coooly** [Zverik/every_door#391]
Hello,

Really useful in "Go Map!!" that would be great to be able to duplicate an existing POI and just move it to current location. 

- Find a poi that you need to duplicate
- Tap a duplicate button
- Show the map to your current location (I'm assuming that user may want to add something close to him)
- offer to modify attributes (if some need to be ajusted)
- Save to OSM

**Comment by deevroman** [comment]
But why ? In micromapping mode, the selected tags are remembered for objects, and in POI mode, the last used presets are prompted.

**Comment by coooly** [comment]
Let say I want a duplicate an object that i didn't created before with an operator, url and maybe other attributes that are bit tedious to type again on mobile.

Could be it be worth it ?

**Comment by Zverik** [comment]
I thought about this, especially few days ago while mapping an airport terminal, and encountering many similar shops. But I am still against: duplicating an object with many attributes might lead to errors from lack of attention, e.g. slightly different opening hours won't be noticed. The editor was optimized for faster input of shops and amenities, and this makes adding a few duplicates not too much frustrating.

Also I would need a very, very good practical reason that applies to most editor users to add another button.

**Comment by deevroman** [comment]
And what if you place this function by long pressing on the POI in the list? Yes, this is a bad and not obvious pattern, but this way it will not clutter up the place.
