### ISSUE TITLE
Type not translatet in List

### ISSUE THREAD

**Issue by thomasramm** [Zverik/every_door#400]
The type of a POI is in english in the list. If i open a POI then the type is shown translated in my language. Please translate it also in the List, if you can't assign an Icon for the type.
Example: in the List it shows me townhall, if i click on the Listitem then in the Form the Title is Rathaus (the German translation of townhall)

**Comment by Zverik** [comment]
That's not type, that's the main tag value. E.g. "florist" for `shop=florist`, or "townhall" for `amenity=townhall`. Translations and human-readable values are too long, so I decided not to use those. I assume users have some knowledge of OSM to read that.
