### ISSUE TITLE
Say what "amenities" are in the FAQs

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#407]
![Screenshot_20220901-174238.jpg](https://user-images.githubusercontent.com/1230959/188018734-d35671c4-1018-4483-86bf-bc255d06374a.jpg)
Here the user has no idea what you mean by "amenities". We see there's several points of data on the map within a hundred meters. So that must not be what you mean. So make sure you say what you mean in the FAQ.

**Comment by jidanni** [comment]
(Okay, in coffee cup mode, I mean amenities mode, attempt to add a point. This will reveal a list of basic amenities, so we do indeed have an idea what this says, before any documentation is written.)

**Comment by Zverik** [comment]
It already says it in the FAQ, in the last item.
