### ISSUE TITLE
Make sure the FAQ is and all other documentation is also on the website

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#408]
It's good to make sure the website for this app, https://every-door.app/ , has all the documentation also on it, so we don't need to start up the app to go find it in case we're at home.

**Comment by jidanni** [comment]
And that way, we wouldn't need to go all the way into the help menu and then come all the way back just to try a feature. We could look at the help on one screen (browser) and then try it in the app on another, or even split screen.

**Comment by Zverik** [comment]
The editor is intended to be used offline, since many countries don't have easily available internet. So everything goes into the app. The website is just a landing page for app store links.

Also I ran into a problem when much fewer people translate the website than the app, so I decided to consolidate everything that needs translating in a single place.

**Comment by jidanni** [comment]
(Just have the docs also in a PDF or better: one big page HTML, that one could download and read offline too... ) (Also allows one to learn the app without a cellphone!)

**Comment by mnalis** [comment]
It might be possible to automatically generate online HTML from app help screens ?

**Comment by Zverik** [comment]
What for?

**Comment by jidanni** [comment]
Well, it's just like if we want to read up on a television before we buy one. We shouldn't have to buy one to be able to read up about it.

**Comment by jidanni** [comment]
Or like, television manuals are available from the manufacturer's website, without requiring a purchase. That way we can even compare the details before getting involved with hardware purchases.

**Comment by jidanni** [comment]
Or, our phone might have been squashed by a Mack truck. And it'll take a week before they send a new one to our remote Northern laboratory. Before that happens we would like to learn up on all kinds of different apps in our spare time using our desktop. (Without needing  installing sdks, just purely reading the documentation.)

**Comment by jidanni** [comment]
Or the boss would like us to prepare and review comparisons of several different apps, before selecting what hardware to purchase, and we can only do so via comparing the written documentation.

**Comment by jidanni** [comment]
Or we simply would like to read the documentation, at the same time using the app without having to leave the app to go into the documentation because they're all inside the same app only. That way we could just simply use different windows on our Android screen. Just like one can do with Vespucci.

**Comment by mnalis** [comment]
> What for?

I (for one) find reading the docs/FAQ on bigger screens much more endurable, _especially_ if it is more than few lines of text, and prefer it whenever possible.

**Comment by mnalis** [comment]
Also, web searchers are much more useful for users when they find actual directly-useable-by-user HTML FAQ page (then if they index the github source XML or JSON or whatever which would happen without it, if at all)
