### ISSUE TITLE
Buttons not documented

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#410]
![Screenshot_20220901-180208.jpg](https://user-images.githubusercontent.com/1230959/188020769-377cf95c-cdc6-4e5b-b3cd-4435923ee733.jpg)
As there's no documentation anywhere of what the buttons do, we try some. We try the button with the tree on it. The word swimming pool appears. Okay there is a swimming pool on the picture so it must be related somehow. Then we tried the download button and it says download 3000 points but we don't really know where all those 3000 points are so maybe we downloaded more than we thought it would etc. so all these buttons need to be documented including the coffee cup which  apparently does nothing; it's all big mystery Thank you very much.

**Comment by jidanni** [comment]
Okay, it turns out a long press on each one gives its name. But still you need to write a description somewhere in some document about the idea of each one. Yes, e.g., in the video you mentioned micro mapping mode but still you need to formally write about it and some document.

**Comment by jidanni** [comment]
Okay, it turns out  the buttons are mentioned (hidden) inside the FAQ about adding building entrances.

**Comment by Zverik** [comment]
So each button in the app has a tooltip which you can see by long-pressing it. The documentation is planned, although not in the nearest months (see also #40).
