### ISSUE TITLE
Make sure holding big blue buttons act the same

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#411]
![Screenshot_20220901-181246.jpg](https://user-images.githubusercontent.com/1230959/188021980-31637495-9cca-44fa-ac60-bcb8923886b5.jpg)
Here we see two big blue buttons on the bottom. Holding the left one for a while shows what it's supposed to do in a balloon. But holding the right one for a while does something completely different, something unexpected..

**Comment by jidanni** [comment]
No we will not know what it does. All we know is we need to push cancel to get back where we were.

**Comment by jidanni** [comment]
Okay poking around with it, it must be a picture of a door, and this is the famous "every door" door for mapping entrances and exits!
Too bad the user has to kind of figure all this out for himself because there's no documentation.

**Comment by Zverik** [comment]
These buttons are exactly the same :) You might have moved your finger when holding the right one.

But you convinced me to plan the built-in documentation: #428. It is indeed not obvious what these buttons do.
