### ISSUE TITLE
"Does not exist" not very clear

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#412]
![Screenshot_20220901-182025.jpg](https://user-images.githubusercontent.com/1230959/188023006-685f1334-063d-41e0-811c-cf5c554c14e9.jpg)
Here we see in red the words "does not exist". But it's not very clear what it is trying to communicate.

**Comment by jidanni** [comment]
Okay maybe it means to delete the whole record of this entrance.

**Comment by Zverik** [comment]
Well it's a button when you press with the POI does not exist. I have plans for making a tutorial (see also #40), and there'll be a new video and maybe a documentation in the future, but the button will stay as it is.

**Comment by jidanni** [comment]
Actually it seems down at the bottom of the image there could just be another button next to "save", called "delete".

**Comment by jidanni** [comment]
Oh, I see, in amenities mode it pairs with "mark defunct".
