### ISSUE TITLE
Add a way to turn off GPS

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#415]
Add a way to turn off GPS, without the user needing to turn it off for his whole cell phone. For instance we might be happy with what we're looking at we don't need the GPS on all the time using battery.

**Comment by Zverik** [comment]
Uhm, sorry, but I have to reject this. The editor is specifically made to map around you, so GPS is essential. Every setting should have a clear benefit for most of the users, and this won't be it.

**Comment by jidanni** [comment]
Okay, if GPS is supposed to be on all day, why is  the magnetic screen orientation rotation off all day? (Okay it hasn't been implemented yet 😀
