### ISSUE TITLE
Do not allow exporting 0 map changes

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#417]
Looking at the intent generated by sharing an appending change we see the odd wording "0 changes":

`intent:#Intent;action=android.intent.action.SEND;type=application/xml;launchFlags=0x1b080000;S.android.intent.extra.SUBJECT=0%20changes%20from%20Every%20Door%20on%202022-09-01%2020%3A10;end`

**Comment by Zverik** [comment]
Could you please trace your steps? Just tested it, and got a correct number of changes.

**Comment by jidanni** [comment]
Here I press the Share button:
![Screenshot_20220902-192052.jpg](https://user-images.githubusercontent.com/1230959/188245741-324aa607-cf3d-4fd8-bfd8-76401e8e7624.jpg)![Screenshot_20220902-192116_Android System.jpg](https://user-images.githubusercontent.com/1230959/188245748-f1f16065-4601-4a6f-81e5-654e76f8e542.jpg)![Screenshot_20220902-192130_Intent Intercept.jpg](https://user-images.githubusercontent.com/1230959/188245751-8d99d44a-4c9d-45ba-856d-d015aca52da0.jpg)

**Comment by Zverik** [comment]
Ah, it's an OSM note, which does not go into osmChange exports. I'll disable sharing when that's the case.

**Comment by Zverik** [comment]
Done in 2.0.
