### ISSUE TITLE
Update change total after swiping left

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#418]
![Screenshot_20220901-201928.jpg](https://user-images.githubusercontent.com/1230959/188033515-89be7eee-aeff-4ca9-ac27-4a699297b5eb.jpg) here we have swept left and got rid of a change but at the top of the screen still says 1 change.

**Comment by GeorgeHoneywood** [comment]
This has also already been fixed, and will be released in the [2.0 version](https://github.com/Zverik/every_door/blob/main/CHANGELOG.md).

**Comment by Zverik** [comment]
Uhuh, thanks George. It is.
