### ISSUE TITLE
Reference codes sometimes also can have letters in them

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#419]
![Screenshot_20220901-202656.jpg](https://user-images.githubusercontent.com/1230959/188034154-3913607b-f80e-4932-9aba-93861079cfcc.jpg)
Here it is assumed that reference codes, only consists of numbers and dashes. But that's hardly the case; there's letters and gosh even Chinese characters that could be in a reference code.

**Comment by jidanni** [comment]
PS, this is super high priority, because tomorrow I'm going off to tag a lot of electric poles, with letters in their reference codes.

**Comment by jidanni** [comment]
Okay, in the FAQ there is indeed some words about the extended numeric keyboard, that indeed work. However that choice should be the default otherwise it'll take about a day for each user to figure out how to fix it back. Instead of have an experts learn how to disable the normal keyboard..

**Comment by Zverik** [comment]
I made the extended keyboard the default in 2.0.
