### ISSUE TITLE
Add custom URL imagery choices 

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#423]
Sooner or later somebody's going to (be in a hurry and) want to use a different imagery than the ones offered, so there should be at least one custom URL1, custom URL2 etc. templates.

**Comment by deevroman** [comment]
And this applies not only to satellite images, but also to the main map. For example, so that it is possible to add maps with z20 https://osm.cquest.org/dev/#20/44.13530/4.81051

**Comment by joshinils** [comment]
And if implemented, please allow multiple sources at the same time, maybe with custom opacity.

For example, if I were to add a tree layer of my city, this would have opacity and be useful for adding trees, but seeing the DOP (or OSM) would be necessary as well to see which tree I am looking at.

**Comment by tordans** [comment]
For reference: I think it is time to start a collaboration with editors to store presets and custom image overlays in our osm.org user profile. I wrote up an example in https://github.com/bryceco/GoMap/issues/599#issuecomment-1139283802.
Apart from Every Door, also MapComplete, GoMap, iD and other editors would benefit from a shared but personal preset and image store.

**Comment by Zverik** [comment]
Will be a part of #119. Imagery available in the editor is sufficient for regular mapping, and all these changes could go into custom profiles, when they are implemented.
