### ISSUE TITLE
2 weeks hardwired

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#425]
One  can imagine that for e.g., oil wells one might want four weeks instead of two, so there should be some way to adjust these kind of things.

**Comment by GeorgeHoneywood** [comment]
In the next release, the limit will be just under 2 months instead of 2 weeks. 
I think 2 months hardcoded is a good compromise, as that isn't enough time for much to significantly change — and saves adding some extra configuration.

**Comment by Zverik** [comment]
Yes, I want to keep config options to a minimum, and the threshold will be increased in the next version.
