### ISSUE TITLE
Weird tag: pinfarmers

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#426]
![Screenshot_20220901-214250.jpg](https://user-images.githubusercontent.com/1230959/188041078-002ba05c-3b0e-4b59-81f1-d98e1c5c6e86.jpg)

**Comment by Zverik** [comment]
Well, the list [comes from taginfo](https://taginfo.openstreetmap.org/keys/line_attachment#values). I have thought for a minute about filtering it, but then it opens a new line of work for filtering everything in taginfo, and I don't want that.
