### ISSUE TITLE
White area should shrink to fit

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#427]
![Screenshot_20220901-215511.jpg](https://user-images.githubusercontent.com/1230959/188042389-57eb3d98-f51e-42cc-b4b1-bbad9cefdbc4.jpg)
Here all that is needed is one line of white area, instead of all that extra wasted white area when there's no text to fill in.

**Comment by Zverik** [comment]
I have issues about white area constantly changing its size while moving the map, so I don't think there can be a consensus. From experience, the map size is good enough even for 4" displays.
