### ISSUE TITLE
App doesn't help you change the main tag easily

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#431]
Let's say you accidentally tag a picnic site but you really meant picnic table. Well the app helps you a lot to pick the first value, but if you want to change it it doesn't help you with the presets anymore at all.

**Comment by Zverik** [comment]
It does — tap on the title panel in the editor.

**Comment by jidanni** [comment]
(Oh, I see. It is because it looks like it is just part of the page's title and can't be changed..)
