### ISSUE TITLE
Cannot zoom to one's heart's content

### ISSUE THREAD

**Issue by jidanni** [Zverik/every_door#433]
Zooming with two fingers works, up to an arbitrary point, then one can't blow up the map any further. It just so happens that I got some real clear air photos and it doesn't make sense to not allow me to keep on zooming in. (OK, I was using Bing.)

**Comment by mnalis** [comment]
- ref. related issue https://github.com/Zverik/every_door/issues/453

**Comment by Zverik** [comment]
I've increased max zoom from 20 to 21 in version 2.1. Should be enough.
