### ISSUE TITLE
Original string typo in translation ("nearby:w with")?

### ISSUE THREAD

**Issue by mnalis** [Zverik/every_door#435]
When translating ED, I've come up on this original string to translate:

> <pre>* `1/0`: `addr:floor=1` + `level=0` (and there's an object nearby:w with the same `addr:floor`, but different `level`, or vice-versa).</pre>

Is seems broken (`nearby:w with` part). Or at least I can't make sense of that part.

**Comment by Zverik** [comment]
Thanks, it is an error. I've fixed it. Also, in the weblate interface, there's a "Suggest" button to suggest an edit.
