### ISSUE TITLE
[iOS] Fixme not displaying correctly

### ISSUE THREAD

**Issue by matheusgomesms** [Zverik/every_door#440]
On last version (2.0), the fixme message does not display the entire text properly, per image below.

![IMG_4368](https://user-images.githubusercontent.com/86851490/189925533-06672b01-99d8-4271-9063-8c00549c6d14.PNG)

**Comment by Zverik** [comment]
It won't display the entire text (there's the fixme field below for that), but I'll cut the text properly, thanks.

**Comment by Zverik** [comment]
Done in 2.1.
