### ISSUE TITLE
[iOS] Error when confirming hashtags

### ISSUE THREAD

**Issue by matheusgomesms** [Zverik/every_door#441]
On last version (2.0), if I activate the new option to confirm the hashtags before uploading changes, when uploading nothing appears to confirm. If I click anywhere, then the changes are sent to OSM, without review. I tried to change phone's orientation, but nothing happened as well.

![video](https://user-images.githubusercontent.com/86851490/189928542-34e2909b-9241-4444-920d-f0a72e907f00.gif)

**Comment by Zverik** [comment]
Fixed in 2.1.
