### ISSUE TITLE
Check whether opening_hours:signed=no should be removed when adding opening hours

### ISSUE THREAD

**Issue by kmpoppe** [Zverik/every_door#442]
With Version 6 [this restaurant node](https://www.openstreetmap.org/node/472309160) got assigned [`opening_hours:signed=no`](https://wiki.openstreetmap.org/wiki/Tag:opening_hours:signed%3Dno) by StreetComplete.

While that tagging was "invented" and brought into use (and is now "de facto" according to the wiki) without being voted on, it's used by StreetComplete both in setting the value and in its "map maintenace" quests.

Yesterday I added the opening hours for the new restaurant that is now occupying the node and wasn't able to remove the "old" information that there are no OH signed.

While I can imagine a scenario where you are a) at the place, b) have no OH signed at street level, but c) find them on a leaflet/flyer that you can pick up there and thus you will be _able_ to add OH without them being signed, I feel that this would be a seldom thing to happen.

Proposed solution: Have a three-state option in ED named "Automatically remove "opening hours not signed"-information when adding opening hours" with "yes", "ask" and "no" options and react accordingly.

**Comment by mnalis** [comment]
> Yesterday I added the opening hours for the new restaurant that is now occupying the node and wasn't able to remove the "old" information that there are no OH signed.

as a workaround, there is "raw tag editor" on upper right end of the screen, where you can add or remove any tag. 

Although, official handling would still be nice. As ED is intended to be used on-the-ground, maybe just assume the user really is entering information on the ground, and remove [opening_hours:signed=no](https://wiki.openstreetmap.org/wiki/Tag:opening_hours:signed%3Dno) automatically if user sets  `opening_hours=*`? 

Especially as documented purpose of `opening_hours:signed=no` according to wiki seems to be primarily to help mappers on the ground automatically skip asking for `opening_hours` on places which do not have it signed (and so asking every user for it over and again would be a waste of their time).

But  once `opening_hours` in inputted (from whatever source), `opening_hours:signed=no` usefulness _drops drastically_ (to say the least).

**Comment by kmpoppe** [comment]
You're probably right. If `opening_hours=*` gets set, get rid of `:signed=no`.

**Comment by Zverik** [comment]
I am against making a setting for this, but if everyone's fine with it, I can make ED automatically remove this weird tag, like you both suggest.

**Comment by Zverik** [comment]
Done in 2.1.
