### ISSUE TITLE
Add roof:downpipe yes/no to the building panel

### ISSUE THREAD

**Issue by SquishyBubble** [Zverik/every_door#445]
This is a feature not very well mapped, currently 18 909 entries in the database according to https://taginfo.openstreetmap.org/keys/roof%3Adownpipe#values. Adding it to the app would be very useful.

**Comment by Zverik** [comment]
Well it's not documented — no wonder it's underused. Apart from that, I'm open only to removing lines from the building panel, not adding. It's long enough as it is. Sorry :) You might make a pull request to a [building preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/building.json) though, so it would appear under the "more..." button.
