### ISSUE TITLE
Street names are not pre-filled from highways

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#447]
Looks like only POI are used for street names, despite having the data.

**Comment by matheusgomesms** [comment]
And even though when you enter the street name manually, you cannot reuse it when adding a second POI. Only after uploading it the street name becomes available.

**Comment by Zverik** [comment]
Fixed the titular bug, but forgot about Matheus' comment. Will do by 2.1.

**Comment by Zverik** [comment]
Done in 2.1.
