### ISSUE TITLE
When choosing from closely spaced points, the maximum scale is not the maximum.

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#448]
https://user-images.githubusercontent.com/25708359/191522624-152ac85a-df21-4fba-9b4d-4e0c0062ce5d.mp4

**Comment by j9d3it** [comment]
See #433

**Comment by deevroman** [comment]
No, it's about something else.
When Every Door specifies which object you clicked on, the maximum zoom decreases. Stop at the first frames of the video, and compare with the following.

**Comment by Zverik** [comment]
Done in 2.1.
