### ISSUE TITLE
Add more colors to the micromapping mode

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#451]
It is worth noting a little equipment of playgrounds, hatches, surveillance cameras, trees, hatches, ... , how to navigate by colors on the map becomes difficult. They change every now and then, and a lot of black dots appear on the map.

<details>
<summary>Example</summary>

![Screenshot_20220928-200145](https://user-images.githubusercontent.com/25708359/192846828-25c76250-a75e-46c1-8240-da01cc320c44.jpg)

</details>

Therefore, it seems worth fixing the colors of the dots.

On the one hand, now you need to think about how to link objects and a limited set of colors. And therefore, perhaps this problem should be considered as part of https://github.com/Zverik/every_door/issues/119. So that users can customize the colors themselves.

It is also possible to try to add other symbols besides dots: squares, crosses, ...

**Comment by Zverik** [comment]
So the colors should be stable when there's a big enough pool of colors to choose from. So I'm hijacking this ticket for adding more colors.

I don't plan on adding other symbolics, since it would become harder to navigate.

**Comment by Zverik** [comment]
Done in 3.0.
