### ISSUE TITLE
Allow greater zoom out

### ISSUE THREAD

**Issue by imagoiq** [Zverik/every_door#453]
Hi,

Here is a feature request to restrict less zoom out. I know that you consider the editor made for immediate surrounding, but after a couple of month to use it, I had a couple of use case.

The main is that I often forget things to map and recall it only when I'm travelling back to my place (for example) with train. ~50km to scroll is quite a pain especially for a tiny addition. 

The other use case happens once or twice. I mapped a place somewhere then talk to someone who gave me further details to add. At that moment, I didn't have a computer in front of me and it would have been easier to add with my phone than writing it somewhere and wait to add it.

**Comment by Zverik** [comment]
Done in 2.1.
