### ISSUE TITLE
addr:block and addr:block_number

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#455]
[In some countries](https://wiki.openstreetmap.org/wiki/Key:addr:*#Detailed_subkeys) it is common to use block names or numbers. The address editor (not on POI) should have these added. E.g. a single input field and a switch.

**Comment by Zaneo** [comment]
Any timeline for this? I map in Japan and this affects me. Every door is incredibly useful, but it really slows down my ability to add them while out on a walk. Otherwise I have to correct the addresses later, which is not desirable.

**Comment by Zverik** [comment]
Done in 3.1 (only `block_number`, idk how `addr:block` is used: no consistent usage over the world).

**Comment by contrapunctus-1** [comment]
The lack of addr:block makes it a problem to use EveryDoor for Indian addresses. It's usually an alphabet, and sometimes two alphabets. The workaround is to add `addr:housenumber=A-10` instead of `addr:housenumber=10` + `addr:block=A`, and fix it in other editors, which is suboptimal.
