### ISSUE TITLE
Include Vending Machines as part of legend and map display

### ISSUE THREAD

**Issue by sanecito** [Zverik/every_door#457]
Every Door Version: 2.0

**Problem:** Every Door doesn't seem to include vending machines as part of the footer legend nor as highlighted features to easily select on the map to edit. They seem to appear on the map as very small, semi-transparent black dots on the map. Having vending machines more easily visible on the map to discern if there is already data for it (or if there's a missing machine to be added) and to easily select to refine it as needed (e.g. ITO EN vs Coca Cola, takes IC Card and/or Cash, type of item) would help improve pedestrian related features

While they are diminishing, the number of vending machines in Japan alone are around 4 million. Every Door highlights less common world wide features like Torii which are found almost exclusively in Japan. Therefore, given Every Door highlights Torii already, it should show vending machines better 

**Solution:** Display Vending machines on the map and in the footer legend much like other objects like defibrillators

**Comment by Zverik** [comment]
Hey Scott, thanks for using the editor! Vending machines along with ATMs can be found on the POI tab (the button with a tea cup at the bottom of the screen). This was made to make surveying shopping malls faster, since you can find a lot of those machines on different floors.
