### ISSUE TITLE
Unable to enter basement levels

### ISSUE THREAD

**Issue by ianthetechie** [Zverik/every_door#458]
See the attached screenshot. It seems impossible to enter negative numbers (at least on iOS) so I can't fully tag underground shops.

![IMG_9155](https://user-images.githubusercontent.com/2140440/193992197-64f722da-8d68-40a6-b1ac-4e64c791eaf9.png)

**Comment by Zverik** [comment]
Thanks for noticing! Fixed in 2.1.
