### ISSUE TITLE
Show notes locations on the map chooser panel

### ISSUE THREAD

**Issue by mnalis** [Zverik/every_door#459]
in `micromapping` and `amenity` modes, current location pointer in the middle of the screen (black inverted raindrop image) is shown at all times, allowing for precise position that is shared between modes.

Alas, in Notes screen current location pointer is shown **only** when adding a new note. That makes one unable to make it point to note exactly, and then switch to another mode to use information from note to update/create amenity. 

e.g. it is hard from the first picture to determine which amenity (second picture) needs to be edited here:

![small_Screenshot_20221006_105659_info zverev ilya every_door](https://user-images.githubusercontent.com/156656/194290390-611bef03-9fa2-44aa-af23-365625d98204.jpg) ![small_Screenshot_20221006_105717_info zverev ilya every_door](https://user-images.githubusercontent.com/156656/194290410-f456d75a-2a90-42f0-8a7c-c1cd9c324f8e.jpg)

The problem is additionally exacerbated by non-persistent zoom issue (https://github.com/Zverik/every_door/issues/230) 

So, could we have a location pointer shown at all times in Notes mode (as it is shown in Amenity/Micromapping modes)?

**Comment by Zverik** [comment]
Showing the location marker in the notes mode does not solve this issue directly. Instead, I'm changing this issue to displaying notes locations on the map chooser screen when adding a new object/amenity.

**Comment by Zverik** [comment]
Done in 3.0.
