### ISSUE TITLE
Support adding vacant shops as amenities

### ISSUE THREAD

**Issue by scvalex** [Zverik/every_door#463]
In my area, there are a lot of empty retail spaces.  I'd like to be able to quickly add these as I walk down the street.

The advantages of adding these empty shops over not adding anything are:
  - It gives positive information to consumers that there's nothing there, and that there isn't just a hole in the data,
  - It gives us a space to add known information like the street address of the retail unit, and
  - It makes it easier for future editors to fill in the details.  This is one of the things I care about because the mall next to me is half empty, and it's annoying to figure out where the shops are supposed to be inside because GPS isn't reliable.  If I could quickly add all the empty spaces, I could easily figure out where everything is based on spatial relations (e.g. the Holland&Barrett is three shops down from the Boots, even if the three shops are empty right now).

I can sort of do this now by adding a shop, and then marking it as defunct, but that takes a lot of clicks and requires me to lie in some fields.

Based on the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dvacant), I think we're supposed to use either `shop=vacant` or `disused:shop=yes` to mark these.

I'd be happy to write a PR for this change, if you agree that it's a good idea.

**Comment by mnalis** [comment]
Agreed. Current workaround of **_adding_** a random shop,  and then **_editing_** it to `Make defunct` is somewhat clunky.

**Comment by Zverik** [comment]
In 2.1, added `shop=vacant` to presets, and reinstated `Mark defunct` button for newly created amenities.

**Comment by scvalex** [comment]
Thank you!
