### ISSUE TITLE
Toilets within POIs

### ISSUE THREAD

**Issue by siiky** [Zverik/every_door#468]
This is a feature request to include questions/fields related to toilets inside POIs, for example in "More Fields".

Reading the wiki page for [`amenity=toilets`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Toilets_within_places), I think the most important questions would be these:

1. `toilets=yes/no`: Are there toilets in this establishment?
2. `toilets:access=yes/customers/no/...`: Who may use them?
3. [`toilets:wheelchair=yes/no/limited`[(https://wiki.openstreetmap.org/wiki/Key:toilets:wheelchair): Are the toilets accessible to wheelchair users? According to the wiki page for this key, answering correctly would require more work/investment than I'm guessing most people is willing to put in for a single tag. After watching some of a SotM 2022 talks, I wonder how much of the `wheelchair` tagged data is correct (and therefore useful).
4. [Sex/gender related tags](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Gender_neutral_toilets): `toilets:{male,female,unisex}` are currently pretty much unused (except for [`toilets:female` with 5 uses total](https://taginfo.openstreetmap.org/keys/toilet:female)), but this info is useful, so maybe a discussion about it could be started.

This is all I have for now.

**Comment by Zverik** [comment]
Hey siiky, thanks for the suggestions! All fields in this editor are managed in the same repo as for the iD editor. Please make a pull request there: https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/toilets.json

Regarding mapping, I'm against making toilets a subtag for other POI. This way it's not searchable with the main OSM apps, like Organic Maps. If there is a toilet inside, just make a separate POI for it.

**Comment by siiky** [comment]
Thanks for the very quick reply!

That is a problem of downstream data consumers, not a tagging problem. I fear adding nodes for every little thing would pollute the data unnecessarily since, e.g. in the case of the toilets, they're a part of an "outside" feature.

And that pollution brings with it another problem for downstream data consumers, that is probably harder to solve -- what to show when?

**Comment by matheusgomesms** [comment]
Look, it seems that Organic Maps can search for toilets inside a POI! Didn't know that!

**Comment by siiky** [comment]
@matheusgomesms Oh very good to know! Next time I won't underestimate OM and assume that it can't do it if OsmAnd doesn't either. :)
