### ISSUE TITLE
Support OSM notes

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#47]
Maybe as a dedicated type with special processing. Might also need to be displayed in the poi list. And there should be a comment support.

All in all, quite hard to implement and not sure if needed.

**Comment by matkoniecz** [comment]
From my experience with StreetComplete: note display is highly useful, allows to clean them and resolve some issues that are not immediately useful

**Comment by risturiz** [comment]
OSM Notes support should be great! A lot of people use notes to add info about POI ( creation and resolution of notes always is a plus ).

**Comment by Zverik** [comment]
Done in 0.9.
