### ISSUE TITLE
Urdu translations can be cleared

### ISSUE THREAD

**Issue by bgo-eiu** [Zverik/every_door#470]
I had been putting translations in the "Undetermined" locale while I was waiting for the Punjabi (Pakistan) locale to become available on Weblate. As of today, it is available, and I have copied over all my translations from Urdu to the correct code.

Sorry if I caused any confusion by not explaining this, I was just excited to get a head start. A lot of Urdu speakers also speak Punjabi so it wasn't a bad idea to put them there. Now that the proper locale is available though, Urdu should be cleared so someone who  knows Urdu can do that translation

**Comment by Zverik** [comment]
Thank you, removed the Urdu language.
