### ISSUE TITLE
Add QR scanner for fast adding websites/FB/insta links

### ISSUE THREAD

**Issue by empty-child** [Zverik/every_door#478]
Zverik, hello

A lot of POIs have styled QR stickers with contact information. Like, links to insta, FB, etc. And if you go around the city, it's very inconvenient to check them manually. I think, it would a great feature for fast processing links. I see some pitfalls: using shorten services, inability to validate domains of known and integrated presets. But, I think, there are more pros in this feature

**Comment by Zverik** [comment]
Good idea — I'll have to research Flutter modules, of which I see only [qr_code_scanner](https://pub.dev/packages/qr_code_scanner). There's a chance I'll have to raise minimal supported Android versions for that, which would be not ideal.

**Comment by Zverik** [comment]
* [native_qr](https://pub.dev/packages/native_qr) requires iOS 16+ (current 12+).
* [qr_code_scanner](https://pub.dev/packages/qr_code_scanner) looks good but alas unmaintained for two years.
* [mobile_scanner](https://pub.dev/packages/mobile_scanner) looks good overall, needs testing.

**Comment by Zverik** [comment]
Done
