### ISSUE TITLE
Option to add survey tag

### ISSUE THREAD

**Issue by crannofonix** [Zverik/every_door#480]
It would be nice if Every Door added a feature where it would automatically apply a "source=survey" tag. What do you think?

**Comment by deevroman** [comment]
EveryDoor already adds `check_date'. Why do I need to add another `source=survey'?

**Comment by Zverik** [comment]
They mean, to changesets. Like StreetComplete does. I'm undecided on that: Every Door implies surveying, just as StreetComplete does. And adding static tags is weird.

**Comment by crannofonix** [comment]
I meant if you were adding non-POIs, it would be nice to have a source=survey tag on them since they don't have check dates and to me, it makes more sense on non-POIs to have survey tags rather than check dates.

**Comment by mnalis** [comment]
I'd be against adding `source=survey`.

---

Firstly, note that [source=*](https://wiki.openstreetmap.org/wiki/Key:source) is nowdays to be used on changeset, and **not** as a tag on nodes/ways/relations (as it was used historically), as wiki notes:

> With modern editors, the source=* tag is typically added to the changeset when a change is made, not as a tag on a piece of information which may be updated at different times based on different sources

However, I also think we should **not** add `source=survey` on changesets either, _at least_ not indiscriminately.
While ED is mostly optimized for on-survey mapping, it may well be used in other cases, especially as it can show aerial imageries (so even if ED were to add `source=survey` by default, that tag should be **_removed and replaced_** with `imagery_used=*` if showing aerial imagery functionality was used in that session, which would complicate the code. See https://github.com/streetcomplete/StreetComplete/issues/56#issuecomment-1268212973 for example)

StreetComplete (that was mentioned) handles that by checking location of the object to current user GPS location, and pops up a warning `Are you sure you checked this on-site? Only information that was found on a survey should be entered.` every time user is too far away from the object they are trying to edit, and aborts unless user confirms that this answer is a result of on-site survey. EveryDoor does not (currently) do that, so one cannot know if it the data comes from the survey or not.

I would rather that ED **_does not add changeset tags that might be completely incorrect_**. If someone want to _guess_ the source, they can easily _guess_ from editor name itself (which is already recorded in [created_by=*](https://wiki.openstreetmap.org/wiki/Key:created_by) changeset tag). And if one cannot reasonably (i.e. excluding deliberate lying / vandalism) reliably trust `source=*` then it becomes useless for everyone.
