### ISSUE TITLE
Submit the app to Huawei AppGallery

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#483]
https://developer.huawei.com/consumer/en/appgallery

Since huawei phones don't come with Google Play stores, this might be worth the trouble. Organic Maps publish there as well.

**Comment by Zverik** [comment]
Okay, the store requires me to upload my id card and a bank card. No way I'm sending that to China. So help wanted: who wants to maintain that store's page?

**Comment by reinhart1010** [comment]
Maybe I could help with that?

**Comment by Zverik** [comment]
Reinhart, I would be grateful. One thing, you need not to disappear in the following years, so that Every Door sees updates :)

**Comment by reinhart1010** [comment]
Sure, I'm also considering automating this  process so updates can be handled easier.

**Comment by Zverik** [comment]
Great, go ahead then. Post what you need from me, we can do it by email if you want: ilya@zverev.info. I'm fine if this will be in your name.
