### ISSUE TITLE
fire hydrant bonnet/cap color

### ISSUE THREAD

**Issue by mahdi1234** [Zverik/every_door#487]
In JOSM it's possible to define three color values, for the main body, bonnet and cap

![hydrant](https://user-images.githubusercontent.com/1097047/198841467-80dec728-767b-4a5a-9f20-fb62c91750fa.png)

it'd be great add remaining two, so I don't need to take picture to process it at home.

see also https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant bonnet:colour=* and cap:colour=*

**Comment by Zverik** [comment]
Thanks for the suggestion! This editor works on iD presets, so please make an issue or a pull request there please: https://github.com/openstreetmap/id-tagging-schema
