### ISSUE TITLE
Snap Entrances to buildings

### ISSUE THREAD

**Issue by crannofonix** [Zverik/every_door#490]
Good morning/afternoon/evening/night everyone

When adding entrances to the map, it would make it easier for everyone if the entrance nodes could snap to the building outline

**Comment by GeorgeHoneywood** [comment]
[This has already implemented](https://github.com/Zverik/every_door/blob/6a08b4958c03c9fa86a4c6f920e0d4d1445c6337/CHANGELOG.md#016), and it also works for some other “snappable” features.

It only occurs when you click the upload button, so unfortunately there isn't any visual feedback as you go.
