### ISSUE TITLE
Donation Options

### ISSUE THREAD

**Issue by mds08011** [Zverik/every_door#492]
Have you considered setting up a way for people to contribute financially to Every Door's development?  I don't know programing but have been trying to pay for software I use frequently.  If there was a method to donate (e.g. Github Sponsors), I would happily commit to donating a few dollars each month.  I apologize if this has already been discussed but I didn't see any related answers.

**Comment by jolesh** [comment]
Or maybe [Liberapay](https://liberapay.com/)? I personally like it a lot for supporting for example [StreetComplete](https://liberapay.com/westnordost/)

**Comment by mnalis** [comment]
Note however that apps accepting donating must hide that information from end user, or risk being banned from Google Play, e.g. https://github.com/streetcomplete/StreetComplete/issues/3768

**Comment by Zverik** [comment]
I keep this open in case I get to work on Every Door full time for a few months and it could help me kick-start independent development. But with donations, I see that effort is usually not worth the money: even widely used libraries like Leaflet get $10k a year (not enough to support a developer), and SC, as I can gather, gets around $500 a month — having 9 times more active contributors using the editor.

What matters right now is institutional and corporate support. I'm currently applying to a NLNet grant and seeking out other options. The editor needs at least four months of full-time development to fully reflect my vision for it, and that's expensive.

**Comment by Zverik** [comment]
I've added a "Sponsor" button to the repo, with github and liberapay options. Hope it helps :)

**Comment by Coehill** [comment]
@Zverik Consider linking your github profile with your LiberaPay profile so it's clear that it's linked to EveryDoor. Even add EveryDoor to the description. That way, it'll be clear that people are supporting the EveryDoor developer.

Keep up the great work. I use your app all the time and it's been invaluable to improving the maps in my community, thus improving quality of life for people bicycling, those with physical disabilities, etc. 😄
