### ISSUE TITLE
Apply all tag values from brand presets

### ISSUE THREAD

**Issue by gdabski** [Zverik/every_door#493]
A common use case when editing POIs is to select a brand preset to either:
* replace an obsolete POI
* augment and improve existing tagging of a POI that is not consistent with standardized values

In such a scenario Every Door seems to apply only the POI type (_amenity_, _shop_, _cuisine_ etc.). The _name_, _brand_ and other tags defined in the preset are not applied. I usually then choose the tag editor mode, remove all obsolete values, go back to the main editing screen and reapply the preset, which is obviously inconvenient.

I believe all values from the preset should be applied. I was even thinking if in such a case opening hours and contact information shouldn't be automatically cleared, but this is indeed more questionable, would be desired in the first, but not the second of scenarios listed above.

**Comment by Zverik** [comment]
Closing in favor of #561.
