### ISSUE TITLE
Update `collection_times` like `opening_hours`

### ISSUE THREAD

**Issue by habi** [Zverik/every_door#498]
It would be very nice if the collection times of post boxes could be updated with the nice UI of the opening hours.
Obviously usually only for one time point person day, not start-stop.

![image](https://user-images.githubusercontent.com/1651235/204083437-9216f065-ab4a-46a0-b84f-876bc0083033.png)

**Comment by Zverik** [comment]
Thanks for thee idea — already registered as #56 :)

**Comment by habi** [comment]
Sorry for the noise, missed to look through all the 'old' issues.
