### ISSUE TITLE
Add a toogle to use the Bremen Schema

### ISSUE THREAD

**Issue by Mannivu** [Zverik/every_door#499]
Even if the [Bremen Schema was proposed and archived](https://wiki.openstreetmap.org/wiki/Proposed_features/House_numbers/Bremen_Schema), in some regions it's widely used for the standard mapping of `housenumbers` info (you can see that [in Europe there's a wide use of contact:housenumber](https://taginfo.openstreetmap.org/keys/contact:housenumber#map)), so I think that a toogle to let the user decide if they can use the `contact:` prefix for amenities' address could help some in their contribution.

**Comment by ivanbranco** [comment]
+1, I thought that the "Prefer the "contact:" prefix" in the options was about the Bremen Schema, I found out it's about phone/contact:phone ecc. maybe this should be clearer?

**Comment by Zverik** [comment]
Oh my god this schema is awful. Sorry :)

In theory it can be added to the tagging presets repo just as [post:housenumber etc](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/post.json) are added, and it will be supported by Every Door then. But this will blow everyone's brains off.

So it's for tagging presets, not the editor (which uses whatever is there).
