### ISSUE TITLE
Add a button in micromapping mode to add the last added object

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#500]
In combination with https://github.com/Zverik/every_door/issues/436 this will allow you to quickly add many identical objects (benches, trash cans, trees, cameras)

It looks like the entrance mode, in which there are two floating buttons, but I suggest making one of them change depending on the last added object.

**Comment by Zverik** [comment]
Attribute values are kept for a few last added types. So currently the workflow is:

1. Tap on the plus button.
2. Choose the new location.
3. Choose the first (or 2nd, 3rd) last added type, always there.
4. Tap "Save".

Just four taps. Three after #436. Saving another one or two imo isn't worth possible mistakes when you're not sure what the last added object is, or some attributes need to be corrected.
