### ISSUE TITLE
Aktuelle Position teilen

### ISSUE THREAD

**Issue by biketeur** [Zverik/every_door#503]
Es wäre schön, wenn ich die aktuelle Position an eine andere App senden könnte.
Und umgekehrt, die dortige akt. Pos. an EveryDoor senden könnte.

**Comment by mnalis** [comment]
related (for second part): https://github.com/Zverik/every_door/issues/387

**Comment by Zverik** [comment]
Geo intents are planned, but sending a location to another app — not so much. The idea is that you use the current location, which is easy enough to get in another app.
