### ISSUE TITLE
Marathi language to be added to the app

### ISSUE THREAD

**Issue by sanketgarade** [Zverik/every_door#507]
Hello 

I have almost completed (98% strings done) for [Marathi language in the app on weblate](https://hosted.weblate.org/projects/every-door/app/mr/#overview).
Do these translations automatically get included and enabled in a future release or is there anything more that needs to be done from my side?

Thanks

**Comment by deevroman** [comment]
Weblate periodically updates its own translations. As seen here, for example https://github.com/Zverik/every_door/pull/485

**Comment by sanketgarade** [comment]
Ok got it. Thanks.
