### ISSUE TITLE
Make the colors of the dots in micromapping mode linked to the type of object

### ISSUE THREAD

**Issue by call-me-matt** [Zverik/every_door#509]
Love your app!
Wondering if it would be possible to pre-define at least some of the colors in micromapping mode - I just cannot get used to trees being shown in red and lamps in green, it always confuses me.
maybe already done in #451 ?
maybe possible in #119 .

**Comment by Zverik** [comment]
This is an idea for #119 — but generally colors are random because there are too many types, hundreds. The editor tries to keep colors as stable as possible during the current session though.
