### ISSUE TITLE
Swipe back gesture doesn't work in editor

### ISSUE THREAD

**Issue by euf** [Zverik/every_door#510]
Every Door 3.0 on iOS 16.0 doesn't allow to go back from the editor by swiping from the left edge of the screen. This is very confusing, because it's a default go back gesture expected to work in any context. At the same time, it does work correctly in settings, it's broken only in the editor.

**Comment by Zverik** [comment]
This was an UX issue: according to https://github.com/flutter/flutter/issues/14203, "back" gesture cannot be conditional on iOS. And the editor page checks for unsaved changes. Hence, as recommended, I transformed the page into a full screen dialog, which doesn't imply it can be swiped.

There is one UI hole left (creating a new amenity), but at the moment I've no idea how to patch that. Still, looks more consistent now in 3.1. Thanks for reporting, I would never notice that myself :)
