### ISSUE TITLE
farbliche Hervorhebung bestimmter Gebäudearten

### ISSUE THREAD

**Issue by biketeur** [Zverik/every_door#513]
Ich nutze ED viel dafür, falsch erfasste Gebäudearten zu korrigieren (terrace statt house) oder die allgemeine Gebäudeart residential zu präzisieren.

Hierbei wäre es sehr hilfreich, wenn ich einen Filter hätte, mit dem eine von mir gewählte Gebäudeart farblich hervorgehoben wird.

**Comment by Zverik** [comment]
Google translation:

> I use ED a lot to correct incorrectly recorded building types (terrace instead of house) or to specify the general residential building type.

> It would be very helpful if I had a filter that highlights the type of building I have selected in color.

**Comment by Zverik** [comment]
I'm afraid this color change would puzzle editors. And I don't understand what do you mean by "selected a building".

Anyway, your use case would most likely be solved with #119.
