### ISSUE TITLE
EV charging station missing socket:<type>

### ISSUE THREAD

**Issue by korakot** [Zverik/every_door#515]
I try to add an EV charging station. But I cannot add `socket:type2=1`. I check another station with socket info and it is not shown too.

**Comment by deevroman** [comment]
If any tag is not in the template, then it can be added through the list of all tags.

![-212446_temp.jpg](https://user-images.githubusercontent.com/25708359/210880223-45b595f2-ccb6-42be-8fb6-d0deea6c32e9.jpg)

If you want to see this tag in the template, then you will have to add it to the iD presets https://github.com/openstreetmap/id-tagging-schema
