### ISSUE TITLE
Let one character search effective

### ISSUE THREAD

**Issue by higa4** [Zverik/every_door#516]
On the tag search box, one character search seems to be ignored. But many Japanese (also Chinese) characters have enough meanings by one character. Please make it effective. It's very important for quick mapping.
ex. "酒"(alcohol), "木"(tree), "店"(shop), "道"(street)...
![IMG-9801_2 PNG](https://user-images.githubusercontent.com/551478/210942911-5a60dea1-bcad-4782-9b41-be01abd29e5a.jpg)

**Comment by Zverik** [comment]
Done in 3.1.
