### ISSUE TITLE
Satellite imagery overzoom does not work

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#52]
When zooming into satellite imagery, tiles become gray at some point.

**Comment by Zverik** [comment]
Yeah, I know about that and I set the correct zoom limits for layers. Alas there's a bug somewhere in [flutter_map](https://pub.dev/packages/flutter_map) that probably overzooms layers a little too much. This issue is about that.

**Comment by pyrog** [comment]
What is strange is that over zoom work for osm tiles, not for satellite images.

Note: I solved this issue for a vector style edited directly in [maputnik](https://maputnik.github.io/editor/#12.36/47.12799/5.59058). Have you tested vector styles with flutter ?

**Comment by Zverik** [comment]
Overzoom works for OSM tiles because of #132.

**Comment by Zverik** [comment]
Done in 0.5.
