### ISSUE TITLE
Notes are lost when loading new data

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#520]
For stable playback, clear the already downloaded data. Please note that apparently by mistake it does not clear the notes. https://github.com/Zverik/every_door/issues/519

1. Upload a new area
2. Put a note on the edge of this area or outside it
3. Move to the note so that there is a suggestion to upload a new area
4. Upload a new area
5. The note is lost

https://user-images.githubusercontent.com/25708359/211158699-aa7c073f-49d3-431f-8ace-7005b923194a.mp4

**Comment by Zverik** [comment]
Fixed in 3.1 — but changes to existing notes would still be lost. Made #581 to track that, but not in the nearest versions.
