### ISSUE TITLE
Add high res (but old) imagery layer

### ISSUE THREAD

**Issue by thibaultmol** [Zverik/every_door#526]
A lot of other osm editors have this layer
https://geoservices.informatievlaanderen.be/raadpleegdiensten/OGW/wms?LAYERS=OGWRGB13_15VL&STYLES=&FORMAT=image/jpeg&CRS={proj}&WIDTH={width}&HEIGHT={height}&BB

Yeah, it's dating back from 2013 , but it's convenient sometimes to check something on the higher res layer.

(You can also find it in the osm imagery index)

**Comment by Zverik** [comment]
Layer source: https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/be/AIV10cm.geojson (I don't see it in the app indeed).

**Comment by Zverik** [comment]
Generally the idea is, you don't use the imagery to trace things in this editor, but just as a reference for on the ground mapping. So missing layers should not pose a big issue. But I'll look into this nevertheless.

**Comment by thibaultmol** [comment]
Yeah, but sometimes things are hard to see on the lower resolution recent
imagery but you know it has existed for at least 10 years so the old
imagery would show it as well
👍

**Comment by Zverik** [comment]
So what I found is, 1) the layer has been deleted last week; 2) it had a category of `historicphoto`. The editor injests only layers of `photo` and `map`. So it was filtered out.

**Comment by thibaultmol** [comment]
Actually, the Flanders government overhauled their systems and the URL has changed. 
see
https://github.com/osmlab/editor-layer-index/pull/1884

**Comment by Zverik** [comment]
Thanks, though it's still a `historicphoto` type of a layer. I'd understand the need to enable it if we didn't already have multiple more recent satellite imagery layers for the area.

**Comment by thibaultmol** [comment]
The reason why this one is so important. And the reason why it's default in ID and JOSM. Is because it's the highest resolution layer available in Flanders
