### ISSUE TITLE
Display notes in other modes

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#528]
Similar to how it is done in OSM objects in other modes: a small dark dot.

One of the examples:

I want to add a note that there is an arch with a passage in the building. But there is an entrance next to the arch, and it is difficult to show where it is located without seeing where the note is placed. (especially because of the zoom change when switching to notes mode)

**Comment by Zverik** [comment]
Not sure if this is still relevant: notes are displayed when adding an object or a note, in all modes.

**Comment by deevroman** [comment]
Not really. If in buildings mode, you're probably using drag and drop buttons rather than the intermediate screen from the building/entry location selection

**Comment by Zverik** [comment]
Come on, your comment breaks your use case. If you know there's a specific note and you want to use it in positioning a new building, you could take an additional tap for opening the standard positioning screen.
