### ISSUE TITLE
which products / services a shop offers (more details)

### ISSUE THREAD

**Issue by coffeepotprotocol** [Zverik/every_door#532]
Use case
Typical things a shop offers :
Sales
Parts
Repair
Rental

Not every shop is "specialized", it might also offer things you'd expect from other features. Or a shop offers similar services (i.e. repair or rental) for/of different things. An example would be https://taginfo.openstreetmap.org/keys/mobile_phone:repair. Whether they offer delivery might also be interesting.

Proposed Solution
Add optional services to the shop menu https://wiki.openstreetmap.org/wiki/Shop_suffix

Filter already implemented in OsmAnd
![motorcycle](https://user-images.githubusercontent.com/28932695/215179790-033e883c-ebc3-4ede-8d6c-df48738f23b0.jpg)

**Comment by Zverik** [comment]
Good idea! All tagging is managed in the https://github.com/openstreetmap/id-tagging-schema/ repo, so that it's usable from the iD editor. Try making this one there.
