### ISSUE TITLE
OAuth error when attempting to set up new phone

### ISSUE THREAD

**Issue by pnorman** [Zverik/every_door#533]
I got a new phone and need to set up OAuth again. When I try to upload and press the OAuth button I get this message 

![Screenshot_20230127-153026](https://user-images.githubusercontent.com/1190866/215362676-fa10f2ff-8fc1-4fa1-8867-511c92f9529e.png)

every door version 3.0 on a Google Pixel 7

**Comment by PaulTheArchivist** [comment]
I'm having the same problem, just moved on to a Google Pixel 5 phone. I've also tried the log in with password option and nothing at all happens when I try that it just goes back to the previous screen. I'm also on version 3.0. 
![Screenshot_20230206-191946](https://user-images.githubusercontent.com/97367476/217066252-fe274241-e19e-4901-8714-574e1443204c.png)

**Comment by pnorman** [comment]
I reinstalled every door and it works so it looks like the issue is related to moving phones. I'm leaving it open because it's a bug, but testing it is difficult because it requires an install with the data being wrong in some way that happens when you move phones.

**Comment by tomchiverton** [comment]
Snap, pixel 4a to 6a

**Comment by CloCkWeRX** [comment]
Add pixel 7 to the list.

**Comment by HandyHat** [comment]
Same here - Pixel 3 to 7

**Comment by call-me-matt** [comment]
Pixel 8 has the same issue. Reinstall of the app solved it also for me.

**Comment by Zverik** [comment]
Looks like this is the relevant upstream ticket: https://github.com/teranetsrl/oauth2_client/pull/134

Which references the even more upstream `flutter_secure_storage`: https://github.com/mogol/flutter_secure_storage/issues/541 and https://github.com/mogol/flutter_secure_storage/issues/354

Those issues are still unsolved, but I should read the full threads and see if anybody has a good idea on bypassing the error.

**Comment by kevinetore** [comment]
@Zverik I came to the same conclusion, did you find any solutions to the error?

**Comment by CloCkWeRX** [comment]
https://github.com/mogol/flutter_secure_storage/issues/354#issuecomment-1170367152 appears to be the most widely accepted workaround, but not clear if it helps existing data.

The other workaround - deleting the specific token on exception also seems to have a bit of traction

**Comment by CloCkWeRX** [comment]
(clear app data should also do the trick for us in userland)

**Comment by Zverik** [comment]
Hopefully fixed, thanks @CloCkWeRX for pointers. Please test https://github.com/Zverik/every_door/actions/runs/8775080923 if you have access.

**Comment by pnorman** [comment]
Since the only way I've triggered this is with a new phone I can't test right now.

**Comment by Kofl** [comment]
Delete and reinstall also fixes it for Pixel 8 Pro

**Comment by Zverik** [comment]
Thanks, I guess I'll close it then.
