### ISSUE TITLE
Add postcode field

### ISSUE THREAD

**Issue by Firefishy** [Zverik/every_door#535]
It would be appreciated if a postcode field could be added.

The postcode is an important address field for at least UK, Ireland, South Africa and likely many more.

**Comment by Zverik** [comment]
We already had discussions on postcodes in #310 and #326. The problem with these is, they are rarely displayed outside, and since the editor is primarily for on-the-ground surveying, it doesn't make sense to clutter the interface with a field that's almost never used.

**Comment by Firefishy** [comment]
VAT numbers are rarely displayed outside too ;-)

The postcode is required (as part of address) to be on all VAT receipts in the UK.
The full address including postcode is also surprisingly common on signs at the door (at least in the UK)

**Comment by mnalis** [comment]
> VAT numbers are rarely displayed outside too ;-)

I guess it depends on a country; in Croatia `ref:vatid` is actually very common  to be written on the shop doors along with `opening_hours`, `phone` etc. (so common in fact that I'd hazard to guess it might be mandated by the law) 

>  The full address including postcode is also surprisingly common on signs at the door (at least in the UK)

But I agree here that it would make sense to show `postcode` under `More Fields` (i.e. at same place as `ref:vatin`, so it would not clutter normal input display). 

I know (and like) that EveryDoor is primarily on-the-ground tool, but as @Firefishy notes, UK at least is somewhat specific regarding what they call "postcodes". It is more like `block/building unique id` or [what3words](https://wiki.openstreetmap.org/wiki/What3words)-alike schema than what it means in Croatia and surrounding countries (where usually nobody but postman cares about postcodes at all about, and they are not display prominently)...

In fact (to my limited experience in UK) you're probably more likely to be guided to your destination by postcode only, and use street name and housenumber only for fine positioning when you reach that postcode.

**Comment by matheusgomesms** [comment]
In Brazil post codes are also displayed on street name signs.

**Comment by Zverik** [comment]
I'll have to think a bit on this, but there's one thing I should point out. The building/address form is for "quick adding", for when you walk or drive past many buildings. Hence it should be as compact as possible. Like, `addr:block` could go in there in some countries (#455), but for postcodes, tapping on "More..." button and filling it in there is not too much extra work.

**Comment by Firefishy** [comment]
Hidden behind "More Fields" makes sense to me.

2 examples of postcodes found in the wild in the UK:

![PXL_20230204_105621603](https://user-images.githubusercontent.com/248188/217809222-3f4ea003-43ed-4834-8828-d575ea646529.jpg)

![PXL_20230203_130052523](https://user-images.githubusercontent.com/248188/217809203-a8ec6959-7ffb-47a1-a569-9f958e3e92e1.jpg)

**Comment by Zverik** [comment]
Done in 4.0.
