### ISSUE TITLE
Post box references codes doesn't allow letters

### ISSUE THREAD

**Issue by SuborbitalPigeon** [Zverik/every_door#537]
In Britain, post box reference codes have letters in them. However, the default UI of Every Door doesn't allow letters, only numbers. They can of course be edited using the manual tag editing feature.

This is with Android.

**Comment by Zverik** [comment]
It does — but for that you have to enable extended keyboard in the settings. If it doesn't work with that, please post a screenshot for reference.

**Comment by SuborbitalPigeon** [comment]
Yup, that works. Just curious why there's a setting for this.

**Comment by Zverik** [comment]
Closing this in favor of #636.
