### ISSUE TITLE
Note comments notifications

### ISSUE THREAD

**Issue by angoca** [Zverik/every_door#538]
When a map user creates a note and uploads it from the app, the note could receive a comment from another mapper immediately asking for more details. But the map user is only notified about the note comment when it receives the mail message, but not in the app. 

It will be interesting to have a subscription mechanism for the notes in the working area so that if any note receives a comment, a notification will appear on the device.

The notes can allow real-time modifications (map users with phones on the ground and mappers on the computers). However, it needs a notification mechanism for the messages (comments) in the notes.

This kind of feature will improve the mapping in disaster scenarios, where many mappers are on the computers, with people on the ground reporting the changes on the map.

**Comment by Zverik** [comment]
Good idea, but not possible at the moment because the OSM website does not provide any API for that. See https://github.com/openstreetmap/openstreetmap-website/issues/908 and https://github.com/openstreetmap/openstreetmap-website/issues/1387.
