### ISSUE TITLE
State of Development

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#539]
Hey all, I know you might be a bit frustrated there haven't been a new release of Every Door since October.

First, I want to thank you for adding bug reports and feature requests. It's important that we don't forget these and that I can later sort them between releases. And most of all, it shows you are using the app, which makes me happy :)

Regarding the plans, I'm currently a bit burned out at my current job, and I have few other projects, hence I have got literally zero time to work on Every Door. I dreamed of having a kind of a grant or a temporary job to work on improving the editor, but with the current economy and my lack of experience at raising money, this is unlikely.

I expect to have some time around April-May, since Summer is the best time to go out and map, and I plan to map the heck out of my new surrounding area.

For the roadmap, I plan to release 3.1 with smaller fixes that have been piling up, and then 4.0 with the freehand drawing mode (#197), that was planned from the beginning.

**Comment by matkoniecz** [comment]
> I dreamed of having a kind of a grant or a temporary job to work on improving the editor, but with the current economy and my lack of experience at raising money, this is unlikely

Have you tried https://nlnet.nl/ ? I had some successes with them (though apparently they have growing number of applicants).
