### ISSUE TITLE
[Feature Request] Allow custom WMS background layer

### ISSUE THREAD

**Issue by joshinils** [Zverik/every_door#547]
I would like to see updated and or newer WMS or some custom Data source not useful outside my city.
And if implemented, please allow multiple sources at the same time, maybe with custom opacity.

For example, if I were to add a tree layer of my city, this would have opacity and be useful for adding trees, but seeing the DOP (or OSM) would be necessary as well to see which tree I am looking at.

**Comment by deevroman** [comment]
https://github.com/Zverik/every_door/issues/423

**Comment by joshinils** [comment]
ah my bad, I only searched for WMS in the issues
