### ISSUE TITLE
Amenity age warning can display for buildings

### ISSUE THREAD

**Issue by MMK21Hub** [Zverik/every_door#549]
If a feature is old, a banner appears at the top of the edit screen that says "Amenity is X years old". However, the text remains the same if a building is being edited. It should probably say "Building is X years old" instead, or not show at all.

This is likely also an issue with other feature types, such as entrances and micromapping features, but I have not tested this.

![The screen for editing a building. Yellow banner says "This amenity is 5 years old.](https://user-images.githubusercontent.com/50421330/226119400-b3282275-430b-42da-a7a1-0695c1b15e91.png)

**Comment by Zverik** [comment]
Done in 4.0: this warning is displayed only for amenities.
