### ISSUE TITLE
Hangs when authentication is cancelled

### ISSUE THREAD

**Issue by richlv** [Zverik/every_door#556]
* Have unauthenticated app, attempt to upload changes.
* In the OSM auth form, hit cancel.
* The resulting screen is inoperable, efficiently hanging the app.

![IMG_8409](https://user-images.githubusercontent.com/112888/230722953-2950a29e-5080-4905-8e58-91a10c52b57c.PNG)

iOS, Every Door 3.0.

**Comment by deevroman** [comment]
Duplicate https://github.com/Zverik/every_door/issues/147

**Comment by richlv** [comment]
Thank you for spotting that, my searches did not turn that issue up.
Trying to mark it as a Github duplicate...
Duplicate of #147 .

**Comment by richlv** [comment]
Duplicate of #147

**Comment by Zverik** [comment]
Duplicate of #147

Thanks Roman and Richlv.
