### ISSUE TITLE
Difficult to add a name in another language

### ISSUE THREAD

**Issue by arrival-spring** [Zverik/every_door#557]
When I add or edit an element, the languages suggested to me are English and Zulu (in South Africa).

However if I want to add another language I have to search for it after tapping the globe icon. This list is maybe in order of most common languages, but not for my region so it's very hard to find the right one (there's no option to sort alphabetically either).

If I go to add the tag directly then when I type `name:st` it tries to autocomplete it, giving me two wrong options. I can't advance to the value box without it changing the key to `name:statcan_rbuid`.

**Suggested solutions**
* Show the languages of the current country at the top
* Sort the languages to somehow prefer languages of the current region (possibly region smaller than country)
* Allow sorting the languages alphabetically
* Make it possible to add a key without autocompleting it

**Comment by neuschaefer** [comment]
Another suggested solution:

- Add a keyboard input / search bar to the language picker, so that the flow for uncommon languages becomes:
  - tap the globe icon
  - enter a few characters of the language name or abbreviation (e.g. `st`)
  - pick the right result from the filtered list

**Comment by Zverik** [comment]
Added a search bar in 4.0.
