### ISSUE TITLE
Allow moving nodes if they are part of a relation

### ISSUE THREAD

**Issue by gdabski** [Zverik/every_door#558]
EveryDoor prohibits moving nodes when they are part of a larger geoemtry, e.g. line or polygon. That obviously makes sense. But it also prohibits moving point POIs when they are first-class members of a relation. Moving such points shouldn't cause any harm.

A specific example is not being able to adjust the position of a municipal bike station, because it's part of a relation that groups all such stations in the city.

**Comment by deevroman** [comment]
Duplicate https://github.com/Zverik/every_door/issues/245
