### ISSUE TITLE
Write only objects

### ISSUE THREAD

**Issue by matkoniecz** [Zverik/every_door#559]
https://www.openstreetmap.org/node/10788307353 was added with ED but cannot be edited with it

Redownloading data for area changed nothing

**Comment by mnalis** [comment]
Hmmm, I can? But it is under `amenity mode`, not `micromapping mode`

![small_Screenshot_20230413_223544_info zverev ilya every_door](https://user-images.githubusercontent.com/156656/231877193-84022ee7-eef2-497a-b3b0-21ce48135ef6.jpg) ![small_Screenshot_20230413_223705_info zverev ilya every_door](https://user-images.githubusercontent.com/156656/231877304-ee23f69c-3bdb-41cc-977b-42387dd61cb4.jpg)

(note that you can **create new** parcel locker from _either_ mode)

**Comment by matkoniecz** [comment]
Oh, thanks!
