### ISSUE TITLE
Exclude churches and places of worship from bimonthly check

### ISSUE THREAD

**Issue by ivanbranco** [Zverik/every_door#562]
Hi,

I think churches and amenity=place_of_worship should be excluded from bimonthly check. Most churches here has been built in XIII and I don't think the situation will change soon :p 
jokes aside, they clog-up the "to be checked" list, making it less useful (for me at least). If not excluding them, maybe increase the check time for these elements up to 1 or 2 years?

**Comment by Zverik** [comment]
Done in 3.1, set to 1 year.
