### ISSUE TITLE
Exclude recently surveyed places from bimonthly check

### ISSUE THREAD

**Issue by ivanbranco** [Zverik/every_door#563]
Hi,

I went for a walk in town and checked some shops meanwhile. When I got home I noticed I checked shops that were recently surveyed, but where the date was added as survey_date=* instead of check:date=*. Maybe the "bimonthly check" should keep in consideration the most recent date of both tags, so users can focus on not-checked places.

**Comment by Zverik** [comment]
I just chose the most used and known tag for the check date :) Regarding others, I assume they have been set with different editors, which might miss some attributes like a phone or a wheelchair accessibility. So even if they were checked like a day ago, it would still have sense to take another look with Every Door.
