### ISSUE TITLE
Please add craft=grinding_mill in POI type selector

### ISSUE THREAD

**Issue by sanketgarade** [Zverik/every_door#570]
I wanted to add flour mills, but searching "mill" didn't show up anything.

[Wiki for the said tag](https://wiki.openstreetmap.org/wiki/Tag:craft%3Dgrinding_mill)

![image](https://github.com/Zverik/every_door/assets/74632379/b79da2d6-1e09-47d7-8bbe-579ec6aca138)

**Comment by deevroman** [comment]
Every Door takes presets from 
https://github.com/openstreetmap/id-tagging-schema . The presets database is updated as Every Door is updated. The grinding_mill was added [after](https://github.com/openstreetmap/id-tagging-schema/commit/13f1d024f3303e921d02ea5e422d2e90f055cfed) the last update of EveryDoor, so will have to wait for the next update.

**Comment by Zverik** [comment]
Yeah sorry about the lack of updates. I really need to fix the presets script to comply to the last schema update, and then I'll be able to publish the ED update.
