### ISSUE TITLE
name:signed=no is misinterpreted as name "no" in language "signed"

### ISSUE THREAD

**Issue by neuschaefer** [Zverik/every_door#577]
[Version: Every Door 3.0]

When Every Door encounters POI with `name:signed=no`, it interprets it as named in the language "signed", and shows the value ("no") as the name of the POI, rather than falling back to the `operator` value.

This is incorrect, as `name:signed=*` [has a specific meaning](https://wiki.openstreetmap.org/wiki/Key:name:signed).

**Comment by Zverik** [comment]
Fixed in 3.1.

**Comment by mnalis** [comment]
Hmmm, I'm using Every Door 3.1 (from F-droid) but it still seems to show _"no"_ as a name when `name:signed=no` is used (see element number `1.` in the list):
 
![small_Screenshot_20230611_173133_info zverev ilya every_door](https://github.com/Zverik/every_door/assets/156656/fc5e38ce-c9dd-4b1b-b942-540c6872649a) ![small_Screenshot_20230611_173141_info zverev ilya every_door](https://github.com/Zverik/every_door/assets/156656/9257084a-d9c0-45a3-b446-00713d9c322e)

I think it should not be showing _"no"_ as a name, but shown as `2.` in the list in that example.

Can it be reopened?

**Comment by Zverik** [comment]
Fixed in 3.2.
