### ISSUE TITLE
Outdoor seating values other than yes or no

### ISSUE THREAD

**Issue by codeinabox** [Zverik/every_door#579]
I noticed a bug in the app where it doesn't recognise `outdoor_seating` values other than yes or no. A pub near me has `outdoor_seating=garden`, which Every Door doesn't handle.

**Comment by Zverik** [comment]
I guess this need to be done in the tagging repo: https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/outdoor_seating.json
