### ISSUE TITLE
[feature] Support Key:surveillance

### ISSUE THREAD

**Issue by hex-m** [Zverik/every_door#585]
Currently to add the key `surveillance` to a node/amenity (like a shop, bar, restaurant,..) it is necessary to open the "node view" and manually add the key and a value according to the [documentation](https://wiki.openstreetmap.org/wiki/Key:surveillance).

I suggest to show this in the UI. Similar to "is there internet available" I would like to map "is this under surveillance". `yes` and `no` would suffice as possible values.

**Comment by Zverik** [comment]
This needs to be done in the presets repo: https://github.com/openstreetmap/id-tagging-schema
It already has the [surveillance](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/surveillance.json) field, but I assume you want it to be added to certain presets.
