### ISSUE TITLE
Easier adding of wikimedia_commons=* tag

### ISSUE THREAD

**Issue by mnalis** [Zverik/every_door#586]
People on mobile usually use [Wikimedia Commons App](https://github.com/commons-app/apps-android-commons) to upload pictures and metadata to Wikimedia. The app provides `Copy the wikitext to the clipboard` button, which produces something like this in copy/paste buffer:

> [[File:Kaptol_Square,_Zagreb,_Croatie.jpg|thumb|other_optinal_metadata...]]

OSM [wikimedia_commons=*](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons) tag expects the values to be in the format:

> wikimedia_commons=File:Kaptol_Square,_Zagreb,_Croatie.jpg

Current workflow is:
1. create picture in Wikimedia Commons App and click `Copy the wikitext to the clipboard` in it
2. switch to Every Door, navigate to `wikimedia_commons` field and paste value
3. edit the pasted value to erase `[[` at the beginning, as well as everything after first `|`

That third step is very time consuming (and error prone if user sits on backspace key a fraction of second too long). 

It would be great if **EveryDoor could automate it** -- e.g. if it detects the value starts with `[[` it should simply extract the text until first `|`, and use that as a raw tag value for  `wikimedia_commons=*` OSM tag.

(related commons issue: https://github.com/commons-app/apps-android-commons/issues/4371)

**Comment by Zverik** [comment]
You're very in luck: done in 3.1, released later today :)
