### ISSUE TITLE
highway=emergency_access_point is not rendered

### ISSUE THREAD

**Issue by gitmuti** [Zverik/every_door#587]
Hi,
highway=emergency_access_point is not rendered

Already existing are not shown.

Example node id 520398764

Every door can create new one but after upload it is also not shown

Found in Every door 3.1 and 3.0

Can you please check?

**Comment by Zverik** [comment]
Yeah it's not in the list of supported tags. I've just added it, will appear in the next release.

**Comment by mnalis** [comment]
Hmmm, if it is not in the list of supported tags, should EveryDoor be able to create it? i.e.

> Every door can create new one but after upload it is also not shown

I would expect that if the tag is _not supported_, that it can't be created either? 

Being able to create it, but then unable to see it or edit it sounds like a strange design decision which is bound to be confusing to users?

**Comment by Zverik** [comment]
Thing is, I do not filter presets (except by geometry type), but I do filter tags to download. This allows for issues like this one, but it's pretty rare, and fixing this is straightforward. Also, objects create still show in the editor, although one can make duplicates without knowing.
