### ISSUE TITLE
Street vendor tag

### ISSUE THREAD

**Issue by codeinabox** [Zverik/every_door#592]
Love your work with this app! One feature request, could support for the [street_vendor tag](https://wiki.openstreetmap.org/wiki/Tag:street_vendor%3Dyes) please be added. Happy to raise a PR for this if I could be given a few pointers

**Comment by Zverik** [comment]
I guess you would need to add the field to https://github.com/openstreetmap/id-tagging-schema (which is also used by iD editor). Basically add a field [like this](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/button_operated.json) and add its name to shops — to [all of them](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/shop.json) or a [subset](https://github.com/openstreetmap/id-tagging-schema/tree/main/data/presets/shop).
