### ISSUE TITLE
Duplicate fields in a crossing editor

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#595]
As Roman found, and I could reproduce albeit with 2 fields:

![crossing-markings](https://github.com/Zverik/every_door/assets/766031/c1cd8b6f-f3e9-4b97-a658-2694797d4363)

**Comment by deevroman** [comment]
Also duplication can be seen on the screen in this issue https://github.com/Zverik/every_door/issues/612#issue-1825985476

**Comment by Zverik** [comment]
The reason for all three cases is that there are duplicate fields that differ in locations. The app doesn't support `locationSet` for fields, yet.

**Comment by Zverik** [comment]
Fixed in 3.2.

**Comment by riQQ** [comment]
See also 1c4f21c7e3120d326e9719230f0789179e7d6b7d
