### ISSUE TITLE
No grave poi on map

### ISSUE THREAD

**Issue by ERYpTION** [Zverik/every_door#596]
It is possible to add a grave ([cemetery=grave](https://wiki.openstreetmap.org/wiki/Tag:cemetery%3Dgrave)) poi in the app. However, existing graves does not show up on the map. Would be nice so that it is possible to not only add but also adjust position, add inscription etc in the field.

Thanks!

**Comment by Zverik** [comment]
Done, added to the micromapping mode in 3.2.

**Comment by riQQ** [comment]
See also e872e6e244624533c78fec35a63ef4a8bbc039f3
