### ISSUE TITLE
Information Board has outdated tags

### ISSUE THREAD

**Issue by ERYpTION** [Zverik/every_door#597]
Just noticed that after adding an Information Board selecting 'map' for type, I see this notification for the poi in the iD editor: 

Information Board has outdated tags

Suggested updates:
- (minus) board_type=map
- (minus) information=board
+ (plus) information=map

**Comment by mnalis** [comment]
Thanks for your report!

In EveryDoor 3.1 at least, you should probably instead choose `Map` and it will tag `tourism=information`+`information=map` correctly.

---

However, if you choose `Information board`, it will tag `tourism=information`+`information=board`, but also has an extra field `Type` which you can set to `Map` which would additionally add `board_type=map` which is (as you note) [deprecated](https://wiki.openstreetmap.org/wiki/Key:board_type).

Generally every_door users [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema/) for presets, but I'm somewhat puzzled here as there does not seem to be `map` value listed here: https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/board_type.json

Unless I'm wrong, I [think](https://github.com/Zverik/every_door/blob/main/README.md#how-to-build) it probably uses [board_type values currently in use](https://taginfo.openstreetmap.org/keys/board_type#values) from taginfo, which still includes some **2 789** uses of `board_type=map`. When that value goes to zero (or some low value?) I think it should probably disappear automatically on subsequent EveryDoor release. 

But I do not know if it there are options for easily blacklisting that specific value even if it is being used in the wild. :shrug:

**Comment by Zverik** [comment]
I think that's a mapper's mistake, not the app's. If you search for a "map" or an "info", you can see a map to add with proper tags.
