### ISSUE TITLE
GPS position freezes after switching to other app and then switching back

### ISSUE THREAD

**Issue by Zaczero** [Zverik/every_door#598]
As the title suggests, the only way I can restore GPS updates is by completely relaunching the application. I don't encounter this issue with other apps, like StreetComplete. I have attempted waiting for some time, but the issue does not resolve itself.

**Comment by Atrate** [comment]
May be related to https://github.com/Zverik/every_door/issues/199?

**Comment by Zaczero** [comment]
The location updates fine, as long as I don't tab out of the application.

**Comment by Zverik** [comment]
Please try the same in [4.0-beta1](https://github.com/Zverik/every_door/releases/tag/v4.0-beta1) (or wait a week until release).

**Comment by Zaczero** [comment]
I will wait and report back after the release :+1: Thanks!

**Comment by Zverik** [comment]
The app is up in Google Play store :)

**Comment by Zaczero** [comment]
Awaiting an F-Droid release :)

**Comment by Zaczero** [comment]
Fixed :+1:
