### ISSUE TITLE
Redesign purging cached data so it's understandable

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#6]
Nothing happens when I press the button

**Comment by Zverik** [comment]
It should not: the button only purges _obsolete_ data, which is at least a week old.

**Comment by mfbehrens99** [comment]
The message you added makes it much better :)

However, it might still be nice to be able to either update all data or purge all data for team mapping activity

**Comment by Zverik** [comment]
Possible options:

* show "N/M" or "N% of M" (too wide).
* show only number of obsolete items and hide the total number.
* make a sub-pane with multiple options (clear obsolete, clear all, more info).
* hide the number.

**Comment by Zverik** [comment]
Now the item shows only obsolete data count, and switches to full data count when there are none. Fixed in 0.1.8.
