### ISSUE TITLE
Exception Failed to query OSM API 414 error

### ISSUE THREAD

**Issue by SquishyBubble** [Zverik/every_door#600]
Hi! Trying to upload a rather large changeset through the app today (north of a thousand nodes containing a few thousand tags) i encountered the error "Exception Failed to query OSM API 414 error" followed by long possibly even truncated URL. The chanceset contained notes as well if it helps. Using the 3.1 version of the app and unfortunately the log seems to get flushed after the error appears.

**Comment by SquishyBubble** [comment]
I guessed it could have something to do with the number of bodes ibvolved. I've already downloaded the osmChange file so nothing is lost. Just figured you'd want to know. I guess not everyone usibg the app is savvy with JOSM.

Amazing work by thr way. Your app made me flesh out the number of nodes in my neigbourhood by a factor of 10 or so. It wouldn't have happened without Every Door.

**Comment by Zverik** [comment]
Fixed in 3.2.
