### ISSUE TITLE
Project health: consider a tipjar/buymeacoffee/etc

### ISSUE THREAD

**Issue by CloCkWeRX** [Zverik/every_door#609]
Everydoor is a great project, and provides value.

I would encourage you to look at ways that fit with your worldview to look at mechanisms for adhoc or even grant based funding.

Buymeacoffee is a reasonable tipjar provider, something like patreon or osmlive are examples of recurring small amount funding.
Similar projects such as street complete or some of the HOT mapping applications have been able to apply for and receive grants.

It may not amount to much, if anything, but it would be a way for users like myself who can't write a dart application but care about mapping to say thanks!

**Comment by Zverik** [comment]
Good idea! Also asked in #492. I'm keeping this venue open, but currently seeking corporate or institutional support, since the editor is still in early stages :)
