### ISSUE TITLE
Basic road editor

### ISSUE THREAD

**Issue by empty-child** [Zverik/every_door#610]
Hello Zverik,

Do you have any plans for adding some functionality of road editing? I mean, speed limits, unidentified police surveillance, lanes, parking lanes. Maybe, turn restrictions, but it is realized through relations, and it's out of simple mapping app responsibility.

**Comment by Zverik** [comment]
Hi ec, I'm sorry but I don't. ED is focused solely on points and polygon attributes. See design principles in the repo's readme. But #197 in the future can help with mapping linear features too.
