### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by Mannivu** [Zverik/every_door#612]
I've seen that the presets for the Mail Drop Box says "Mounted in a wall" but I think it should be "Mounted on a wall"
![Screenshot_2023-07-28-10-41-14-215_info zverev ilya every_door](https://github.com/Zverik/every_door/assets/42747216/1a98cbca-0a41-4efa-9320-457356549b41)

**Comment by deevroman** [comment]
https://github.com/Zverik/every_door#presets-and-translations

**Comment by Mannivu** [comment]
@deevroman thank you, I didn't see that part. I've opened an issue on Transifex.
