### ISSUE TITLE
Notify when changing the type to/from building

### ISSUE THREAD

**Issue by empty-child** [Zverik/every_door#616]
Hello

I've noticed that in 3.1 the next behavior: if we have a building and want to add tag for a whole building (for example, add tourism=hotel) with upper menu (where we can change tag), building tag will be overwritten. On the earlier versions, the app only added tag (building=yes AND tourism=hotel). Maybe I missed something or don't know, but it's confusing

**Comment by Zverik** [comment]
Yeah, you write it yourself: "where we can change tag". Change from the current object type to something else. In your case, from a building to a hotel. That it stops being a building and becomes a hotel.

I agree that's not idea. In case of buildings, I maybe should split their treatment from amenities they host.

**Comment by empty-child** [comment]
Maybe, to add a pop-up in this type of changing? Because there are only ways to add manually or to add as a node for exact this case

Also, I didn't expect such changes in a minor version

**Comment by Zverik** [comment]
Okay this notification would be useful I think. There are those options when changing the type:

* Proceed with changing the type (is there a real world use case for this?..).
* Add the type to the building instead (may lead to issues?).
* Add a node to the building center instead.
* Cancel changing type.

**Comment by empty-child** [comment]
Changing the building type on amenity type, for example, is such a niche case. Maybe to suggest "Tag will be applied for the whole building. Are you sure?"

**Comment by Zverik** [comment]
Another option came up: see #644 for an easier way of adding an amenity to a building or an address node.

**Comment by Zverik** [comment]
Note: there are no building presets in the app, so the issue applies only to building→amenity transition.

**Comment by Zverik** [comment]
Decided to simply forbid changing building to another type (already in 4.0), and to use #644 for a process of adding amenity tags to a building.
