### ISSUE TITLE
Raised crossing is not detecting all the possible values for traffic_calming

### ISSUE THREAD

**Issue by andreadecorte** [Zverik/every_door#617]
Creating a raised crossing with ID editor adds to the crossing node a tag
`traffic_calming=table`

EveryDoor seems to know only about 
`traffic_calming=yes`
So the crossing is not detected as raised.

I think EveryDoor should consider any value for traffic_calming as valid for raised (and keep using a default of yes or use ID default value)

**Comment by Zverik** [comment]
Huh. iD indeed adds the `table` value when you check the box. [The preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/crossing_raised.json) uses an undocumented feature. I'll look into that.

And yes, I agree it should treat any value as "yes".

**Comment by Zverik** [comment]
Done in 3.2.
