### ISSUE TITLE
tourism=museum with was:amenity not displayed

### ISSUE THREAD

**Issue by Robot8A** [Zverik/every_door#620]
Hi,
I updated a tourism=museum using Every Door, to add that before it used to be a mosque was:amenity=place_of_worship. After that, it is not editable in Every Door anymore, and doesn't appear (the change got properly uploaded).

Here is the node:
https://www.openstreetmap.org/node/3031023098

Thanks

**Comment by Zverik** [comment]
Fixed in 3.2. The disappearance was because `was:*` keys mark the amenity was closed and essentially deleted.
