### ISSUE TITLE
(Swedish) In the FAQ; the segment regarding Floor 3 and /3 is difficult to understand. 

### ISSUE THREAD

**Issue by Christoffre** [Zverik/every_door#626]
In the Swedish FAQ, in the segment regarding the difference between floor 3 and /3; the text is very cumbersome and difficult to comprehend, at least in Swedish. 

In stark contrast to all the other texts in the Swedish FAQ, which all are good.

**Comment by Zverik** [comment]
Hi Christoffer, please fix the translation [on Weblate](https://hosted.weblate.org/translate/every-door/app/sv/?checksum=dc0d21a52cf40ffa&sort_by=-priority,position), and thanks for catching this :)
