### ISSUE TITLE
Type=address fields are not editable

### ISSUE THREAD

**Issue by gena01** [Zverik/every_door#628]
It seems that some tags are missing when mapping letter boxes, things like `support` and `post:*` addresses would need much easier if they could be provided in the UI. I am sure there's possibly other tags missing as well.

**Comment by mnalis** [comment]
I'm not sure if you mean [amenity=post_box](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_box) or [amenity=letter_box](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dletter_box) when you say _"letter boxes"_, but the former does include [support=*](https://wiki.openstreetmap.org/wiki/Key:support) when you click `More fields`.

But unless I'm wrong, Every Door uses [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema) for such presets, so you want to open issue there instead.

Or you could even do a PR, it looks simple enough:

https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/post_box.json

or

https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/letter_box.json

**Comment by gena01** [comment]
I did mean `amenity=latter_box`

**Comment by mnalis** [comment]
Thanks for clarification that this is about `amenity=letter_box` tag. 

As I said [above](https://github.com/Zverik/every_door/issues/628#issuecomment-1712883150), the issue seems to be in another project called `id-tagging-schema` which Every Door uses, so you should report issue / suggest changes there (and then the next release of EveryDoor would pull those changes automatically)

**Comment by gena01** [comment]
I am looking at their preset and it does have `post` tag. Somehow that's not recognized as `post:*` instead of the `address:*` tag(s). This makes tagging things like house numbers on letter boxes a bit more challenging.

**Comment by mnalis** [comment]
I've created PR for `support` tag at https://github.com/openstreetmap/id-tagging-schema/pull/1005

---

As for `post:*`, you might be correct there @gena01. I'm not an expert there, but I think `post` field in https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/letter_box.json **_should be_** expanded to list of keys defined in https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/post.json 

That `post` field expansion: 

- seems to work correctly for example in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) which uses `id-tagging-schema` (via [osmfeatures](https://github.com/westnordost/osmfeatures)) , showing **all** those `post:*` keys
- It  also seems to work in iD editor (although it seems to offer only 5 out of two dozen `post:*` keys?!)
- However, EveryDoor 3.1 does not seem to expand that `post` field at all in `amenity=letter_box`, but it is lost completely. It is unfortunately beyond me why (could be me missing something, but perhaps it might also be EveryDoor bug?)

**Comment by Zverik** [comment]
Every Door currently filters out fields with the `address` type, hence no `post:*=*`. Given it handles addresses differently, it may be tricky to implement. I'll let this hang around.

**Comment by Zverik** [comment]
Done in 4.0.

**Comment by mnalis** [comment]
Just an note that   `support` & `colour` tags have been added to `amenity=letter_box` in https://github.com/openstreetmap/id-tagging-schema/pull/1005#event-11261293394

So hopefully next Everydoor build should be able to specify those, if I understand correctly.
