### ISSUE TITLE
Can not choose `amenity=music_venue`

### ISSUE THREAD

**Issue by pred2k** [Zverik/every_door#634]
Hi, when i'm creating or editing POI's i can not choose `amenity=music_venue`.
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmusic_venue

**Comment by mnalis** [comment]
Every Door uses [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema) for its presets, so it should be implemented there, after which it will be picked up by EveryDoor automatically (on next release).

There seems to be issue already opened about that at https://github.com/openstreetmap/id-tagging-schema/issues/8, so you may want to add your voice there, @pred2k
