### ISSUE TITLE
Enable type=roadheight preset fields

### ISSUE THREAD

**Issue by andreadecorte** [Zverik/every_door#643]
Hello, I can see the maxheight field in the [Presets](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/barrier/height_restrictor.json)  but in Every Door the field is missing

![Screenshot_20230926_123207](https://github.com/Zverik/every_door/assets/104198/29889e6b-dd90-4382-8207-4620b3d13308)

**Comment by Zverik** [comment]
Hmm, indeed. I chose to ignore `roadheight` fields, but frankly there should be no problem enabling those.
[Re: maxheight](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/maxheight.json)

**Comment by Zverik** [comment]
Fixed in 3.2.
