### ISSUE TITLE
Add information if cafe has power outlets for laptops?

### ISSUE THREAD

**Issue by DavidKarlas** [Zverik/every_door#646]
I saw https://news.ycombinator.com/item?id=37721320 and wondered if OSM/EveryDoor has information about electrical outlets being available to customers.
Quick check it seem OSM doesn't have a tag for this...

I hope it is OK to open issue here :)

**Comment by Zverik** [comment]
We have got the [power_supply=yes/no](https://wiki.openstreetmap.org/wiki/Key:power_supply) tag for this, but mostly focused on campsites. [This page](https://wiki.openstreetmap.org/wiki/Tag:power%3Doutlet) suggests on using this tag for publicly available sockes in cafes too. According to [taginfo](https://taginfo.openstreetmap.org/keys/power_supply#combinations), it is used on 1642 amenities, 136 of which are cafes, restaurants, and pub ([mainly in Japan](https://overpass-turbo.eu/s/1BeY)).

The tag [has its field](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/power_supply.json) in the presets, but used only by `caravan_site`, `camp_site`, and `marina`. Maybe it would make sense to submit a pull request there to add the field to eating places. This editor uses that preset repository for its fields.

**Comment by DavidKarlas** [comment]
Thank you for quick response, I will look into opening PR.
