### ISSUE TITLE
Warn if shop=yes

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#65]
Should maybe also be more prominent

**Comment by Zverik** [comment]
Thing is, we cannot do much about that. E.g. without #66. I'll see what can be done — maybe just higlight the field in red...

**Comment by mfbehrens99** [comment]
I don't think we need a hot fix for that. I just think it should be implemented some time in the future

**Comment by Zverik** [comment]
Now tracked in #354.
