### ISSUE TITLE
Allow to set roof:levels to zero

### ISSUE THREAD

**Issue by arrival-spring** [Zverik/every_door#652]
At the moment you can only set non-zero roof levels, but it is useful to record that a building has no levels in the roof.

**Comment by Zverik** [comment]
Huh. Great idea, completely missed that — and just leaving the tag unfilled for buildings with no roof floors.

**Comment by arrival-spring** [comment]
That's what it is at the moment, you can't (easily) say that a building has no roof levels, so it doesn't get set.

I think it's just adding '0' to the start of this list:

https://github.com/Zverik/every_door/blob/56a6939a312822f20765005abdc04291237fccc0/lib/screens/editor/building.dart#L213

**Comment by Zverik** [comment]
Done in 4.0.
