### ISSUE TITLE
Prioritize preset options over taginfo

### ISSUE THREAD

**Issue by 501Ghost** [Zverik/every_door#656]
When scrolling through "more fields" I noticed that source=BAG comes up as a suggested tag. This tag comes from the Dutch buildings & addresses import and was probably included because it's one of the most common source tags. But since it's an import tag, there is no need for Every Door users to add it to POIs that they map. Please stop suggesting this tag to mappers.

**Comment by deevroman** [comment]
There are many tags like this and more and more tags will be coming. 

And it doesn't seem worth it, because: what `source=` other than `source=survey` can be added via EveryDoor?

**Comment by Zverik** [comment]
Actually I think this might be a good idea to prioritize options mentioned in a preset. I'll try that for 4.1.

**Comment by 501Ghost** [comment]
If you're going to prioritise options, `source=local knowledge` may be a good tag besides `source=survey`.

**Comment by Zverik** [comment]
Here are documented options for `source` that would be prioritized: https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/source.json

**Comment by Zverik** [comment]
Done in 3518beb.
