### ISSUE TITLE
Some fields are not translated?

### ISSUE THREAD

**Issue by matheusgomesms** [Zverik/every_door#657]
[v4]
It seems some fields are not translated, and the translation is not coming from iD presets? PT-BR in EveryDoor is 100% translated on Weblate (by me).

What I can see in English, that should be in PT-BR:

- Room Number
- Postcode
- Elevation (Meters)
- Levels
- mobile

Is this an Every Door mistake or iD Preset? I remember seeing those fields translated on iD, but I might be wrong!

**Comment by Zverik** [comment]
"Room Number" and "Postcode" are indeed not yet translatable. The other three come from presets, I guess.

**Comment by Zverik** [comment]
In 4.1, I've changed Room Number to be taken from presets, and for Postcode, it's pretty hard to make it translatable, since there is no preset for this field alone.

**Comment by matheusgomesms** [comment]
Great! I just checked on Transifex, and it seems all of these fields are available on the iD Presets (although I'm not sure how it can be used on the fields). And I also checked PT-BR translations, those fields were already translated.

**Comment by matheusgomesms** [comment]
Update (which is probably known to you, Ilya, but just to make it easier for future fixes:

What I can see in English, that should be in PT-BR:

Postcode
Elevation (Meters)
Levels

**Comment by Zverik** [comment]
Postcode is still untranslatable, but Levels and Elevation come from presets, there are no such strings in the code.

**Comment by matheusgomesms** [comment]
Don't know then what's the cause, because I checked the Presets translations and it's translated there for ages :(

(you can check in EveryDoor, in all languages have "Elevation" and "Levels")

**Comment by Zverik** [comment]
![levels-elevation-translated](https://github.com/Zverik/every_door/assets/766031/1ce17f09-c99f-4531-9f59-e2ce27253772)

Translated for me (the second and the third line). Are you looking at 5.1-beta2?

**Comment by Zverik** [comment]
![levels-elevation-pt-br](https://github.com/Zverik/every_door/assets/766031/68c51ad4-f148-4467-ae86-ec5cfec58c43)

Actually here's pt-BR locale.

**Comment by matheusgomesms** [comment]
That's odd! iOS here, 5.1-beta2:

![IMG_3239](https://github.com/Zverik/every_door/assets/86851490/55bd0015-7108-4b76-a6e9-1a8f3237cde4)
![20240527_171555391_iOS](https://github.com/Zverik/every_door/assets/86851490/c0dd34c9-f8db-465b-b31d-749a929ee82f)

**Comment by Zverik** [comment]
Oh! I see, this is related to references inside the fields files. And I guess this is a bug. I'll see what I can do.

**Comment by Zverik** [comment]
Fixed in 5.1, including the postcode!
