### ISSUE TITLE
Add preset aliases to the search index

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#658]
When I add a POI and search for "barber", it only finds "Hairdresser Supply Store" (`shop=hairdresser_supply`) but not "Hairdresser" (`shop=hairdresser`). I was wondering if it would be possible to tweak the code to find both for this value.

I browsed through the code and I thought maybe it's related to the id-tagging-schema, but searching for a barber in iD does come up with hairdresser.

**Comment by Zverik** [comment]
Actually, aliases should be used in search, so let's keep this.

**Comment by Zverik** [comment]
Done in 3518beb.
