### ISSUE TITLE
Creation of Duplicate Notes

### ISSUE THREAD

**Issue by kmpoppe** [Zverik/every_door#665]
Albeit in a much smaller scale than other editors, I also found ED creating notes in the same place twice.

These are

1) https://osm.org/note/3949330 and https://osm.org/note/3949331
as well as
2) https://osm.org/note/3949332 and https://osm.org/note/3949333

The notes under 1 where created in the exact same second, the notes under 2 likewise 2 seconds later.

Could https://github.com/Zverik/every_door/blob/ef668b53a54e345ae944faa4ba7f8ccbaf6f8f8a/lib/providers/notes.dart#L256 possibly check to only insert notes into the database awaiting upload when there isn't a note already with the same lat/lon?

**Comment by Zverik** [comment]
Well it doesn't download notes in the area before uploading them. Duplicate notes should be an error indeed. In 5.0 notes process has been reworked — let's see if we get duplicates later.

**Comment by Zverik** [comment]
Closing this because with 5.0 the mechanism is a bit different. We'll see how it goes.

**Comment by mnalis** [comment]
(just to add a reference to https://github.com/streetcomplete/StreetComplete/issues/4853 and https://community.openstreetmap.org/t/potential-note-duplicates-worldwide/9517, as the issue happens in other software too)

**Comment by kmpoppe** [comment]
It would seem, that 5.0 has fixed this issue completely. There are 3,885 Notes on osm that had been created by EveryDoor, the newest being 4342428 from 20.07.2024 17:07 UTC.

The newest ED duplicates that were created are 4142136 and 4142137 from 06.03.2024 17:11 UTC - Even though they are "only" in the listing because they're on the exact coordinate, the contents is different.

I think ED has left behind this issue for good, thanks @Zverik !
