### ISSUE TITLE
Snap traffic signals to highways

### ISSUE THREAD

**Issue by gdabski** [Zverik/every_door#666]
Consider introducing snapping of newly-added [highway=traffic_signals](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals) to highways. Such snapping is already done for [gates and other barriers](#541). Doing the same for traffic lights is even less error-prone, because the chance someone would not want to have traffic signals snapped is much thinner.

**Comment by Zverik** [comment]
It would require snapping to intersections — which is what #125 is about.

**Comment by mnalis** [comment]
Do note however that some cases of [highway=traffic_signals](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals) are **not** mapped on intersections (see e.g. [Tag all incoming ways](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Tag_all_incoming_ways)  or [Tagging also cycleway traffic signals](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Tagging_also_cycleway_traffic_signals)  sections for examples)

**Comment by gdabski** [comment]
Thanks @mnalis , in my area they are actually hardly ever mapped on intersections and in my case I was also trying to put them at the stopping position on incoming ways. But I of course see the challenge associated with the other approach.
