### ISSUE TITLE
Amenity age warning is not displayed

### ISSUE THREAD

**Issue by ray66** [Zverik/every_door#667]
Version: 4.0.0
Device: Xiaomi Redmi Note 10 Pro
OS: MIUI 13.0.16/ Android 12

When editing a POI that has been created many years ago, a message "Amenity  is x years old" should appear below the map. This is not the case after switching from the main screen to the edit screen. The message only appears after the "raw tags" window is opened and closed.

**Comment by Zverik** [comment]
Indeed it isn't. But it appears when you change any field.

**Comment by Zverik** [comment]
Done in 3518beb.
