### ISSUE TITLE
Description field auto-capitalizes every word

### ISSUE THREAD

**Issue by bdwz-osm** [Zverik/every_door#669]
When using the default AOSP keyboard (LOS 20, A13) to fill in text fields on the latest Every Door F-Droid build, pressing space automatically engages Shift for the first character of each word on _all_ text fields, including the fields for the `description`, `note`, and `fixme` keys, where sentences are commonly written. It would be good for usability if these keys were excluded from per-word auto-capitalization, and instead auto-capitalized per sentence.

This might need to be implemented for the multi-language tags as well, i.e. `description:en`, `description:es`, etc.

**Comment by mnalis** [comment]
Yes, I guess it should apply only to `name`, `name:en` and similar fields. 

Possibly related to changes explained in this issue: https://github.com/Zverik/every_door/issues/659 (but app-designated capitalization _"luckily"_ does not work _at all_ in my keyboard/android combo mentioned there, so I cannot confirm nor deny this behaviour reported here)

**Comment by Zverik** [comment]
Absolutely, this is a bug and I hate it.

**Comment by Zverik** [comment]
Done in 4.1.
