### ISSUE TITLE
Android app version 4.1 is still manifested as 4.0.x

### ISSUE THREAD

**Issue by reinhart1010** [Zverik/every_door#674]
Hi, I'm recently noticed that [version 4.1](https://github.com/Zverik/every_door/releases/tag/v4.1) has just been released for Android. However, when I'm preparing to submit it to Huawei AppGallery, the website still detects this package as version 4.0.99.

![image](https://github.com/Zverik/every_door/assets/17312341/bfbcb0e7-149c-4aac-922f-3b131a42640f)

**Comment by Zverik** [comment]
Hi Reinhart, sorry for that hiccup. I've updated the apk in the release, now it's 4.1.0 proper.

**Comment by reinhart1010** [comment]
I've uploaded the new APK to AppGallery
