### ISSUE TITLE
Add support for aeroway=gate

### ISSUE THREAD

**Issue by osmuser63783** [Zverik/every_door#677]
Please consider adding support for aeroway=gate e.g. in the "tree view".

At the moment I can add a gate (like any other unsupported tag) by creating a new node using a different preset and manually changing the tags. It'll then appear in the tree view as an airport gate and I can upload it. But I can't select an existing airport gate and move or delete it.

(Also thanks for developing this fantastic editor!)

**Comment by Zverik** [comment]
Good idea! I wonder if those should be snapped to building contours, like entrances.

**Comment by osmuser63783** [comment]
Not sure. I've seen them placed just inside the terminal building, on the outline, and just outside the building.

**Comment by Zverik** [comment]
Okay, should be available in micromapping mode (I know, but definitely not an amenity) in 5.0.
