### ISSUE TITLE
Add some more de-facto changeset tags

### ISSUE THREAD

**Issue by coolultra1** [Zverik/every_door#679]
As almost all modern editors (basically all except for JOSM) add at least some of them, I think Every Door should also add the following changeset tags:

- [`imagery_used`](https://wiki.openstreetmap.org/wiki/Key:imagery_used)
- [`locale`](https://wiki.openstreetmap.org/wiki/Key:locale)
- `changesets`
- **maybe** [`source`](https://wiki.openstreetmap.org/wiki/Key:source)`=survey`

**Comment by Zverik** [comment]
I see why you might want those tags on changesets, though I don't feel they are necessary. I prefer to add the absolute minimum needed for understanding a change. If we're putting the same tag on all changesets, that would be as good as not using it.

Every Door is an editor for field surveys, so all four tags would be either redundant or irrelevant.

**Comment by mnalis** [comment]
> Every Door is an editor for field surveys, so all four tags would be either redundant or irrelevant.

- Well, even if it is intended for field surveys, it _**does**_ allow user to use satellite/aerial/other imagery, and those _**do**_ have different offset which would affect the positioning of the elements, so I think it would be **useful to  record [imagery_used](https://wiki.openstreetmap.org/wiki/Key:imagery_used)** for all imagery that user has viewed in that session (it should not be too hard either: append current satellite imagery name to the list [if not already present] every time user changes the display to satellite, and on upload set the `imagery_used` changeset tag and clear the list).

- [locale](https://wiki.openstreetmap.org/wiki/Key:locale) would be even easier to set, but I have not really found that tag useful, so unless someone has use case how it would be useful, probably not worth the effort.

- And I completely agree with  **not** setting `source=survey` **unconditionally** -- even if EveryDoor is intended to be used on the ground by the author, it is not always used like that, and as you say it would not make sense to set it on all changesets... 
  While it _would be quite useful_ if it was selectively set (e.g. only set `source=survey` tag if every modified/added node in that session has been located within 100m of currently detected GPS location), I get that this would likely be too much work.
