### ISSUE TITLE
I managed to rotate a building

### ISSUE THREAD

**Issue by j13m126** [Zverik/every_door#680]
It seems I managed to rotate this [building](https://www.openstreetmap.org/way/250844489) with Every Door in changeset [132372976](https://www.openstreetmap.org/changeset/132372976) 9 months ago. I was kindly notified about it today. This is the only building affected in the changeset, I looked through all ways and relations.
Has this happened before? I couldn't find a similar issue, open or closed. Or did I miss anything?
This must have been on my Pixel 6 running Android 13

![grafik](https://github.com/Zverik/every_door/assets/7961926/ccef72ab-7c91-4286-b4e5-350ce647c770)

**Comment by Zverik** [comment]
Thanks for the investigation guys :)
