### ISSUE TITLE
Some way to filter by floor level

### ISSUE THREAD

**Issue by dbdean** [Zverik/every_door#683]
When adding shops in multi-level shopping centres, it would be good to have some way to only show shops on a certain level, so that is would be easier to tell what has already been mapped, what hasn't and to select shops to edit details about them.

I don't think this is available in the app at the moment, or if it is I can't seem to work out how to do it.

**Comment by Zverik** [comment]
David, try the filter icon at the [top right](https://user-images.githubusercontent.com/25514836/183449814-38caa70f-9fb3-4ccb-b188-d13251b86352.jpg). Filtering by floor is more effective when there are addresses as well.

**Comment by dbdean** [comment]
I don't have a filter icon. How do I get it to display?

![image](https://github.com/Zverik/every_door/assets/12725310/d646b2dd-3fe4-4cce-85b6-cc8dec53b822)

I'm on Version 4.1 of EveryDoor on Android 14

**Comment by dbdean** [comment]
ok - found it - it only shows for shops. Thanks.
