### ISSUE TITLE
Handle Instagram links with query string

### ISSUE THREAD

**Issue by Danysan1** [Zverik/every_door#685]
Currently Instagram links in these formats are handled:
- `openstreetmap`
- `instagram/openstreetmap`
- `instagram.com/openstreetmap`
- https://www.instagram.com/openstreetmap
- https://www.instagram.com/openstreetmap/

But Instagram links can also come in these formats:
- https://www.instagram.com/openstreetmap?hl=it
- https://www.instagram.com/openstreetmap?igsh=ODA1NTc5OTg5Nw==
- https://www.instagram.com/openstreetmap/?hl=it
- https://www.instagram.com/openstreetmap/?igsh=ODA1NTc5OTg5Nw==

These should be handled as well.

I think this can be achieved by editing the regex in [InstagramProvider](https://github.com/Zverik/every_door/blob/6e55dea2c2a5c41c43082811b68ac326b822069b/lib/fields/helpers/website_fmt.dart#L178):

```diff
- regexp: RegExp(r'(?:instagram(?:\.com)?/)?([^/ ]+)/?$'),
+ regexp: RegExp(r'(?:instagram(?:\.com)?/)?([^/ ?]+)/?(\?[\w=]+)?$'),
```

I compared the regular expressions in regex101:

Before:
![image](https://github.com/Zverik/every_door/assets/8406735/c38eebc7-7404-4dca-bdba-90d543d7f5c1)

After:
![image](https://github.com/Zverik/every_door/assets/8406735/d92c09c3-3a74-404e-87c4-ade75da82269)

**Comment by Zverik** [comment]
Thanks, extended the regexp.
