### ISSUE TITLE
Automatically remove disused: when inactive shop is edited

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#69]
Not sure about this one. Sometimes I delete tags from inactive shops but usually when I edit a shop it is active again

The app could also ask you if ... is active again

**Comment by Zverik** [comment]
I don't see how to make it non-intrusive and non-unexpected. There is a button to remove the prefix. But I know of some cases when I edited data for a disused amenity (owners of a cafe asked me to update some data before opening).

**Comment by mfbehrens99** [comment]
The only correct way would be to have a popup when saving the amenity. "You changed an inactive amenity. Do you want to mark it active again?"

I just forgot to mark them as active three times today and I think in most cases (with some exceptions) you only edit amenities if they are active again

**Comment by Zverik** [comment]
Done in 0.1.4.
