### ISSUE TITLE
addr:city/country fields

### ISSUE THREAD

**Issue by bloerwald** [Zverik/every_door#690]
Apparently at least in Germany it is considered best practice to add `addr:postcode`, `addr:city` and `addr:country`. Currently only `addr:postcode` is easily accessible and the others aren't even shown in more, just the raw tag editor.

It would be nice to have them visible, maybe optionally, or in the expanded view at least.

Since they are so repetitive, I'd of course love to see a helper feature to pre-populate them when setting street/housenumber with the last entered data or closest nearby addr:* or from a surrounding relation or with the same selector used for street names. Having them visible at all would be a good start though.

**Comment by Zverik** [comment]
I'm strictly against setting `addr:country` tags on anything in OSM. It is a geospatial database, and you can get the country from geometry and administrative borders.

Not even mentioning disputed borders when such a tag would spark edit wars.

On the hyper-local scale, the same could be said for `addr:city`. If it's a city with roads, just draw the boundary. And when the town is so small that amenities are addressed by the place name, editor does set it with `addr:place`.

Finally, we should use tags that can be validated on the ground. I was against the postcode too, but people convinced me. And that's as far as I'm willing to go :)
