### ISSUE TITLE
add tiktok to contact presets

### ISSUE THREAD

**Issue by teacupmaps** [Zverik/every_door#694]
![20240207_202340](https://github.com/Zverik/every_door/assets/158172547/98d313b3-1a67-40d3-81fe-a4d05c02b31d)

**Comment by hehehe92** [comment]
please add tiktok tags, it's on the wiki https://wiki.openstreetmap.org/wiki/Key:contact:*

**Comment by Zverik** [comment]
I have added values that had more than 5k uses, and tiktok has like 800. But then, why not.
