### ISSUE TITLE
Changes to notes don't always seem to survive power off

### ISSUE THREAD

**Issue by osmuser63783** [Zverik/every_door#695]
How to reproduce
1. Walk around, adding POIs, resolving notes
2. Run out of battery
3. Recharge your device, then upload changes

On my phone (Android 12, Every Door 4.1) it's now happened twice to me that changes to POIs were uploaded but changes to notes had gone. I *think* this is because my battery had run out. It doesn't happen when I just reboot the device normally.

**Comment by danieldegroot2** [comment]
Sidenote: iD editor also does not cache draft notes/comments yet, unlike map data. See https://github.com/openstreetmap/iD/issues/6905 .

**Comment by Zverik** [comment]
I looked at this and I feel like the issue was not with the power off, but with the way comments to OSM notes were handled. In 5.0 it's probably fixed, let's see how it goes. You can already get a debug build from github actions.

**Comment by osmuser63783** [comment]
Thank you! I'll wait for the update then report back if it still happens.
