### ISSUE TITLE
add hair removal tag

### ISSUE THREAD

**Issue by teacupmaps** [Zverik/every_door#696]
https://wiki.openstreetmap.org/wiki/Key:beauty please

**Comment by gdabski** [comment]
I'm pretty sure it's there :thinking:

**Comment by deevroman** [comment]
You can do this:
<img width=33% src="https://github.com/Zverik/every_door/assets/25708359/2402131e-236d-4cc6-9a11-06318e0e60f2">

If you want this to appear in the search: https://github.com/Zverik/every_door/?tab=readme-ov-file#presets-and-translations
