### ISSUE TITLE
OAuth not working

### ISSUE THREAD

**Issue by davidpnewton** [Zverik/every_door#703]
OAuth authentication to OSM is not working. The following error message is produced:

![Screenshot_20240330_102041](https://github.com/Zverik/every_door/assets/74616419/ce85e92a-971c-4fe1-86a4-73ba3f2bc711)

Android 14, Galaxy A55, Everydoor 4 1.0

**Comment by Zverik** [comment]
Duplicate of #533. Still no idea how to fix this :(
