### ISSUE TITLE
Black pin marker is hard to see against some aerial imagery

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#714]
I'd like to suggest an improvement: changing the color/outline of the map marker to show up against all backgrounds.

On the Carto layer, the black pin stands out, but some parts of aerial imagery are very dark or black, and the pin disappears (especially when mapping in bright sun).

I would suggest either a change to the whole marker to a new color (red?), a thin outline of a bright color, or maybe some code to invert the color of the background where the pin is (but that might look awful...). 

Example image of black on dark background:
![Screenshot_20240427-081030](https://github.com/Zverik/every_door/assets/7786285/75abc265-51f2-4190-87d9-cc4f9bd88a51)

**Comment by Zverik** [comment]
In 5.0 it will have inverted background layer colors, so a bit easier to see — but not on gray spots alas.
