### ISSUE TITLE
Thoughts on usability and bugs in Drawing Mode (5.0-beta 1)

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#719]
Loving the new drawing mode, but I thought I'd let you know of a few things I've discovered while mapping.

First, a bug: the location dot doesn't seem to update position in Notes Mode unless the screen is tapped. This is true whether drawing mode is locked or not. Location refreshes when you tap buttons or draw a line. 

Also, probably related, tapping to change to imagery vs. OSM map in the same way doesn't refresh the background unless the map is tapped.

Secondly, usability:

- I think it might be better to have drawing mode locked at the start, because the expectation when you move to that mode is that you can drag the map around like the other modes. Maybe instead of a separate lock icon, you could put a tiny lock on whatever drawing icon is most recently used. So at app start, it would be the default drawing method (white lines), but with a tiny lock in the corner of the button, then you tap it to unlock it (tap to go into the drawing options, then unlock, or maybe long hold on the button as another option?).
- The erasing icon doesn't intuitively suggest erasing to me (other than color). It looks like a paintbrush, which to me suggests drawing wider lines. Maybe a change to an eraser icon would work? Not sure on regional differences of understanding, though.
- I think it would be good to have the menu and location buttons on the screen during drawing mode.
- Long shot idea: I think it would be interesting to have a method where instead of drawing with your finger, you could drag the map and draw with the central pin marker. It might be more precise, but I'm not sure how you'd stop and start the drawing. Could be cool, though.

**Comment by Zverik** [comment]
All good comments, thank you for caring!

* I experienced the same with location refreshes, but background layer is refreshed immediately for me. Weird.
* On locking: I see how it can be frustrating. For start, I wanted to make this a part of discoverability: you try to drag the map, and suddenly you're drawing. Ah, that's how this mode works! So maybe I'll adjust it for 5.1 release, idk.
* Absolutely agreed on the eraser icon. Could you suggest anything from [this](https://fonts.google.com/icons) or [this](https://lineicons.com/icons) set?
* The idea was to give as much space for drawing as possible. These corner buttons don't just take their small areas, they visually chop off three borders on the screen. At first I wanted to do even without bottom buttons, but that would complicate things. Hence the buttons are enabled only when locked. On the other hand, menu button is rarely needed, and the location button just centers you on yourself, not that important too.
* Nice idea! I agree it would be more precise. But with finger drawing, there's also this feeling of power over the map, and that you don't have to do perfect, just good enough. If we aim at precision, then why not add ways to OSM directly?

**Comment by pkoby** [comment]
Sorry for the slow response on this.

- I checked the background refresh bug again, and I was able to reproduce it only sometimes. Click the map button to change to imagery, pinch to zoom in a bit, click it to change to Carto, it might not refresh. I _think_ it might only occur when you've zoomed past z19 for Carto. I cannot reproduce in v4.1.
- In terms of locking, I understand your reasoning, but from a completely new user perspective, there's no indication of how to stop it from drawing. The undo button pops up when you draw, which nudges the user to the left side, so maybe they'd pick the drawing button, but there's also the + button, so maybe that helps too? This needs more user input than just me.
- I like the second "eraser" in the lineicons.com (when you search for eraser, it's the more bold lined one). I was actually picturing something like [this](https://creazilla-store.fra1.digitaloceanspaces.com/icons/3215028/eraser-icon-md.png), maybe without the line on the bottom (basically the two-tone aspect is what suggests eraser to me).

**Comment by Zverik** [comment]
Yay I found the reason for the GPS location not updating! Also I found an icon for eraser, but not that one, because I posted a wrong link for Line Icons (I use [icons8](https://icons8.com/line-awesome)). Marking the rest of this for 5.1.

**Comment by pandadeepimpact** [comment]
> In terms of locking, I understand your reasoning, but from a completely new user perspective, there's no indication of how to stop it from drawing. The undo button pops up when you draw, which nudges the user to the left side, so maybe they'd pick the drawing button, but there's also the + button, so maybe that helps too? This needs more user input than just me.

I agree with this. I find the lock button unintuitive, where the only way to know what it does is trying it out (or reading this issue). How about replacing it with a hand icon commonly used for panning, where you grab a part of the screen then move it, as the lock works in a similar way?

**Comment by pandadeepimpact** [comment]
> Nice idea! I agree it would be more precise. But with finger drawing, there's also this feeling of power over the map, and that you don't have to do perfect, just good enough. If we aim at precision, then why not add ways to OSM directly?

Good point... but what happens to the drawn features after uploading? Please forgive my ignorance as I've never seen a note containing a drawing.

**Comment by Zverik** [comment]
So from above I see two things to fix: 1) locking mode, 2) imagery update. With 5.1, I've fixed the former, and for now idk how to do 2 — possibly related to upstream issues. So I guess I'm closing this.

@pandadeepimpact see this wiki page: https://wiki.openstreetmap.org/wiki/GeoScribble
