### ISSUE TITLE
Opening hours editor should ask for time by default

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#72]
Should ask for times ba default instead of assuming full day open. Then add a "full day open"-button. 99% of the shops are not open 24 hours a day

**Comment by Zverik** [comment]
I understand the reasoning, but no. It won't be a good UI. This one extra tap is needed to ease a user into the UI switch. Also many people follow the order "weekdays → hours", and your suggestion reverses it, adding for an unnecessary confusion that would take more time than tapping the switch.

**Comment by mfbehrens99** [comment]
How about getting rid of any 24 hours and just letting the user set the opening time from 0:00 to 24:00?
