### ISSUE TITLE
[iOS] Messages displayed under bezel

### ISSUE THREAD

**Issue by matheusgomesms** [Zverik/every_door#726]
Not sure if this happens in other devices, but the newest iPhones (some 14 models and all 15 models) have this pill-shaped camera island (bezel). EveryDoor doesn't respect that, so all messages (such as Download Successful etc) are cut. I can't show properly because screenshot doesn't show the camera island hehe, but even though you can see the message is fairly close to the clock/battery bar.

In Settings screens there is no problem at all, just when these messages pop up.

You're probably well aware of the details, but maybe these help: this is something related to the safe areas and superview? https://uxdesign.cc/how-does-understanding-superview-and-safe-area-make-you-a-better-designer-601dc7117aff

OrganicMaps fixed some of these problems, eg: https://github.com/organicmaps/organicmaps/pull/7314

iOS docs: https://developer.apple.com/design/human-interface-guidelines/layout

Raw idea: keep the green tab, but add some pixels above the message.

![IMG_3122](https://github.com/Zverik/every_door/assets/86851490/a1e63d9b-e103-4c11-9286-cee5df8e9b47)

**Comment by matheusgomesms** [comment]
PS.: latest v4 official App Store version here. Didn't test v5 yet, so not sure if this persists.

**Comment by Zverik** [comment]
Will be fixed in 5.1.
