### ISSUE TITLE
Add "origin" field on supermarkets and convenience stores

### ISSUE THREAD

**Issue by pandadeepimpact** [Zverik/every_door#728]
I've seen an increasing number of supermarkets and convenience stores that specialize in selling imported products from specific countries, and tagging these countries can help people searching for specific products, such as Korean noodles or Chinese spices.

I suggest implementing a list similar to how `cuisine` is handled, where I can press the `...` button and choose from a list of countries instead of needing to type them manually (which is prone to typos and inconsistencies). Furthermore, I suggest including `origin` on the main list of fields (rather than under "more fields"), as it's an important consideration on whether to enter a supermarket or convenience store in the first place (e.g., no point searching for cheese in a Korean supermarket).

**Comment by Zverik** [comment]
All presets are managed in the repo shared with iD, so I think you should take this there: https://github.com/openstreetmap/id-tagging-schema/issues/623

**Comment by Zverik** [comment]
The entrance issue is about a different mode, buildings & doors, where there's a popup editor with a different set of fields.
