### ISSUE TITLE
[iOS] White screen when adding nodes, addresses, anything

### ISSUE THREAD

**Issue by matheusgomesms** [Zverik/every_door#733]
Possible bug: when adding a note, the screen gets white, making it almost impossible to see where to insert the new note. Happens this within or not GeoScribble mode.

(I was moving the screen behind, very hard to see)

https://github.com/Zverik/every_door/assets/86851490/a9911791-1b2c-4cf4-9280-12d4b74413fb

**Comment by bcheronn** [comment]
Having the same issue when adding/editing any node, making it impossible to add/move a node (ED 5.0, iOS 17.4.1)

**Comment by matheusgomesms** [comment]
Updated the title, since it spans not only nodes, but anything actually.

**Comment by ianthetechie** [comment]
Yeah, agreed. Same for me in 5.0.

![image](https://github.com/Zverik/every_door/assets/2140440/92e7f407-31c9-4ae4-8114-59cab09b0851)

**Comment by Zverik** [comment]
Riiiight, so the screen is almost white, but not entirely: it's like a 90% white layer on top of the map. I don't see a reason [in the code](https://github.com/Zverik/every_door/blob/main/lib/screens/editor/map_chooser.dart), so... Idk for now, will try to debug.

**Comment by kschepkin** [comment]
The version I built from source and installed on my iPhone is missing the above problem. As proof, I attach a video showing the AppStore version of the app and then the debug version I built from source using the attached instructions.

https://github.com/Zverik/every_door/assets/2526575/f524e6d8-d915-4757-8c70-169e3616e652

**Comment by Zverik** [comment]
Everyone, please test the latest beta through TestFlight: https://testflight.apple.com/join/5138nQCq

I really hope the white map issue went away. On my phone (iPhone 6s) I haven't seen it in 5.0, so I can't really say whether it was fixed.

**Comment by ianthetechie** [comment]
@Zverik it works for me :)

**Comment by matheusgomesms** [comment]
Also works for me (14 Pro).

**Comment by Zverik** [comment]
Great, thanks! Considering this fixed then.
