### ISSUE TITLE
Be much more careful about not removing addresses when removing POIs

### ISSUE THREAD

**Issue by zyphlar** [Zverik/every_door#734]
Users online are reporting that they prefer to map addresses and amenities separately because some apps like Every Door will too easily let people mark an amenity as no longer here, thus deleting the entire node and its address, without realizing. Changing the language or introducing an additional step would help people communicate the status more accurately and avoid this issue. Maybe "this location is demolished" vs "this amenity is closed", or "no longer here" -> "the address still exists" / "the address is also gone"

**Comment by matheusgomesms** [comment]
I highly second that. Especially in countries/places where address came imported as nodes, mappers have the tendency to map POIs directly in that node. Not an EveryDoor exclusive problem, but definitely a problem to be taken care of when deleting.

**Comment by gdabski** [comment]
On the other hand, EveryDoor encourages users to add the address (street and hose number, at least) to every POI, even if there is a separate address node somewhere or the address is placed on the building outline. In such a case, deleting the POI should not result in the address tags remaining on the POI node.

**Comment by Zverik** [comment]
Sure, I ask a user about that only when the address is unique. Done for 5.1.

**Comment by zyphlar** [comment]
@Zverik when you say unique, does that include unique for sub-addresses like `addr:unit` etc? Or just unique for the street and housenumber?

**Comment by Zverik** [comment]
@zyphlar all `addr:` tags are considered, see [the list](https://github.com/Zverik/every_door/blob/main/lib/models/address.dart#L45).
