### ISSUE TITLE
Detailed position mode fades background map to almost unreadable 

### ISSUE THREAD

**Issue by donaldrnoble** [Zverik/every_door#742]
In v5.0 if I use the detailed positioning mode, eg to move a poi or add a note, then the background is faded to the point it is unusable. 

The same thing happens with satellite imagery or OSM tiles background, and seems to have changed with the recent release 5.0 of Every Door. 

I’m using iOS 17.4.1 (21E236) on an iPhone 13 mini, let me know if you need more info. 

![IMG_4966](https://github.com/Zverik/every_door/assets/6844639/df5b5c85-7695-4736-b32c-b821093bb5b9)

**Comment by Zverik** [comment]
Duplicate of #733, hopefully resolved in 5.1. Please test with the beta build, linked there :)

**Comment by donaldrnoble** [comment]
Sorry, I tried searching but didn’t see the closed issue. It works for me in the TestFlight beta
