### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Zverik/every_door#744]
as QR Scanner depends on proprietary Google libs

ref: https://github.com/Zverik/every_door/commit/154ebcefff9eba3a05b1f3b449fce45f502e8678

ref: https://github.com/juliansteenbakker/mobile_scanner/blob/v5.1.1/android/build.gradle#L70-L73

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d80c43804b40d4d8dba8244037db8a730d9c26e3

**Comment by licaon-kter** [comment]
https://github.com/microg/GmsCore/issues/2018 apparently microG 0.3.1 and later might have the libs to replace the Google stuff, but not sure anyone tried

**Comment by Zverik** [comment]
QR code scanning is not that important to find workarounds, so I'll look into disabling it for f-droid.

**Comment by mnalis** [comment]
@Zverik F-droid MR complains with `Merge blocked: Merge request must be rebased, because a fast-forward merge is not possible.`

**Comment by licaon-kter** [comment]
That's a Gitlab thing, F-Droid contribs can rebase as needed.

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/10488057791 umm? About?
