### ISSUE TITLE
Resolve redirects in QR codes

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#746]
Many QR codes are using URL shorteners. Try to resolve them.

**Comment by coolultra1** [comment]
Altough websites might also redirect to sub-pages of themselves sometimes. (e.g. redirecting from / to /index.html or even to temporary error pages)

So we should probably only change the URL if the one redirected to is of a different domain. (Or have an index of URL shortener's domains, altough that's unrealistic.)

**Comment by mnalis** [comment]
quite a few redirects might be based on user-agent (e.g. separate pages for mobile agents), or change redirect target based on other data (language setting / cookies etc). And sometimes underlying website changes name (esp. if site doesn't own their domain, but redirect to some "free website" hosting which changes in a year or so, but some shorteners can be updated to link to new destination).

What is unrolling URL shorteners attempting to accomplish? 
Guard against URL shortener going out of the business, or ...? 
(That should be weighted against problems that unrolling might bring...)

**Comment by mxxcon** [comment]
> What is unrolling URL shorteners attempting to accomplish?
> Guard against URL shortener going out of the business, or ...?

I consider it similar to Google analytics tracking url parameters.
And URL shortners are relevant where URL length matters. In an app where you tap on it the length doesn't matter and shortners just add another point of failure.

**Comment by Zverik** [comment]
Done in 5.2.
