### ISSUE TITLE
In-app-search for wikidata IDs

### ISSUE THREAD

**Issue by hejjoe** [Zverik/every_door#750]
When adding memorials, graves or similar items it could be very helpful to look up the right wikidata IDs for keys like [subject:wikidata](https://wiki.openstreetmap.org/wiki/Key:subject:wikidata), [buried:wikidata ](https://wiki.openstreetmap.org/wiki/Key:buried:wikidata) or [artist:wikidata](https://wiki.openstreetmap.org/wiki/Key:buried:wikidata) within the app. Otherwise the IDs has to be search in a separate browser app. This in-app search might be done with the [wikidata REST api](https://www.wikidata.org/wiki/Wikidata:REST_API) and/or [wikidata api tools](https://www.wikidata.org/wiki/Wikidata:Tools/For_programmers).

**Comment by mnalis** [comment]
That would be nice, but where do you see those `*:wikidata` fields even offered? 

I tried adding both memorial and grave, and they're not even offered (I'm only offered `wikimedia_commons` field) (EveryDoor 5.1 on Android)

**Comment by hejjoe** [comment]
If you want to add those *:wikidata field right now, you have to go this way by hand. It is a bit laborious. (iOS 5.1, german version)

![image](https://github.com/Zverik/every_door/assets/9425894/a189c36f-8f61-4da0-9283-e1ce89fbbfc0)

![image](https://github.com/Zverik/every_door/assets/9425894/8734c2e0-f0c3-414e-b1d5-7740ebbb801e)

**Comment by Zverik** [comment]
Sorry, but wikidata goes against multiple things this editor stands for. Mainly, that it's for live surveying (and there is no wikidata ids in the field), and should work offline (which wikidata doesn't). Wikidata calls for its own editor I guess.
