### ISSUE TITLE
[Request] Add support for Waterway Dam

### ISSUE THREAD

**Issue by Coehill** [Zverik/every_door#755]
waterway=dam would be a useful addition for those traveling in canoes, kayaks, boats, etc.

**Comment by mnalis** [comment]
Can you specify what seems to be the problem? I seem to have the option to add `waterway=dam` in EveryDoor 5.1 (Android)

**Comment by Coehill** [comment]
Relevant code:
https://github.com/Zverik/every_door/blob/ed9bf4c47548920ac668be57484dc91ece6612a3/lib/helpers/poi_warnings.dart#L63

https://github.com/Zverik/every_door/blob/ed9bf4c47548920ac668be57484dc91ece6612a3/lib/helpers/good_tags.dart#L267

I think it just needs dam to be added in an if statement in good_tags.

**Comment by mnalis** [comment]
But [waterway=dam](https://wiki.openstreetmap.org/wiki/Tag:waterway%3Ddam) should snap on `waterway` ways, though, right? I'm not sure if just adding to `good_tags` is going to do that...

**Comment by Zverik** [comment]
This is actually sensible. 5.2 will support waterway features, and will snap most of them to nearby waterways.
