### ISSUE TITLE
Undo in Draw Mode confusingly only affects lines, not points

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#757]
In Draw Mode, you can add lines, or you can hit the + button to add points with text. Intuitively, I expect that hitting the Undo button after adding a point would then remove the point. Instead, it removes the last drawn line, which might have been awhile before and off-screen.

I was wondering if it would be possible for the Undo button to affect the points as well, because I've hit the button a few times expecting the point to disappear, then had to go find where I'd drawn lines and redraw them. Alternatively, could there be a redo button?

**Comment by Zverik** [comment]
Fixed in 5.2.
