### ISSUE TITLE
Search by lat lon

### ISSUE THREAD

**Issue by mariush444** [Zverik/every_door#759]
I can't find anywhere, so probably it doesn't exist.

I would like to find a place on map by typing lat lon.
Moving/scrolling map is often not useful/ergonomic.

**Comment by mnalis** [comment]
- (partially) related idea: https://github.com/Zverik/every_door/issues/387

**Comment by deevroman** [comment]
and https://github.com/Zverik/every_door/issues/281

**Comment by mariush444** [comment]
No problem, I have stoped to use the app in meantime.
