### ISSUE TITLE
Add memorial=ghost_bike

### ISSUE THREAD

**Issue by Coehill** [Zverik/every_door#764]
https://wiki.openstreetmap.org/wiki/Tag:memorial=ghost_bike

**Comment by mnalis** [comment]
I'm note sure if those are implemented via [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/memorial.json) repository, or  via [Taginfo popularity](https://taginfo.openstreetmap.org/tags/memorial=ghost_bike#overview), or combination of both (I _think_ it is combination of both).

So I've made a PR at https://github.com/openstreetmap/id-tagging-schema/pull/1302, feel free to review/like there.

**Comment by Zverik** [comment]
Yup, will appear in 5.2.
