### ISSUE TITLE
Yield & Stop signs don't allow setting direction

### ISSUE THREAD

**Issue by NormPlum** [Zverik/every_door#765]
The [Yield/Give Way](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/highway/give_way.json) and [Stop](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/highway/stop.json) sign presets both have a 'direction' field, but this doesn't show up in Every Door.

I'm not familiar with the code, so not sure if this is intentional or not. But I'd find it useful and desirable to add if possible...

**Comment by Zverik** [comment]
Sorry, but this is intentional. The direction is set as forward/backward for those, relative to the way direction they are in. Every Door does not work with linear ways and has no information on their direction. So editing this kind of data is impossible.
