### ISSUE TITLE
Disable auto-capitalisation and enable glide typing in opening hours text editor

### ISSUE THREAD

**Issue by gdabski** [Zverik/every_door#768]
The configuration of the text box in the opening hours text editor switches the keyboard to uppercase for every new word. This is problematic more often than helpful, because when switching to the text editor mode I usually don't want to add weekday abbreviations, but rather input things such as open-ended periods, or (most commonly) comments. When adding comments I am thus forced to change the case to lowercase before starting each word.

Another drawback of this text box is that I can't use glide typing.

**Comment by Zverik** [comment]
Okay, why not. fixed in 5.2.
