### ISSUE TITLE
Snap murals and clocks to walls

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#771]
In the chat, people asked about clocks, murals, and graffitti. Probably also mosaics?

**Comment by mnalis** [comment]
[amenity=clock](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dclock) is often mounted on a pole though, so it should be snapped to wall _**only**_ if user selected `support=wall_mounted` in fields 

(in fact, I'd wager that **any** object that has `support=wall_mounted` field should be snapped to the wall!)

**Comment by Zverik** [comment]
Okay, did exactly that in 5.2. Thanks @mnalis for the clarification.
