### ISSUE TITLE
Add bicycle traffic counter

### ISSUE THREAD

**Issue by Coehill** [Zverik/every_door#772]
Many cities implement bicycle traffic counters on bike paths and trails.  It is useful to know for bicycle advocacy work, so please include this feature with the name "Bicycle Traffic Counter".  The documentation is here:

Tags:
|         Key         |             Value             |
|:-------------------:|:-----------------------------:|
| man_made            | monitoring_station            | 
| monitoring:bicycle  | yes                           |
| name                | name of counted street        |
| start_date          | year since starting counting  |
| support             | pole                          |
| visibility          | street                        |
| website             | URL of online data state      |

Documentation: https://wiki.openstreetmap.org/wiki/Bicycle

**Comment by Vuizur** [comment]
I think you need to open an issue on https://github.com/openstreetmap/id-tagging-schema, that is where Every Door gets its data from. (And if added, it would also benefit the iD editor.)

**Comment by habi** [comment]
`man_made=monitoring_station` already exists over there: https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/man_made/monitoring_station.json

**Comment by Zverik** [comment]
Yup, just add a monitoring station and set "monitoring" to "bicycle".

**Comment by mnalis** [comment]
I've created PR https://github.com/openstreetmap/id-tagging-schema/pull/1347 there to improve search, as I guess very few people will search for _"monitoring station"_ when they actually want to find _"bicycle counter"_ (at least it would never cross my mind...)
