### ISSUE TITLE
was:bus_stop does not set was:public_transport=platform

### ISSUE THREAD

**Issue by Nielkrokodil** [Zverik/every_door#773]
In [this changeset](https://www.openstreetmap.org/changeset/154453102) I marked a [highway=bus_stop](https://www.openstreetmap.org/node/4921775630) which has been removed permanently to "does not exist" ("existiert nicht" in German). 

Everydoor changed highway=bus_stop to was:highway=bus_stop. 
But it left public_transport=platform as it was. 

I think this is wrong. It should also have changed public_transport=platform to was:public_transport=platform.

**Comment by Zverik** [comment]
I don't think it will be implemented. I loathe how our public transport schema has become this mess when you need to manage TWO main tags simultaneously. Just cannot make myself do this. Use the single `highway=bus_stop` and make life easier for everybody please.
