### ISSUE TITLE
Add self_checkout for shops

### ISSUE THREAD

**Issue by lightonflux** [Zverik/every_door#774]
Wiki: https://wiki.openstreetmap.org/wiki/Key%3Aself_checkout

Taginfo: https://taginfo.openstreetmap.org/keys/self_checkout#overview

![image](https://github.com/user-attachments/assets/5f7804a6-b259-4b99-b8d2-51d6a65b9b11)

While this tag is still somewhat new and rarely used, i think Every Door is the right app to accelerate its adoption.

The tag itself does not lend itself to desktop mapping, as you need to visit a store to check. Nor does it fit StreetComplete  ([see here](https://github.com/streetcomplete/StreetComplete/issues/4693)) as it cannot be tagged from the outside. But it would be a great addition to EveryDoor.

**Comment by Zverik** [comment]
I would be happy to see it in the editor: please create a pull request to https://github.com/openstreetmap/id-tagging-schema to add it to both iD and Every Door.
