### ISSUE TITLE
Maps from Brussels not woking anymore

### ISSUE THREAD

**Issue by bigon** [Zverik/every_door#775]
Hello,

The aerial maps from brussels are not working anymore because the provider (CIRB/Urbis) changed their API

**Comment by mnalis** [comment]
Every Door uses [editor-layer-index](https://github.com/osmlab/editor-layer-index) for its list of satellite/aerial background maps, so I think you should report your issue there

**Comment by bigon** [comment]
Hello,

It seems that it's already fixed in editor-layer-index: https://github.com/osmlab/editor-layer-index/commit/65ea5b0bf274604099e199c36d36633402bc6001

**Comment by mnalis** [comment]
Thanks for checking! Then I think next EveryDoor release (when it happens) should have it included automatically, i.e. via

https://github.com/Zverik/every_door/blob/ed9bf4c47548920ac668be57484dc91ece6612a3/tools/add_imagery.py#L12

**Comment by Zverik** [comment]
Yup, it will.
