### ISSUE TITLE
Tiles need to load when switching to Draw mode, despite being loaded in other modes

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#778]
In any of the three non-Draw modes, if background tiles are loaded, switching between modes keeps the tiles, and the zoom level stays consistent. Switching to Draw mode, though, requires the tiles to have to load again. With bad signal, this is annoying when the other mode has the tiles cached, but then switching makes you wait for them to load slowly another time.

In addition, it's not intuitive that the zoom level would change between these modes either.

Lastly, there's no copyright text in Draw mode, which means that if you're waiting for tiles to load, you can't even tell if you're waiting for the right layer (OSM Carto vs aerial imagery).

**Comment by Zverik** [comment]
Sure, changing zoom is indeed baffling. Removed the change for the notes mode in 5.2.
