### ISSUE TITLE
[Feature Request] Long hold on map button could open imagery menu

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#779]
I would love it if long-holding on the map switcher button would be a shortcut to the background imagery menu. I live in an area that has high-res imagery at a county level, and traveling around means I switch imagery often. This would be a minor benefit, so not urgent, but just an idea.

**Comment by deevroman** [comment]
https://github.com/Zverik/every_door/issues/258

**Comment by pkoby** [comment]
Big oops. Didn't search first. My bad.
