### ISSUE TITLE
Tagging hairdresser=barber

### ISSUE THREAD

**Issue by codeinabox** [Zverik/every_door#780]
Could support for the tag `hairdresser=barber` please be added, it was recently introduced for tagging [barber shops](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhairdresser#Barbers).

Many thanks for creating this app, I use it on a daily basis!

**Comment by deevroman** [comment]
https://github.com/Zverik/every_door#presets-and-translations

There is a preset for this tag, but you need to wait for the next Every Door update
https://github.com/openstreetmap/id-tagging-schema/pull/1165

**Comment by Zverik** [comment]
Yup, will be available in 5.2.
