### ISSUE TITLE
some presets don't show when there's too many with the same name

### ISSUE THREAD

**Issue by UltimateRiff** [Zverik/every_door#781]
might be clearer with a screenshot.

for some brand presets, some of the presets won't show up due to too many presets for the same brand. for example, Circle K `amenity=fuel` doesn't show on a search for "Circle K", even tho it's probably the most common thing to tag with that name. perhaps we should either show more when names/brands match exactly (or nearly exactly) or prioritize more common presets?

![Screenshot_20240918-153540.png](https://github.com/user-attachments/assets/a5d3af84-50c6-429e-b8ac-4b54a2e7b964)

**Comment by mnalis** [comment]
increasing `kMaxNSIPresets` to `4` should help, without messing up too many things I think?

https://github.com/Zverik/every_door/blob/ed9bf4c47548920ac668be57484dc91ece6612a3/lib/constants.dart#L31

**Comment by Zverik** [comment]
Did that in 5.2, thanks.
