### ISSUE TITLE
Cannot delete GeoScribble notes

### ISSUE THREAD

**Issue by bfontaine** [Zverik/every_door#799]
Hello,
I’m using ED 5.2 on iOS 17.7. Unless I’m missing something, I see no way of deleting notes uploaded to GeoScribble; from what I understand, while they are not uploaded you can tap them and then tap "Delete", but once they are uploaded you cannot tap them.

I went to https://geoscribble.osmz.ru/ and clicked on "Mark done" on all of them, but when I delete all downloaded data and download it again, they come back.
How can one delete those?

Edit: also, https://geoscribble.osmz.ru/docs doesn’t mention any route to delete scribbles.

Edit 2: things are becoming a bit messy
![screenshot](https://github.com/user-attachments/assets/dbf64ec7-8555-42d9-85d8-49fa44cfca98)

**Comment by pkoby** [comment]
I also thought marking "done" would delete, but I haven't seen that to be the case. Perhaps it's just a note for yourself/others about whether it needs to be addressed.

The way I take care of it is to go to the lines and notes that I've added and use the eraser tool on them (you have that selected but locked in your screenshot). If I understand correctly, you know about getting rid of the lines. For the notes, use the same tool, but tap on the circle to delete. That works for me even after uploading.

**Comment by Zverik** [comment]
The only way to delete notes currently is to open Every Door, switch to the drawing mode, select the eraser instrument, and tap or draw over scribbles.

Also, notes will disappear from all maps in three months, and from the "latest" WMS layer in three weeks.

**Comment by bfontaine** [comment]
Ah thanks! I tried to use the eraser tool on notes before but I didn’t tap the dots, I just scribbled over the lines and the notes but it worked only with the lines.
