### ISSUE TITLE
Move repository to an organization

### ISSUE THREAD

**Issue by ProgramminCat** [Zverik/every_door#803]
An organization would be significantly beneficial to Every Door because it would allow for easier collaboration and much more. Most of the OSM editors/android clients are under organizations (ex: Organic Maps)

I have registered https://github.com/every-door and can move ownership to you if you would like.

**Comment by Zverik** [comment]
Thanks for registering, but for now Every Door doesn't need a dedicated organization, because it's basically one person doing work in a single repo. Maybe in a couple years, but now it's too early for that.
