### ISSUE TITLE
Add field for dog=

### ISSUE THREAD

**Issue by RayBB** [Zverik/every_door#808]
I'm mapping some cafes in my area and many are explicit with yes/no for dogs.
Ultimately, I'd like to make a little interactive tool for my area to show dog friendly cafes (kinda like https://mapcomplete.org/pets.html?z=16.5&lat=4.731443461978699&lon=-74.04162554409845#node/703563897)
It would be nice if dog was part of Every Door for easily tagging for shops, restaurants, cafes, etc

https://wiki.openstreetmap.org/wiki/Key%3Adog

Thanks!

### Screenshots

<img width="383" alt="image" src="https://github.com/user-attachments/assets/3772fb5a-9ea1-463b-8ec2-11f8b256e1f3">

**Comment by mnalis** [comment]
Every Door (like many other apps, like StreetComplete, iD, etc.) [uses id-tagging-schema](https://github.com/Zverik/every_door?tab=readme-ov-file#presets-and-translations) for its list of presets (i.e. POIs and associated tags).

Thus, if you for example wanted to add `dog=*` to `amenity=restaurant`, you'd suggest a change to https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/restaurant.json#L13 (most probably under `moreFields`) or open an [issue in that repository](https://github.com/openstreetmap/id-tagging-schema/issues).

Alternatively (or until such change is suggested, accepted & implemented), you can use EveryDoor raw tag editor (that table-like icon in upper-right corner when you're adding or editing an POI) to add any custom tag, including `dog=*`. Or you can use that same [MapComplete  above](https://mapcomplete.org/pets.html?z=16.5&lat=4.731443461978699&lon=-74.04162554409845#node/703563897) not only to display map, but to add/update dog information too.

**Comment by RayBB** [comment]
@mnalis thanks for explaining that :)

I opened an issue in the appropriate repo
https://github.com/openstreetmap/id-tagging-schema/issues/1380
