### ISSUE TITLE
API error 404

### ISSUE THREAD

**Issue by nagisml** [Zverik/every_door#817]
On my Pixle 6 Pro I get always an API error 404 only with NULL as infos.
Maybe related to an Android 15 Upgrade.
How can I grab additonal infos regarding that issue?
![Screenshot_20241227-133355](https://github.com/user-attachments/assets/1f22b63c-a6c5-4ba0-9891-cade59431c9c)

**Comment by Zverik** [comment]
Try Settings → About → System Log please

**Comment by nagisml** [comment]
> Try Settings → About → System Log please

Done again just nooe. But the system log page is empty after submitting the text. Hope it arrives

**Comment by nagisml** [comment]
Issue found. An other app regstered itself as osm.org and so took the auth request.
