### ISSUE TITLE
Checkdate Button next to osm tags button in poi editor

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#82]
For now there is no way to exit the poi editor without changing something and applying the check date

**Comment by Zverik** [comment]
I did not get that. Did you mean, you cannot exit the editor without changing something? You can — just use any of "back" buttons.

**Comment by mfbehrens99** [comment]
![Screenshot_20220412-000147~2.jpg](https://user-images.githubusercontent.com/58851724/162840932-feb37746-8a25-45a0-8ae6-8260fc33de4e.jpg)

Sorry for being so inaccurate. It is a (small) feature proposal. Sometimes, I check POIs and I open the editor to see all the data. When you add any data you can press the save button to exit and the check date will be updated. However, when there is nothing to change (since all the data is correct and complete) you have to exit the editor, finde the Poi in the list and the press the check button.

I think it would be very east to put a button in the upper right corner to set the check date and close the editor view.

What do you think?

**Comment by Zverik** [comment]
Done in 0.1.4.
