### ISSUE TITLE
House numbers don't fit in the field

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#95]
![Screenshot_20220416-113703](https://user-images.githubusercontent.com/25708359/163668392-f7bd2ff5-b922-4d82-b25e-062971cfa54a.jpg)

**Comment by Zverik** [comment]
I think you have `building:levels=литБ` on this screenshot :)

**Comment by deevroman** [comment]
Already now you need to look closely to distinguish лит П' from "лит Д". But there are more interesting cases:)

![Screenshot_20220417-113218.jpg](https://user-images.githubusercontent.com/25708359/163706940-21fbd233-3ec3-4159-8f17-8d0c143eb1d1.jpg)

**Comment by Zverik** [comment]
Fixed in 0.1.5.
