### ISSUE TITLE
Add the ability to specify ref yourself

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#97]
1. Entrance ref can be more than 10
2. Entrance numbers may contain letters https://github.com/streetcomplete/StreetComplete/issues/3064#issuecomment-879318531

![Screenshot_20220416-111914](https://user-images.githubusercontent.com/25708359/163667865-0c869c58-e1df-4fc3-b469-317f9edf13cd.jpg)

**Comment by Zverik** [comment]
Done in 0.1.5.
